### ISSUE TITLE
Link to word on alc.co.jp

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#156]
```
Hi Martin,

I find myself using your excellent Aedict and when words can't be found I also 
use alc.co.jp which has very upto date definitions and modern word usages.
I was wondering if in search results a link to the word's alc page could be 
provided it could save users like myself the need to search twice when words 
cannot be found in Aedict because the dictionaries do not contain a word.

Best Regards,
Martin
```

Original issue reported on code.google.com by `mabra...@gmail.com` on 8 Apr 2012 at 9:04

**Comment by mvysny** [comment]
Closing as old, please feel free to open a new feature request regarding the EPWING dictionary. Please reopen if this alc.co.jp link is still valid and needed feature.

**Comment by mvysny** [comment]
EPWING support is coming: #623 
ALC support has been added, by means of launching an external dictionary from the dictionary entry screen. You can now edit the list of external dictionaries: #625
