### ISSUE TITLE
Add support for Google Drive API

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#261]
```
Google Drive API has been improved and integration may now be more easy. 
https://developers.google.com/drive/android/intro
```

Original issue reported on code.google.com by `martin.v...@gmail.com` on 18 Mar 2014 at 10:48

**Comment by mvysny** [comment]
I will implement this, but it will require the Google Play store to be installed, so this will not work on Blackberry nor Amazon devices.

**Comment by mvysny** [comment]
Google Drive API is moronic as it specifically requires to sign APK with sha1withrsa instead of sha256withrsa. I'm not going to change the signing keys just for this, marking as won't fix.
