### ISSUE TITLE
Send Flashcard Intent

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#264]
```
Hi, I'm one of the (many) developers for AnkiDroid (Tim). I just bought Aedict3 
the other day, and noticed that the intent is not getting sent as expected from 
Aedict. I believe the protocol for the intent was to have the following 4 
fields:

"SOURCE_LANGUAGE"
"TARGET_LANGUAGE"
"SOURCE_TEXT"
"TARGET_TEXT"

But when I sent a card I got this with everything mangled into one field:
SOURCE_TEXT="Aedict Notepad"
TARGET_TEXT="[default]\n強要 [きょうよう]:(P, n, vs) coercion, 
extortion, compulsion, force"

Was there a discussion about this somewhere, and it was decided that AnkiDroid 
should have to split up TARGET_TEXT? Or is it just some misunderstanding? 
Another option could be to extend the protocol to be more general.
```

Original issue reported on code.google.com by `perceptu...@gmail.com` on 2 Apr 2014 at 5:03

**Comment by timrae** [comment]
Did you ever get anywhere with the languagepod101 audio library?

**Comment by mvysny** [comment]
@timrae They replied with some questions, which I have answered, and afterwards there was no further reply. I would guess Aedict3 is too small to be commercially interesting to them.
Their audio links are public, but I simply can't make Aedict3 download their audio without their consent...

**Comment by mvysny** [comment]
I'm attaching the mail here:

Hello Ryan,
  thank you for your mail. Please find the answers below:

On 14.07.2014 04:14, ryan@innovativelanguage.com wrote:
> Hello Martin, 
>
> We would be open to discussing a yearly licensing agreement on our
> audio. Just a few questions:
>
> How many words will you need audio for?

There currently are 2000 users of the dictionary. Unfortunately I have
no statistics as of how many words they search for in total, what is the
variety of search terms and how often they wish to hear the audio.

> In what languages do you need the audio?

I just need the japanese audio, just results from links like this:
http://assets.languagepod101.com/dictionary/japanese/audiomp3.php?kana=%E3%81%93%E3%82%8F%E3%81%99&kanji=%E5%A3%8A%E3%81%99

> Do you have a budget in mind for this project?
>

Well, the project earns cca 350 EUR monthly in sales on Google Play,
which is nothing big. Income from other stores is negligible. So I can
spare at most 50-100 EUR yearly, but I assume that is too small for you.
So perhaps we can collaborate in a different manner - I can perhaps
place an advertisement displayed when the user clicks on the audio for
the first time.
Please let me know if this is acceptable for you.

Kind regards,
Martin

**Comment by timrae** [comment]
I see, that's unfortunate. Another is option is Forvo, which is supposed to be quite good. It seems their minimum price for commercial use is ~$350/year, but when I contacted them regarding using the API in AnkiDroid they seemed quite flexible, so it might be worth asking them.

**Comment by mvysny** [comment]
Forvo: good idea! This bug was originally for something else, I have opened a new feature request for this: #455 let us track the progress there.

**Comment by timrae** [comment]
To properly wrap-up this conversation, the `CREATE_FLASHCARD` intent is now deprecated in AnkiDroid in favor of the [new API](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API). See #454

**Comment by mvysny** [comment]
Thanks, the API looks great! Reopening.

**Comment by timrae** [comment]
Not necessary to reopen this, I just wanted to make it clear to anyone who re-discovers this thread through Google that `org.openintents.action.CREATE_FLASHCARDS` (and `org.openintents.action.CREATE_FLASHCARD` in general) are dead now. From v2.5 the new API should be used with `ACTION_SEND ` as a fallback

**Comment by mvysny** [comment]
You're right, closing this, let us watch the progress at #454
