### ISSUE TITLE
Strange Search results on Galaxy Tab 3 when searching for Japanese words

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#290]
```
What steps will reproduce the problem?
1. open Aedict and enter a Japanese word in the omni search box using hiragana 
or Kanji (I use Google Japanese Keyboard)

2. Search...

What is the expected output? What do you see instead?
The dictionary entry of this word should be displeayed (maybe sevaral as there 
could be several homophone word = same pronounciation but different 
meanings/kanji)
Instead on (empty) result is displayed for each hiragana/kanji entered.

Seach works fine for english words...

See Screenshots for more details

What version of Android are you using?
Android: 4.2.2
Kernel-Version: 3.4.34-2545684
Model: GT-P5210 (Samsung Galaxy Tab 3 WiFi)
Aedict Version: 3.4.19

Please provide any additional information below.
I also own a Samsung Galaxy S3 and a S3-mini and Aedict 3.4.19 works nicely on 
both.
I have tried to compare my settings on S3-mini and Tab and they seem to be the 
same... however i cannot garantee that the defect is not between keyboard and 
chair (or tablett and couch in this case) (^_~)v


```

Original issue reported on code.google.com by `Nedo...@googlemail.com` on 12 Jul 2014 at 6:13

Attachments:
* [Screenshot_2014-07-12-19-48-42.png](https://storage.googleapis.com/google-code-attachments/aedict/issue-290/comment-0/Screenshot_2014-07-12-19-48-42.png)
* [Screenshot_2014-07-12-19-56-59.png](https://storage.googleapis.com/google-code-attachments/aedict/issue-290/comment-0/Screenshot_2014-07-12-19-56-59.png)
* [Screenshot_2014-07-12-20-05-52.png](https://storage.googleapis.com/google-code-attachments/aedict/issue-290/comment-0/Screenshot_2014-07-12-20-05-52.png)
* [Screenshot_2014-07-12-20-08-51.png](https://storage.googleapis.com/google-code-attachments/aedict/issue-290/comment-0/Screenshot_2014-07-12-20-08-51.png)

**Comment by mvysny** [comment]
This bug can only be fixed at Samsung's side - I cannot override the String.compareTo() function which is internal and cannot be changed. Replacing all calls to String.compareTo() in Lucene would require very heavy patching and I don't even know if it is possible at all. Unfortunately, I have to mark this as won't fix.

**Comment by mvysny** [comment]
To sum this up, GT-P5210 incorrectly compares Japanese strings, which confuses all libraries and causes all searches to return zero or weird results. This is definitely bug in GT-P5210's Android's String.compareTo(). I cannot create a workaround for such basic function as it is used heavily all over in Android.
