### ISSUE TITLE
TAGs and Screen Rotation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#337]
```
When creating a tag info to a kanji, the tag windows closes when screen 
rotation happens, like when turning screen from vertical to horizontal by 
accident. It is annoying because then you can enter the tag info again from the 
start.
Thanks.
Android 4.4. CM11.
```

Original issue reported on code.google.com by `dezorian...@gmail.com` on 27 Oct 2014 at 3:27

**Comment by mvysny** [comment]
This is not easy to fix (the dialog remembers a list reference so it can refresh the list when tag is updated - yes, this is kinda antipattern but I have no time to fix this ;) . I assume that this is not a high priority bug and not a lot of users are bitten by this bug. Closing as won't fix for now, please reopen if this gets super-annoying.
