### ISSUE TITLE
Add support for Noto Sans CJK

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#398]
```
http://www.google.com/get/noto/

The thin version is really great for me on my device (note2) but i have some 
weird display on Aedict when using radical composition. See the attached 
screenshot.

```

Original issue reported on code.google.com by `martin.v...@gmail.com` on 18 Dec 2014 at 7:31

Attachments:
* [Screenshot_2014-12-17-19-13-44.png](https://storage.googleapis.com/google-code-attachments/aedict/issue-398/comment-0/Screenshot_2014-12-17-19-13-44.png)

**Comment by mvysny** [comment]
Submitted to Android as issue https://code.google.com/p/android/issues/detail?id=160547

**Comment by mvysny** [comment]
Android has some quirks in font rendering, so until they fix the font rendering (or the font itself), there is nothing I can do. Closing as won't fix.
