### ISSUE TITLE
Animation for kanji stroke order

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#431]
```
It would really be amazing if we could get some sort of gif animation for the 
stroke order of kanji. I've seen the iOS app called "Japanese". 

This is the only thing I miss about that app. 
```

Original issue reported on code.google.com by `roamingp...@gmail.com` on 27 Feb 2015 at 3:30

**Comment by mvysny** [comment]
Thanks for letting me know. I can add this, perhaps as a cheap paid extension.

**Comment by mvysny** [comment]
The application should be available soon at https://play.google.com/store/apps/details?id=sk.baka.aedictkanjidrawpractice
