### ISSUE TITLE
Kanji Recognition Problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#442]
```
Can you check on the kanji 多い (ooi) because I cannot seem to be able to 
draw that one correctly, well, at least not to the extent to make aedict find 
it.

If written in romaji it gets found of course.
```

Original issue reported on code.google.com by `dezorian...@gmail.com` on 8 Mar 2015 at 6:53

**Comment by mvysny** [comment]
Oh, taking a screenshot on Android is quite straightforward - just press VolumeDown plus Power button for two seconds, the screenshot will be captured and will be present in the top bar as a notification. You can then save it, mail it to yourself or share via other means.

**Comment by nirdavo** [comment]
:-) I did not realize it was that simple. Although on my oldish HTC the key combination is different. Anyway, here are two screenshots. The first one with the paid extension (no recognition at all, I scrolled through the whole list), the second one using the internal recognizer with a -very- sloppy kanji. But it still finds it!
![imag0308](https://cloud.githubusercontent.com/assets/11539563/6710124/df3698ba-cd7e-11e4-8933-004a70cca627.jpg)
![imag0309](https://cloud.githubusercontent.com/assets/11539563/6710123/df359762-cd7e-11e4-9fed-077f928d96f6.jpg)

**Comment by mvysny** [comment]
Oh man, that's definitely very sloppy :-D At least *try* to get those sekis underneath one another ;)

So, what now? If I try to run both algorithms and merge results, the result 多 will probably move from second line to fourth... and this will also probably worsen other results - this is something I would very much like to avoid. So, I'm strongly focused on letting this one go unfixed, but I need confirmation from you guys that it's okay with you to draw those oois properly :)

**Comment by nirdavo** [comment]
I seem to remember some of my japanese friends drawing 'ooi' the way I did in the top picture. And I find it surprising that the two algorithms give such different results!
However, you are right that changing the app for this single kanji, resulting in worse results elsewhere, is not the way to go. It will probably be too late for me to learn how to write a 'proper' 多, but this does not change the fact that I am doing it ... not entirely correct currently :-)
For my part, the discussion looks finished - let's keep the current version!

**Comment by mvysny** [comment]
Thanks, I agree, let's keep the current version. Thank you for being so understanding. Closing as won't fix, please feel free to reopen if you change your mind :)
