### ISSUE TITLE
Tag Menue---->so small now

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#444]
```
Maybe I am imagining things, but has the tag menue gotten smaller somehow? :O

I mean only 2 lines or so are in full view, the rest of the lines of text has 
to be scrolled down.
```

Original issue reported on code.google.com by `dezorian...@gmail.com` on 8 Mar 2015 at 8:30

Attachments:
* [Screenshot_2015-03-08-21-26-33.png](https://storage.googleapis.com/google-code-attachments/aedict/issue-444/comment-0/Screenshot_2015-03-08-21-26-33.png)

**Comment by mvysny** [comment]
I can enlarge the tag text box back to five rows if there is enough space on your phone, both for the dialog and the soft keyboard. Perhaps please share a screenshot, or let me know that five rows are okay :) Or, even better, I can make the dialog to simply fill the screen and show as many lines of text as it is possible. Let me try this first.

**Comment by mvysny** [comment]
Of course, setting the dialog to fill the screen is not possible as none of the suggested methods work. So, we are back at tampering on how many lines should the text view have. I think the old value was 7 rows, I set it to 4, if this is not enough, let me know how many rows do you want.

**Comment by mvysny** [comment]
Closing as not active, please reopen if necessary.
