### ISSUE TITLE
kanji radical quiz

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#447]
```
-rename "JLPT Quiz" to "Quiz" because it has jouyou, heisig etc.
-add kanji radical quiz
```

Original issue reported on code.google.com by `kazufuku...@gmail.com` on 13 Mar 2015 at 12:46

**Comment by mvysny** [comment]
So, if I understand correctly, in the quiz, you will be shown the kanji itself, without any meaning or translation (e.g. 頭) and you will need to enter "bean page" into the edit box - is this correct?

**Comment by mvysny** [comment]
Closing as not active, please reopen if necessary.
