### ISSUE TITLE
Same screen can be opened multiple times

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mvysny/aedict#448]
```
1) go to kanji details screen
2) tap on big kanji - another kanji details screen appears.
3) repeat step 3 many times

I quiet often open same page twice unintentionally. I think it's easy to 
prevent such behaviour and save unnecessary taps.
```

Original issue reported on code.google.com by `kazufuku...@gmail.com` on 13 Mar 2015 at 12:56

**Comment by mvysny** [comment]
Thanks for the bug, but I don't understand quite what would you like me to fix :) Aha! You would like to prevent to open yet another instance of the Kanji Detail page, from the Kanji Detail page which shows the very same kanji?

**Comment by mvysny** [comment]
Fixed, please reopen if the fix is not fixed properly.
