### ISSUE TITLE
Problem, Aedict has stopped (Kanji)

### ISSUE THREAD

**Issue by riskikereriski** [mvysny/aedict#450]
When I click Kanji, aedict has stopped. Why?Any solution?Thanks
![2015-03-17-23-56-07](https://cloud.githubusercontent.com/assets/11524881/6692760/3b9fe65c-cd01-11e4-9fdf-0684ad434d98.jpg)

**Comment by mvysny** [comment]
Hi, I apologize for this behavior. The best way is to let Android report the problem, which will bring the problem analysis to my console. If this is for some reason not offered by Android, please follow this tutorial: http://www.aedict.eu/faq.html section "Aedict 3 log"

**Comment by mvysny** [comment]
Please make sure that you have Aedict updated, the dictionary format has been changed and only Aedict 3.12 can open them.

**Comment by riskikereriski** [comment]
Okey, I will try it.
Thank you very much for your suggestion :D

**Comment by mvysny** [comment]
No problem, please let me know if that helped.

**Comment by mvysny** [comment]
Marking as closed, please feel free to reopen if the problem persists.
