### ISSUE TITLE
android 5.1 after update aedict always crashes after selecting words

### ISSUE THREAD

**Issue by ignatius2138** [mvysny/aedict#451]

**Comment by mvysny** [comment]
Hi, I apologize for this behavior. Please use the Android standard facilities to report the crash, so that I can see the details on my Google Play console. Meanwhile I will try to reproduce this in the Emulator.

**Comment by mvysny** [comment]
I failed to reproduce this in the emulator on Android 5.1 - I can select any text no problem. Please try to report the issue via Android, or check http://www.aedict.eu/faq.html section "Aedict 3 log".

**Comment by mvysny** [comment]
Closing as not active, please reopen if necessary.
