### ISSUE TITLE
OCR: Older Android versions

### ISSUE THREAD

**Issue by nirdavo** [mvysny/aedict#452]
Any chance to get the OCR extension working on older Android versions, like 2.3.5?

**Comment by mvysny** [comment]
I can try, sure... but OCR needs a LOT of CPU power, wouldn't it be very slow on those old phones?

**Comment by nirdavo** [comment]
Long texts would probably be too much for my old device, but short phrases or even single Kanji are helpful sometimes. For example, taking a shot of a sign while walking to get the reading of a single kanji, is faster than to draw it. Especially if you do not want to stop for that :-)
But do not put too much effort into it, devices with Android 2.x are on their way out anyway. If you decide to work on it, I will be available for testing!

**Comment by mvysny** [comment]
You're right, single kanji recognition should work. It should not be a problem to port OCR ... oh snap. Androids older than 3.x have a pretty stupid bitmap memory management, please see here: https://developer.android.com/training/displaying-bitmaps/manage-memory.html
Working around this particular issue may require a lot of effort, especially with this app which uses bitmaps heavily... I'll think about it once again, but unfortunately this seems like a quite a lot of effort :(

**Comment by nirdavo** [comment]
Like I said, if it is more work that 'half an hour', we should probably forget about getting it to run on older devices. In any case, I dropped my old phone last weekend and it has developed a splotchy screen now... I need to upgrade soon :-) 
So for my part, we can close this sugestion as "won't do"

**Comment by mvysny** [comment]
Oh, it's definitely more than 'half an hour' ;) perhaps 8 hours or so, I would need to implement a special cache of Bitmaps, to make sure that Bitmaps are evicted properly to avoid OutOfMemory errors...
Thanks for your info, I will close this bug as won't fix as agreed.
