### ISSUE TITLE
Add support for Forvo

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#455]
Tim of AnkiDroid: [Please add support for] Forvo, which is supposed to be quite good. It seems their minimum price for commercial use is ~$350/year, but when I contacted them regarding using the API in AnkiDroid they seemed quite flexible, so it might be worth asking them.

**Comment by timrae** [comment]
Thanks

**Comment by mvysny** [comment]
Finally found the time to do this. Forvo contacted, we'll see :)

**Comment by mvysny** [comment]
Unfortunately Forvo's final offer is 350 USD per year. This is not actually bad, but income from Aedict is not high enough for me to afford to pay such license. So, maybe later.

**Comment by mvysny** [comment]
I'm not sure whether this is still an issue - Google built-in sentence synthesizer is quite good at reading stuff. Please let me know whether this is still an issue.
