### ISSUE TITLE
"SOD Stroke Order Diagrams" listed twice in Dictionary Manager

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#456]
I notice that there are two "SOD Stroke Order Diagrams" entries in the Dictionary Manager list. I imagine one is the old bitmap version and the other is the new SVG version added in #453. I don't know if you're planning to remove the old one, but if they are both in the dictionary list, it might be cool to have some note about the difference appear in the list. Currently, users who are unaware might be confused as to which one they should download, or whether they need both.

**Comment by mvysny** [comment]
Thanks for letting me know, fixed, the second one should now read SOD Stroke Order Diagrams Vector. Aedict 3.13 will require this new file and will force the user to download this. The old one will no longer be needed with Aedict 3.13 and can then be safely deleted.
Closing this issue as fixed, please feel free to reopen if needed.
