### ISSUE TITLE
In kanji draw quiz, answer is revealed when any edge is tapped

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#458]
In the kanji draw quiz, the answer is revealed if I tap the top area of the screen, as expected. But it is also revealed if I tap the extreme left, right, or bottom edge of the drawing area. Sometimes this happens accidentally while I am in the middle of drawing. Is this the desired behavior?

**Comment by mvysny** [comment]
Thanks for letting me know. I think that this concept of tapping random screen contents to reveal answer is not intuitive - there must be a clear, visible button for that. I will add this button, which should also fix this issue.

**Comment by mvysny** [comment]
Fixed in Aedict 3.13
