### ISSUE TITLE
KanjiDraw: optionally show the start of the next stroke.

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#459]
A coloured dot or so to indicate from which end one should begin the stroke would be helpful. One should be able to turn it off though.
Perhaps a button, which (when pressed) will briefly glow a dot at the start of the next stroke?

**Comment by nirdavo** [comment]
Sounds useful for learning!

**Comment by mvysny** [comment]
Hmm, perhaps this is not needed after all? If you watch this video http://aedict.eu/kanjidrawpractice/index.html
at 0:29 - when I press the "play" button, the app shows the next stroke. But, perhaps the user only wishes to see the *start* of the next stroke, not the next stroke in its entirety...

**Comment by mvysny** [comment]
Closing as not active, please feel free to reopen if you deem this functionality important.
