### ISSUE TITLE
KanjiDraw. configurable pen thinkness, animation speed, colours

### ISSUE THREAD

**Issue by begal** [mvysny/aedict#460]
I am using a Note 4, when drawing a kanji with the pen the strokes are very thick. It feels unnatural. Can it be configurable?

Aside, seeing the animation for a a complex kanji is tedious (too slow). Variable speed would be nice to have. 
A different color for user input would be more clear perhaps.

What would be amazing is to automatically identify and mark the parts of the kanji where it deviates from standard drawing order. This is what you really want to memorize.

**Comment by mvysny** [comment]
Hi, thank you for your ideas, fixing now.

**Comment by mvysny** [comment]
Added configuration support for the pen thickness, animation speed and pauses between strokes. Regarding a different color: what do you think of the attached screenshot?

**Comment by mvysny** [comment]
![device-2015-03-27-165105](https://cloud.githubusercontent.com/assets/254091/6871272/bce7875e-d4a1-11e4-8253-2a299da8a026.png)

**Comment by mvysny** [comment]
I'm thinking a reddish color for stroke which is way off the standard drawing order.

**Comment by begal** [comment]
Thanks Martin. In my opinion this dark blue color is perfect.
Just another thing: When using KanjiDraw in a tablet it goes to portrait orientation always. I think it should behave as Aedict does.

**Comment by mvysny** [comment]
Thanks, yes, portrait mode on tablets does not make sense. I'll fix this.

**Comment by mvysny** [comment]
Implemented a very simple proper drawing check, this algorithm will be upgraded later on. Fixed in 1.2
