### ISSUE TITLE
Blank Welcome Buttons

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#462]
![screenshot_2015-03-27-11-29-07](https://cloud.githubusercontent.com/assets/254091/6871665/878edece-d4a4-11e4-8401-0b50ad767982.png)

**Comment by mvysny** [comment]
Fixed in Aedict 3.14. Google's dark theme is horribly broken :(

**Comment by mikemorr** [comment]
This button to enter the custom font path is blank in 3.14.
![screenshot_2015-03-31-10-20-29](https://cloud.githubusercontent.com/assets/2184268/6921449/f0ac7290-d792-11e4-8ed6-3cf84ebaa400.png)

**Comment by mvysny** [comment]
Thanks - fixed in Aedict 3.15.
