### ISSUE TITLE
CD Player: CD characters not displayed

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#464]
![screenshot_2015-03-28-18-47-06](https://cloud.githubusercontent.com/assets/254091/6884735/ae470904-d5ff-11e4-9a43-0e1f314c1c61.png)

**Comment by mvysny** [comment]
I have found out that these are a very special Roman characters, with Unicode range of U+FF21..U+FF5A, such as ＣＤプレーヤー . It seems that some phones have trouble rendering these characters, I will probably replace them in the dictionary files with their simple ASCII counterparts.

**Comment by mikemorr** [comment]
If I set the "Do not use Japanese font" preference in the Expert settings, the fullwidth letters and numerals appear, but the kanji/hanzi are shown in their Chinese forms instead of Japanese. I do not have any custom font path defined in the settings. I'll attach some comparison screenshots.

**Comment by mikemorr** [comment]
![screenshot_2015-03-29-14-22-31](https://cloud.githubusercontent.com/assets/2184268/6886997/cc212330-d620-11e4-9203-d126a68d8e6b.png)
![screenshot_2015-03-29-14-21-56](https://cloud.githubusercontent.com/assets/2184268/6886999/d938283e-d620-11e4-8f81-4c446496d29a.png)

**Comment by mvysny** [comment]
Thanks! Apparently your phone reject to render the special Roman characters when I'm using the bundled Droid Japanese font. I will fix this in the dictionary files, by replacing the special Roman characters with the regular ordinary ASCII Roman characters, which should work without any problem. Please wait for the dictionary updates, I will post here when the dictionaries are ready.

**Comment by mvysny** [comment]
Please update the dictionaries, the Tatoeba example sentences should now contain the regular ASCII Latin characters. Closing as fixed, please feel free to reopen if the characters are still not being displayed.

**Comment by mikemorr** [comment]
Thanks! Letters are displaying now, but there are some entries with numerals (for example １０進２進変換 / じっしんにしんへんかん) that still don't display.

**Comment by mvysny** [comment]
Can you please try also other characters like "?" and "!" あれが生徒会長？  and  わははは！そりゃ傑作だ！  if they are missing as well?

**Comment by mikemorr** [comment]
Thanks, good call, those fullwidth ? and ! also don't display on my phone.

**Comment by mvysny** [comment]
Should now be fixed, please update JMDict and Tatoeba dictionaries.

**Comment by mikemorr** [comment]
Some other characters that currently don't display on my phone in JMDict entries:
Fullwidth ampersand ＆ as in R＆D
Fullwidth commercial at ＠ as in ＠系
Fullwidth equals sign ＝ as in サピア＝ウォーフの仮説
Fullwidth full stop ． as in Web2．0
Fullwidth left parenthesis （ as in （w
Fullwidth plus sign ＋ as in C＋＋言語
Fullwidth solidus ／ as in DOS／V

Sorry :( I wish my phone would just display these characters like it ought to!

**Comment by mikemorr** [comment]
These CJK compatibility ideographs found in JMdict entries also don't display unless I set "Do not use Japanese font":
U+FA11 﨑 (たつさき)
U+FA1F 﨟 ("outdated" version of 臈 as in 中臈 ちゅうろう)

**Comment by mvysny** [comment]
Unfortunately there is nothing I can do about the kanjis. I mean I can implement workarounds for ampersands, @ and other stuff, but I can't render some characters with one font and some characters with another, that's not possible with Android... Sorry mate.

**Comment by mikemorr** [comment]
No problem, I figured :)

**Comment by mikemorr** [comment]
No problem, I figured there have to be some limits to what is possible :)

**Comment by mvysny** [comment]
Fixed in Aedict 3.15, you will need to head to Settings / Expert / Replace Roman Fullwidth and make sure that it is checked.
