### ISSUE TITLE
Cannot disable furigana

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#466]
Hi,

Very concerned about the implementation of furigana.   This is arguably very unnecessary, as you have s romaji to kana switch setting, plus the translation into English.  

Furigana is more for native Japanese, then it's for foreigners learning Japanese, particularly on a computer platform versus a traditional book.

Furigana, creates a visual mess, that many people can find disturbing.  Many would rather simply read the kanji directly and then look at the analysis for words they don't know.

The furigana setting to turn it off or on doesn't work properly or fully.  Even when set to off, furigana stills shows up in the Notepad quizzes, if you look up an example sentences.

**Comment by mvysny** [comment]
I have disabled furigana and notepad quiz from example sentences no longer shows furigana, as shown on my screenshot. Please provide a screenshot where the furigana is displayed on your phone.
![device-2015-03-30-102637](https://cloud.githubusercontent.com/assets/254091/6892792/5043e17e-d6c7-11e4-9e27-d26918377f42.png)

**Comment by nirdavo** [comment]
If you want my opinion: 
For the example sentences the furigana are useful - these sentences my contain kanji that you can not read.
For a quiz you are right - here the are arguably much less needed or even wanted.

**Comment by mvysny** [comment]
Aha, the example sentences tab in the JMDict Entry detail activity always shown furigana! Okay, fixed in Aedict 3.15.
