### ISSUE TITLE
Dictionary update fails with "can't create /sdcard/Android/data/sk.baka.aedict3/files/aedict3/dictionaries/JMDICT/null"

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#468]
Whenever you update JMDict in the Dictionary updater it fails, complaining that it can't create /sdcard/Android/data/sk.baka.aedict3/files/aedict3/dictionaries/JMDICT/null.
When you back out to the main menu you then get put into the original welcome setup screen saying you need to download JMDICT, which (fortunately) then works.
This has been happening on all three of my android devices and has persisted over several updates of the app.

**Comment by mvysny** [comment]
I can't seem to simulate this bug, but I think I know the cause of this bug (I keep dictionaries opened while I change them, not a good pattern ;). I tried to fix this by closing all dictionaries while the download goes, let us see whether it helps or not.

**Comment by mvysny** [comment]
Fixed in Aedict 3.15, please feel free to reopen if the bug occurs again.

**Comment by AAurion** [comment]
Also running into this problem, I had just deleted the dictionaries from my system memory to redownload them on my sd card. It keeps failing saying if failed to create diretory '/mnt/extSdCard/aedict3/dictionaries/JMDICT/null'. I'm pretty sure I'm up to date.

**Comment by mvysny** [comment]
Hi, thanks for letting me know. As a first aid, would you please try to reboot your phone if it makes the problem disappear?

**Comment by mvysny** [comment]
Android is so stupid it can't tell you why it failed to create the directory. What a failure.

**Comment by AAurion** [comment]
Yeah, I've reset my phone a few times since then, but nothing. 
The first time I tried, though, there wasn't enough space on the sd card, so I moved some stuff to my computer and tried again, then got this failure message.

**Comment by AAurion** [comment]
I tried uninstalling and reinstalling the whole app, but that didn't do anything either. I'm still able to download them to my phone's memory, though, so it's definitely just the sd card...

**Comment by mvysny** [comment]
Retarded Android can't tell us why he can't create a directory, what a joke. So, we will have to guess. Perhaps try to kill Aedict, then manuall deleting the entire /mnt/extSdCard/aedict3/dictionaries directory (perhaps the access rights have somehow changed for that directory?), then launch Aedict?

**Comment by AAurion** [comment]
Nah, that just brought me back to the starter screen where it asks to download the dictionaries, and then if I try to download to my sd card it gives the same IOException.

**Comment by AAurion** [comment]
Oh, ok. I redownloaded them to my device storage, force quit the app, and manually moved the folder to my sd card. When I restarted the app, it gave me the usual download dictionaries page, so I set the download path to my sd card and let it run. But, since it's already there, it didn't download anything or give any error message, and it seems to be working properly from what I can see.

**Comment by mvysny** [comment]
This is weird, it seems that Aedict can read from your SD Card, but can't write there. Aedict requests both the android.permission.READ_EXTERNAL_STORAGE and android.permission.WRITE_EXTERNAL_STORAGE permissions so the SD Card should be writable... I will create a hack which will tell us exactly why Android can't create the directory.
