### ISSUE TITLE
Question about kanji font used in Android

### ISSUE THREAD

**Issue by siritinga** [mvysny/aedict#469]
Hello.

I'm considering buying Aedict 3 for Android but I would like to know how the Japanese fonts are supported in non-Japanese androids.

This has been a bug for years (https://code.google.com/p/android/issues/detail?id=19660), by default a Chinese font is used for kanji so some kanji are displayed using the Chinese variant. Since Android 4.1 (I think) there is an option to select the locale for an application (http://developer.android.com/reference/android/widget/TextView.html#setTextLocale%28java.util.Locale%29) that in theory will use the correct Japanese font for the whole application. Alternatively I think it is also possible to attach and use another font to the application. 

There are lot of kanji that are not correctly displayed (all affected by the Han Unification, a terrible idea IMHO http://en.wikipedia.org/wiki/Han_unification)

I have checked Aedict 1 (the free version) and the Chinese version is used, but as I understand, it is no longer under development so maybe the situation is different in Aedict 3. 

Thank you very much.

**Comment by siritinga** [comment]
Ups, I just read the bottom of your homepage: "Aedict3 uses embedded Japanese font for proper character display".

So I assume it is correctly displayed :)

**Comment by siritinga** [comment]
Installed and working as expected :)

**Comment by mvysny** [comment]
Hi, yes, I had to bundle the Japanese font because of the Chinese font. I'm glad that it works for you. Just a tip: you can download another Japanese font to your phone and then point Aedict to that very font, via Settings / Expert.
