### ISSUE TITLE
System font used in some messages

### ISSUE THREAD

**Issue by siritinga** [mvysny/aedict#472]
Hi again :) 
I was playing with the custom font (from http://www.freejapanesefont.com/ , a very nice place to get fonts!) and it works great :) however, using a different font it is easy to spot where it is not being used. I found two places:
When searching, in the message "Searching 直る":
![2015-04-07 16 28 10](https://cloud.githubusercontent.com/assets/3969105/7029746/1c6da2c8-dd60-11e4-8a83-2b5be62c472c.png)

And if there is Japanese in the English translations. I suppose this is harder to fix because using the custom font for the whole message would be ugly (Latin characters in Japanese fonts usually are ugly and monospaced). For this it may be useful to set the Locale of the application to Japanese, but I don't know if doing this will force a 4.x version of Android:
![2015-04-07 16 28 46](https://cloud.githubusercontent.com/assets/3969105/7029785/4ee704b0-dd60-11e4-814c-8c42640c33cf.png)

Regards.

**Comment by mvysny** [comment]
Hi, thanks for the link - great site with nice fonts! Regarding the locale setting: Unfortunately there is no application setting to change the locale - you would have to change your phone's locale to Japanese to show fonts correctly.
If I change the font for the "Searching for: foo" label to Japanese, Android will for some reason start cutting off bottoms of the Latin letters (basically anything below the letter baseline). You can see this behavior in Settings / Dictionaries / Dictionary Manager (attaching a screenshot). Perhaps I should make this configurable? That is, either you will see jp chars correctly but latin letters will look chopped, or you will see chinese characters :)

**Comment by mvysny** [comment]
![device-2015-04-08-172649](https://cloud.githubusercontent.com/assets/254091/7048714/efb211c8-de14-11e4-8eb8-92eb3c51b8c4.png)

**Comment by siritinga** [comment]
I see! Certainly, it is better to have good romaji and ocassionally a bad kanji :) 

Regarding the Locale, I read that it can be selected with http://developer.android.com/reference/android/widget/TextView.html#setTextLocale%28java.util.Locale%29 but it may limit the Android version that Aedict can run on. I'm not an Android developer, I cannot help you there :(

**Comment by mvysny** [comment]
This is interesting, thanks for letting me know. I did not know that TextView.setTextLocale exists. It is indeed limited to Android 4.2 and higher, but I can simply not call this function on Android 4.1 and older, so it should be possible. I'll play with this and I'll let you know.

**Comment by mvysny** [comment]
It works ;) Fixed in Aedict 3.16, please reopen if there are still some texts on Android 4.2 and higher which do not render JP characters correctly.

**Comment by siritinga** [comment]
Thank you! I'll try as soon as I can update it :)
