### ISSUE TITLE
Mixed katakana/kanji cannot be found

### ISSUE THREAD

**Issue by siritinga** [mvysny/aedict#474]
Hello.

It seems that words that mix katakana and kanji (maybe also hiragana) cannot be found if written in romaji. For example, "furaigaeshi" won't find フライ返し.

Regards.

**Comment by mvysny** [comment]
finding words that consist of both hiragana and katakana when typing in romaji (e.g. サボる, you won't find it typing saboru).

**Comment by mvysny** [comment]
Fixed in new dictionary files, please wait until May 1st 2015 when the new dictionary files will be uploaded.
