### ISSUE TITLE
Quick adding of source + page number to word

### ISSUE THREAD

**Issue by TheHellstorm** [mvysny/aedict#478]
I use Aedict while reading Japanese books (yes, the classic style on dead trees :D) and searching unknown words. Afterwards I often want to have the context (e.g. for inserting the complete sentence in to Anki), so I take notes about the page number in the book. Currently I have to do this in a notebook or in a separate app on Android, which disturbes the reading flow a bit.

I think it would be super cool if that could somehow be integrated into Aedict. For example, first set “Currently reading book: ...” (would essentially be the category, but be valid for every search in the Aedict session) and then after searching a word having a input field (preferably numbers only, because that makes the keyboard larger) to input the page number where this was found.

Of course the fewer buttons to press, the better.

Just a quick inspiration, I don’t know if other people need this kind of feature or not :)

**Comment by mvysny** [comment]
Hmmm, it seems that you could use the Tagging functionality for this - just slide the entry to the left and click the 'tag' button (or long-click the entry and select 'tag entries' from the upper-right menu). You can then tag any word, kanji or even an example sentence any way you wish, e.g. "Page 45". Please let me know if this solves your problem fully.

**Comment by mvysny** [comment]
Closing as inactive, please reopen if the proposed solution does not work for you.
