### ISSUE TITLE
Option to disable left options slider while doing JLPT Quizzes with the kanjipad.

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#484]
Option to disable left options slider while doing JLPT Quizzes with the kanjipad.

**Comment by mvysny** [comment]
The main menu drawer must not be activated when swiping near the left edge of the screen in activities with kanji pad component, like in JLPT Quiz with the kanjipad and Kanji Search with the kanjipad. Perhaps the drawer can be disabled in such cases?

**Comment by mvysny** [comment]
Fixed in Aedict 3.17

**Comment by mikemorr** [comment]
Thanks for this! :)

**Comment by mvysny** [comment]
Sure, gladly :) Does the fix work properly?

**Comment by mikemorr** [comment]
Yes, it's very helpful! Thanks!
