### ISSUE TITLE
Transitive/intransitive buddies

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#492]
I just noticed the antonym support (#480), very cool! It made me think of another feature that would also be cool: transitive and intransitive buddy verbs, as are shown by [Tagaini Jisho](http://www.tagaini.net/manual#thedetailedview). For example, if you look up "hajimaru", it will have a link from there to the related verb "hajimeru", and vice versa.

**Comment by mvysny** [comment]
Nice idea! Is there any list of pairs of intransitive buddies? Or is it possible to somehow find the intransitive buddy automatically from the verb?

**Comment by mikemorr** [comment]
I'm curious about that myself. I wonder where the Tagaini team get their list from.

**Comment by mvysny** [comment]
I'm currently occupied with other things; would you please spare some time and ask the Tagaini guys where they got this list? :)

**Comment by mikemorr** [comment]
OK :) https://groups.google.com/forum/#!topic/tagaini-jisho/z4QM7Z8aH8Y

**Comment by mvysny** [comment]
Thanks! It seems that the info is present in JMDict after all, I must have missed it somehow. Please let me look at JMDict one more time ;)

**Comment by mikemorr** [comment]
Actually I think they might be searching for buddy verbs using some of this code: https://github.com/Gnurou/tagainijisho/blob/master/src/gui/jmdict/JMdictEntryFormatter.cc

**Comment by mvysny** [comment]
Thanks! The algorithm is as follows: take a substring of first writing which ends with a kanji, and an appropriate reading. Now, search for all verbs whose writing starts with given substring and the reading also starts with given reading substring. I have created a very similar algorithm (albeit with a lot more hacks) for matching B-Words in Tatoeba sentences, but I haven't thought of using the algorithm for finding the buddy verbs... 
I'll play with this algorithm a bit and I'll post more.

**Comment by mikemorr** [comment]
Their algorithm doesn't catch everything; for example, I would say 出る (deru) and 出す (dasu) should be linked.

**Comment by mikemorr** [comment]
Here are some lists:
http://www.csse.monash.edu.au/~jwb/ti_list.html
http://www.sljfaq.org/afaq/jitadoushi.html

**Comment by mvysny** [comment]
Thanks for the 出る (deru) and 出す (dasu), I should thus only match kanji form.

**Comment by mvysny** [comment]
Implemented in Aedict 3.19
