### ISSUE TITLE
Multiple dictionaries not searched for inexact queries

### ISSUE THREAD

**Issue by timrae** [mvysny/aedict#495]
Example: Download and enable the proper names dictionary
新木場駅: works by itself
新木場駅で: fails

Also, words in kana and deinflection don't seem to work for inexact queries:
新木場駅でキミを見ました

**Comment by mvysny** [comment]
Thanks, fixed in Aedict 3.18

**Comment by timrae** [comment]
Multiple dictionaries aren't working at all for me now after the latest update... none of the examples I gave in the issue are currently working.

**Comment by mvysny** [comment]
It is currently quite hard to write unit tests when two or more dictionaries are used at the same time, but I will try. Let me look into why 新木場駅 is not found in the names dictionary when sentence analysis is performed.
Regarding the 見ました not being deinflected correctly - yes, this is a known issue and it's not easy to fix. What the deinflection algorithm misses is the information whether 見 is v1 or v5 and what the exact reading is in this particular case. Can you please open a separate bug for this?

**Comment by mvysny** [comment]
I have tried the example sentence 新木場駅でキミを見ました and it is analyzed correctly into:
新木場駅: Shinkiba Station
で:
キミ: Kimi
を:
見る: to see (okay, this is fixed in yet-to-be-released Aedict 3.19, you will probably get 見 and ました or something similar).
My point is that it works for me and Shinkiba Station gets resolved properly. Have you configured Aedict to search in the JP Proper Names dictionary? You can do that in Settings or in Advanced search dialog (by pressing the upper-right "cog wheel", then touch "Dictionary" and make sure that both JMDict and JP Proper Names are selected.

**Comment by timrae** [comment]
I just tried again and it's working now. I did have the names dict enabled,
but since I didn't take a screenshot it's possible that I made a mistake
entering the kanji. I'll let you know if I experience it again.

By the way, is there any room for performance improvements? The search on
that example sentence takes almost 30s on my phone.

**Comment by mvysny** [comment]
Thanks, just let me know if it happens again.
On my phone the analysis of 新木場駅でキミを見ました takes less than 1 second (OnePlus One). Perhaps it is time to buy a new phone? :) Currently I don't have much time to improve the algorithm, perhaps it can be improved but it will still be slow as it makes tons of requests to the database. Which phone do you have?

**Comment by timrae** [comment]
I have an Xperia ZR, it's not super slow, but OK I'll give it a try on a different phone sometime

Chipset	Qualcomm Snapdragon APQ8064
CPU	Quad-core 1.5 GHz Krait
GPU	Adreno 320

**Comment by mvysny** [comment]
The specs of that phone are quite good actually, Aedict should definitely work okay on ZR. Hmm.. just a wild guess, perhaps you have the dictionaries on a SDCard and the dictionary lookups are therefore slower? On my phone there is no sdcard so I have dictionaries on the internal memory.

**Comment by timrae** [comment]
Nope that's not the issue but I'll do a bit more testing
