### ISSUE TITLE
ACTION_SEARCH_JMDICT API: Option to hide Aedict activity

### ISSUE THREAD

**Issue by timrae** [mvysny/aedict#496]
It would be nice to have an option to hide the UI in the ACTION_SEARCH_JMDICT API

**Comment by mvysny** [comment]
I believe the UI should be hidden automatically, when return_results is set to true - what do you think?

**Comment by timrae** [comment]
yes that seems reasonable

**Comment by mvysny** [comment]
Hmmm. Normally, I would hide the activity with android:theme="@android:style/Theme.NoDisplay" and change the theme if return_results is false or missing. Of course, second theme setting is ignored by Android, what a joke.
I will implement a new action, e.g. ACTION_SEARCH_JMDICT_NOUI, which will always have return_results set to true and will be implemented by a different activity.

**Comment by mvysny** [comment]
Implemented sk.baka.aedict3.action.ACTION_SEARCH_JMDICT_NOUI in Aedict 3.18

**Comment by mvysny** [comment]
More info here: http://aedict.eu/api.html
