### ISSUE TITLE
error when trying to save notepad as CSV

### ISSUE THREAD

**Issue by niffyat** [mvysny/aedict#498]
Hello, when I try to save or export my notepad list as a CSV, I am getting an error (see attached). Is there something I can do to fix it?
![screenshot_2015-05-06-09-42-04](https://cloud.githubusercontent.com/assets/887476/7498276/83e805b2-f3d4-11e4-8e51-fde380885818.png)

**Comment by mvysny** [comment]
Hi, thanks for letting me know. Please let me look at the Exporter code and I will come up with a workaround.

**Comment by niffyat** [comment]
Sure! Do I need to run something in the app to export anything for you?

**Comment by mvysny** [comment]
Oh no, thanks, I have all the information I need for now. Please be patient, I am extremely occupied at the moment. I hope the fix will be ready at the end of this weekend.

**Comment by mvysny** [comment]
I have *probably* fixed this issue - would you like to test the fixed version? If yes, please write me to vysny@baka.sk and I will send you a fixed version which you can simply install on your phone.

**Comment by mvysny** [comment]
OMG the issue was in my implementation of mkdir() - I need to release new Aedict ASAP.
