### ISSUE TITLE
suggestion: search by heisig

### ISSUE THREAD

**Issue by bengaskin** [mvysny/aedict#500]
I'm very glad the app includes heisig kanji names and numbers. But how about including a search by heisig name and search by heisig index number?
Incidentally even the main search ignores heisig names completely... try searching for nightbreak for example (no results found). Thanks!

**Comment by mvysny** [comment]
Good idea, thanks! I will include heisig keywords and heisig numbers into the index, so if you write either the heisig keyword or the heisig number into the omnisearch box, appropriate entries will be found.

**Comment by mvysny** [comment]
Implemented, will be available automatically when dictionaries are updated (next scheduled dictionary update: June 1st 2015). Just a reminder: you will need to search in Kanjidic, not in JMDict.

**Comment by bengaskin** [comment]
OK great, thanks!

Ben
