### ISSUE TITLE
Some common verbs don't deinflect from polite form

### ISSUE THREAD

**Issue by timrae** [mvysny/aedict#501]
Examples:
見ました　-> 見+真下
来ました　-> 来+真下

**Comment by mvysny** [comment]
I believe that the correct deinflection is 見ました -> 見る and 来ました -> 来る, is this correct?

**Comment by mvysny** [comment]
Fixed in Aedict 3.19.

**Comment by timrae** [comment]
Yes, thanks. Do you not speak Japanese?

**Comment by mvysny** [comment]
I did, long time ago ;) Nowadays, unfortunately I do not have any time left for learning Japanese, so I'm starting to forgetting even katakana.

**Comment by timrae** [comment]
Do the other common inflections also work?

E.g. 見た, 見たい, 見たかった, 見て, 見ていた, 見てた,  見られた, etc, etc?

**Comment by mvysny** [comment]
They do now :-)
見てた? Could you please paste a link for information about this form?

**Comment by timrae** [comment]
見てた is the everyday form of 見ていた

See example 4:
http://www.guidetojapanese.org/learn/grammar/teform

**Comment by mvysny** [comment]
Thanks, fixed in aedict 3.19
