### ISSUE TITLE
Kana Underneath Sentences

### ISSUE THREAD

**Issue by boku0801** [mvysny/aedict#503]
Is it also possible to toggle off/on  the Kana underneath sentences, similar to how 「a/あ」Kana/Romanji is toggled; if it cannot be toggled, can it be optionally (**disabled**)?

My eyes automatic look at it and I am forced to put much effort on attempting to ignore the Kana underneath sentences.  I know that the sentence analyses tab can serve to readily translate the meanings of sentences if they are not understood.

**Comment by mvysny** [comment]
So basically you wish to hide the kana of the example sentence in the first tab of the example sentence detail screen? Would you also like to hide kana in all lists which show example sentences as well?

**Comment by mvysny** [comment]
Probably yes if you wish to completely avoid the sentence reading. I will fix this, thanks for letting me know

**Comment by mvysny** [comment]
Fixed in Aedict 3.19; to hide the kana, just head to Settings / Expert Settings / Show Example Sentence Reading and uncheck.
