### ISSUE TITLE
Anki Export

### ISSUE THREAD

**Issue by myrmos** [mvysny/aedict#507]
Since a few days Aedict exports to Anki like this:
{残;のこ}す, {遺;のこ}す
when it is supposed to be:
残[のこす], 遺[のこす]
or:
残[のこ]す, 遺[のこ]す

the problem with the above is, that anki doesnt know, where the Furigana are and hence doesn't display them correctly. Insted it displays it like this:{残;のこ}す, {遺;のこ}す

**Comment by mvysny** [comment]
Hi, thank you for letting me know. I will fix this asap.

**Comment by mvysny** [comment]
Fixed, Aedict now correctly sends 残[のこ]す, 遺[のこ]す
