### ISSUE TITLE
Dictionaries error 

### ISSUE THREAD

**Issue by tomvanilla** [mvysny/aedict#509]
Hello, I haven't been able to use aedict3, which I really love and depend on, due to some error probably related to a dictionary error. Maybe after some Adroid update, I guess the app didn't have the permission to access the SD card any more. So I changed the dictionary location the the internal storage. But even though I downloaded most of the dictionaries, it doesn't swich back to the normal user interface, so I am not able to use the program any more. I am grateful for any suggestion.

**Comment by mvysny** [comment]
Hm, this is weird. In the welcome screen, please check the "Expert Settings" and verify that the directory is correct and actually points to the directory with dictionaries. If everything seems okay, please try to uninstall Aedict and then use some sort of a File Manager to delete *all* directories with dictionaries. Perhaps please backup your data to some cloud, e.g. Dropbox. If you encounter undeletable directories, please try to remove the SD card from your phone, insert it into your computer and delete the files there. Then, please install Aedict and try to download the dictionaries again.
Please let me know if this helped or not.

**Comment by tomvanilla** [comment]
Thank you for your fast reply. I think the main problem was that I couln't properly connect to WIFI as I am in China atm. But after reinstalling it (against expectations) it worked again - even with the internal memory as the dictionaries location. You can't believe how happy I am to get my precious aedict back after around 1 month without it. And I was bewildered to see all the beautiful new updates. I just bought all of your extentions as a little sign of my appreciation. Please keep up your awesome work!

**Comment by mvysny** [comment]
Dear Tom, I sincerely apologize for that you couldn't use Aedict for so long, and thank you for your kind patience and for your great support - it is really appreciated. Thanks! Just please let me know if there is anything I can do to improve Aedict.
