### ISSUE TITLE
Analysis Sentences

### ISSUE THREAD

**Issue by boku0801** [mvysny/aedict#512]
When a sentences is clicked on, it does not go to the analysis tab immediately, it first opens up the same sentence without the analysis in a new page...this seems like a wasted click. Can it be made so sentences clicked on go immediately to the analysis page?

Thank you.

**Comment by mvysny** [comment]
Sure, good idea. Alternatively, the sentence analysis tab can be merged with the first tab and the analysis could be shown below the sentence detail, what do you think?

**Comment by boku0801** [comment]
Thanks for the reply.

The alternative seems to be fine, but only if it does not impose the
furigana readings on the user (provides am option to immediately switch it
on/off). This is to maintain the option of the user having to choose to
test their knowledge of the kanji, as well as to switch between checking
that knowledge.

Thank you.

2015年6月6日(土) 1:56 Martin Vysny <notifications@github.com>:

Sure, good idea. Alternatively, the sentence analysis tab can be merged

**Comment by mvysny** [comment]
Fixed in Aedict 3.24, please reopen if this is not according to your requirements. This 'first tab split between the sentence and analysis' mode will be activated by default, to deactivate, just head to Settings / GUI Tuning / Dictionary Entry and uncheck "Sentence Analysis in first tab"

**Comment by boku0801** [comment]
This is what I had in mind. Thanks you.
