### ISSUE TITLE
Furigana Shortcut

### ISSUE THREAD

**Issue by boku0801** [mvysny/aedict#513]
Is it possible to have the option within sentences to switch between turning off/on the furigana for sentences? This will make it more easy than having to go to the settings each time to turn it on or off.

By furigana: the hiragana and katakana underneath sentences.

Thank you.

**Comment by mvysny** [comment]
Thanks for the idea, I'll look into that and I'll let you know.

**Comment by boku0801** [comment]
Thank you.

2015年6月6日(土) 1:57 Martin Vysny <notifications@github.com>:

**Comment by mvysny** [comment]
Fixed in Aedict 3.24
