### ISSUE TITLE
Kanji draw always available in Quiz

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#514]
Even in regular quiz
Something that is already available in Anki

**Comment by mvysny** [comment]
You can always switch the quiz type, by the upper-right menu button. Regarding Anki - little confused there, as I thought Anki to be a simple card show-guess system, with no support for drawing...
Please provide more info on what you had in mind.

**Comment by andrejrenard** [comment]
Just to be able to train to draw the kanji when doing the simple quizAndre

Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Martin Vysny <notifications@github.com> 
Date : 06/06/2015  13:08  (GMT+01:00) 
À : mvysny/aedict <aedict@noreply.github.com> 
Cc : andrejrenard <a.j.renard@skynet.be> 
Objet : Re: [aedict] Kanji draw always available in Quiz (#514) 

You can always switch the quiz type, by the upper-right menu button. Regarding Anki - little confused there, as I thought Anki to be a simple card show-guess system, with no support for drawing...

Please provide more info on what you had in mind.

**Comment by mvysny** [comment]
You can do that right now, by switching the quiz type to any of the "Draw kanji" options, either before the quiz is started, or in the quiz itself (by the upper-right menu button).
If this is not enough, please share your vision on how this should work.

**Comment by andrejrenard** [comment]
Haven't realize that.Quite good enough. Perhaps adding a button to access the drawing pad would be a bit simpler.Thanks


Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Martin Vysny <notifications@github.com> 
Date : 06/06/2015  13:34  (GMT+01:00) 
À : mvysny/aedict <aedict@noreply.github.com> 
Cc : andrejrenard <a.j.renard@skynet.be> 
Objet : Re: [aedict] Kanji draw always available in Quiz (#514) 

You can do that right now, by switching the quiz type to any of the "Draw kanji" options, either before the quiz is started, or in the quiz itself (by the upper-right menu button).

If this is not enough, please share your vision on how this should work.

**Comment by mvysny** [comment]
Hmmm, perhaps I can simply always display the kanji draw pad in the unused free space, to allow the user to doodle anything he wishes :)

**Comment by andrejrenard** [comment]
That would be perfect.


Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Martin Vysny <notifications@github.com> 
Date : 07/06/2015  13:09  (GMT+01:00) 
À : mvysny/aedict <aedict@noreply.github.com> 
Cc : andrejrenard <a.j.renard@skynet.be> 
Objet : Re: [aedict] Kanji draw always available in Quiz (#514) 

Hmmm, perhaps I can simply always display the kanji draw pad in the unused free space, to allow the user to doodle anything he wishes :)

**Comment by mvysny** [comment]
Thanks, fixed in Aedict 3.24. Please let me know if you find the solution not perfect for your needs.

**Comment by andrejrenard** [comment]
Hi Martin,
That's perfect. Thanks.
Add the possibility to add and timely show a short textual (toggle) hint 
to a kanji and I won't need AnkiDroid anymore (I wa Heisig's method o 
use no desu).
André

**Comment by mvysny** [comment]
Sure - can you please open a new feature request for that? Please also provide a bit more information - how should the hint look like, when it should appear... thanks!
