### ISSUE TITLE
Add a textual hint to a kanji

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#517]
It should be possible to add a short textual hint to any kanji.
This hint is shown as a toggle button (or a link) in the quiz mode (kanji first). Not shown by default.
It should be possible to edit the hint in the answer.
The hint is also shown (and editable) in the kanji tab.

**Comment by andrejrenard** [comment]
And in the top kanji view when a kanji is selected in the stat view of the quiz.

**Comment by mvysny** [comment]
I believe this issue has been closed by accident, reopening.

**Comment by andrejrenard** [comment]
Le 2015-06-12 09:33, Martin Vysny a écrit :
>
> I believe this issue has been closed by accident, reopening.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mvysny/aedict/issues/517#issuecomment-111393006>.
>
Yes indeed. Sorry.

**Comment by mvysny** [comment]
Currently you can tag any kanji and/or word by a text of your choice, just long-click any list and select 'Tag Entries'; or slide the list item to the left and click the 'tag' icon.
So, all what is needed is to show this tag text both in the 'Review Learning Progress' screen and in the quiz itself, in the 'answer' part. Please let me know if this is correct.

**Comment by andrejrenard** [comment]
I didn't know about this tag feature. And yes indeed allowing to access this tag (view and editing) in the Review Learning Progress screen and in the question and answer parts  of the quiz, would be perfect.

**Comment by andrejrenard** [comment]
The button would be "there" even there is no notes.

**Comment by mvysny** [comment]
Added the 'tag editor' menu item to the upper-right Quiz Activity menu. Fixed in Aedict 3.26, please reopen if the fix is not complete.
