### ISSUE TITLE
持って coming up in dictionary as 持久

### ISSUE THREAD

**Issue by boku0801** [mvysny/aedict#520]
When I attempted to copy a phase into the search, the word 持って appears as jikyuu (持久).  I copied and pasted twice and it happened both times. This is the sentence I pasted into the search: 御使いとは、人格を持った霊的存在です。彼らは知性、感情、意志を持っています
When I attempted to search for 持って as a lone search (not pasting the phrase), this did not occur; it would bring up different iterations of 持つ...

**Comment by mvysny** [comment]
Thanks for letting me know, I'll look into this and I'll post more.

**Comment by mvysny** [comment]
Thanks, one of the machine deinflection of 持っています is 持u which matched 持久 (because of mixed kana and kanji searches - e.g. search for 見ため will also find 見た目). Fixed, now correctly resolves to 持つ

**Comment by mvysny** [comment]
Fixed in 3.26
