### ISSUE TITLE
Allow in User Data to define a different default folder for the backups

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#528]

**Comment by mvysny** [comment]
Hi Andrej, thank you for letting me know. What is the reason for this request, is it because there is not much space on the internal memory of the phone?

**Comment by andrejrenard** [comment]
Hi MartinMy cloud requires a specific directory for synchronisation. André


Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Martin Vysny <notifications@github.com> 
Date : 01/07/2015  07:58  (GMT+01:00) 
À : mvysny/aedict <aedict@noreply.github.com> 
Cc : andrejrenard <a.j.renard@skynet.be> 
Objet : Re: [aedict] Allow in User Data to define a different default folder
  for the backups (#528) 

Hi Andrej, thank you for letting me know. What is the reason for this request, is it because there is not much space on the internal memory of the phone?

**Comment by mvysny** [comment]
Hi Andre, this is interesting. Which cloud are you using, OwnCloud? As far as I know, Dropbox does not have such requirement... Are you using any OwnCloud service in particular, or do you have your own server configured?

**Comment by andrejrenard** [comment]
Le 2015-07-01 09:46, Martin Vysny a écrit :
>
> Hi Andre, this is interesting. Which cloud are you using, OwnCloud? As 
> far as I know, Dropbox does not have such requirement... Are you using 
> any OwnCloud service in particular, or do you have your own server 
> configured?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mvysny/aedict/issues/528#issuecomment-117514616>.
>
It is in fact a cloud service from my phone company in Belgium (Mobistar).

**Comment by mvysny** [comment]
How does this cloud service work? Does it automatically backup particular directory on your phone?

**Comment by andrejrenard** [comment]
Le 2015-07-01 13:04, Martin Vysny a écrit :
>
> How does this cloud service work? Does it automatically backup 
> particular directory on your phone?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mvysny/aedict/issues/528#issuecomment-117608614>.
>
yes

**Comment by mvysny** [comment]
Fixed in 3.28
