### ISSUE TITLE
3.26 Something wrong with dictionary update

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#532]
I lost JMDict (-> downloadable) But got Aviation Dictionary I never Downloaded. I also lost Taotoeba and SOD Stroke Order Diagrams. 
Cannot download these dictionaries anymore. Nothing seems to get queued.

**Comment by mvysny** [comment]
Hi Andrej, thanks for letting me know and I apologize for the behavior, I'm currently fixing it and an update will be available today later on. The problem should only lie in the display code, but I'll look into this.

**Comment by mvysny** [comment]
Fixed in Aedict 3.27

**Comment by andrejrenard** [comment]
Yes indeed. Thanks for implementing my proposals. Aedict is now very 
useful as a support to Heisig method.
Perhaps you should start looking improving your SRS/Leitner algorithm by 
adding some features we can find in Anki for example.

**Comment by mvysny** [comment]
I do not use Anki myself, so I have no idea what features are missing in the Aedict's SRS/Leitner implementation. Can you please open a new bug and describe these missing features in more detail please?
