### ISSUE TITLE
Extend Leitner/SRS algorithm implementation for Quiz

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#534]
See http://ankisrs.net/docs/manual.html#what-algorithm.
You can also directly have a look at http://www.supermemo.com/english/ol/sm2.htm
You will need also to better define what is a card deck.

**Comment by timrae** [comment]
why don't you just use AnkiDroid?

**Comment by mvysny** [comment]
That is a valid point. Once the proper AnkiDroid export is implemented in #454, you should use AnkiDroid for quizzes. Quiz in Aedict is only rudimentary - Aedict is a dictionary after all, not a quiz engine. Closing as won't fix, please reopen if you have further comments.
