### ISSUE TITLE
Add the tag 'pen' with its color in the two Quiz screens

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#535]
Currently the tag can be accessed with the 'edit tag' entry in the top right menu of the two question/answer screens. It would be more helpful to have the tag 'pen' itself (as in the Nodepad screen) for an easier access during quiz and to allow to tag a quiz card with color (something I am already using in the Notepad).

**Comment by mvysny** [comment]
Thank you for entering the bug. Currently I am occupied by other work, but I will fix this next week for sure.

**Comment by andrejrenard** [comment]
No worries. That would be "la cerise sur le gâteau" as we say in French.
Your application is already very powerful to learn Japanese.

**Comment by mvysny** [comment]
![device-2015-07-28-173416](https://cloud.githubusercontent.com/assets/254091/8935806/ea966914-354e-11e5-9061-12afbb7449d8.png)
Please let me know if this is the correct fix.

**Comment by andrejrenard** [comment]
that looks fine


Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Martin Vysny <notifications@github.com> 
Date : 28/07/2015  17:35  (GMT+01:00) 
À : mvysny/aedict <aedict@noreply.github.com> 
Cc : andrejrenard <a.j.renard@skynet.be> 
Objet : Re: [aedict] Add the tag 'pen' with its color in the two Quiz screens
  (#535) 



Please let me know if this is the correct fix.
