### ISSUE TITLE
Possibility to add own (private) example sentences with their translation

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#537]
I am using Aedict when reading Japanese texts from external sources (for example NHK Easy Japanese, Japanese Reader, Wikipedia...). It would be nice to be able to copy/paste some sentences in Aedic, and to input their translation, in such a way all Aedict features would also apply to them (search, analysis and notepad). This should be a private database to respect the copyrights.

**Comment by mvysny** [comment]
Hi, this is a good idea. To input the example sentence you would need to input three fields: the version with kanjis, the version with no kanjis (kana reading only) and the translation. You can input those sentences one by one directly in Aedict, but I imagine that you already have a private database in, say, an Excel sheet, of those sentences. So perhaps it would be better if Aedict would support to mass-add those example sentences. What do you think?

**Comment by andrejrenard** [comment]
Hi martinLet's just start with a simple saving of a sentence that has been copied in aedic to be analyzed.


Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Martin Vysny <notifications@github.com> 
Date : 19/09/2015  14:12  (GMT+01:00) 
À : mvysny/aedict <aedict@noreply.github.com> 
Cc : andrejrenard <a.j.renard@skynet.be> 
Objet : Re: [aedict] Possibility to add own (private) example sentences with
  their translation (#537) 

Hi, this is a good idea. To input the example sentence you would need to input three fields: the version with kanjis, the version with no kanjis (kana reading only) and the translation. You can input those sentences one by one directly in Aedict, but I imagine that you already have a private database in, say, an Excel sheet, of those sentences. So perhaps it would be better if Aedict would support to mass-add those example sentences. What do you think?

**Comment by mvysny** [comment]
I see. If I understand correctly, you would like to have an option to add the sentence currently being analyzed, to a custom list. That is possible.
1. I can *maybe* construct the reading, but I can't construct the translation automatically. So, the translation will be blank. Is this okay?
2. I can add the sentence in question to a notepad, instead of a completely new custom list. Is this sufficient?

**Comment by andrejrenard** [comment]
Le 2015-09-21 08:39, Martin Vysny a écrit :
>
> I see. If I understand correctly, you would like to have an option to 
> add the sentence currently being analyzed, to a custom list. That is 
> possible.
> 1. I can /maybe/ construct the reading, but I can't construct the 
> translation automatically. So, the translation will be blank. Is this 
> okay?
>
Sure
>
> 2. I can add the sentence in question to a notepad, instead of a 
> completely new custom list. Is this sufficient?
>
Yes

**Comment by mvysny** [comment]
I have solved this as follows: when the sentence analysis kicks in, a very first result entry will be an example sentence entry, containing the original sentence. You can do anything you wish with this entry - you can copy/paste it, add it to the notepad, export to Anki, etc. I think that this solution solves this issue, please let me know if this solution works for you. An example screenshot follows:
![device-2015-09-21-151747](https://cloud.githubusercontent.com/assets/254091/9992728/2fb2f3d2-6074-11e5-82e8-74efce60742c.png)

**Comment by andrejrenard** [comment]
Looks fine.Andre


Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Martin Vysny <notifications@github.com> 
Date : 21/09/2015  15:19  (GMT+01:00) 
À : mvysny/aedict <aedict@noreply.github.com> 
Cc : andrejrenard <a.j.renard@skynet.be> 
Objet : Re: [aedict] Possibility to add own (private) example sentences with
  their translation (#537) 

I have solved this as follows: when the sentence analysis kicks in, a very first result entry will be an example sentence entry, containing the original sentence. You can do anything you wish with this entry - you can copy/paste it, add it to the notepad, export to Anki, etc. I think that this solution solves this issue, please let me know if this solution works for you. An example screenshot follows:

**Comment by mvysny** [comment]
Thanks ;) Please note that the reading may not be accurate and proper - do not believe everything you see ;)

**Comment by andrejrenard** [comment]
Hi MartinI indeed got the "auto-generated sentence entry" but I cannot save it in the notepad (only Copy to the clipboard in the menu)Andre


Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Martin Vysny <notifications@github.com> 
Date : 21/09/2015  21:03  (GMT+01:00) 
À : mvysny/aedict <aedict@noreply.github.com> 
Cc : andrejrenard <a.j.renard@skynet.be> 
Objet : Re: [aedict] Possibility to add own (private) example sentences with
  their translation (#537) 

Thanks ;) Please note that the reading may not be accurate and proper - do not believe everything you see ;)

**Comment by mvysny** [comment]
Hi Andre,
  you can add the sentence two ways:

1. swipe the sentence to the left - new buttons will pop up to the
right, just click the "Add to notepad" button.

2. You can long-click the sentence. After the sentence is selected, you
can then select "Add to notepad" from the upper-right menu.

Please let me know if this helps.
Thanks,
Best regards,
Martin

**Comment by andrejrenard** [comment]
Got it.Thanks 


Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Martin Vysny <notifications@github.com> 
Date : 27/09/2015  13:00  (GMT+01:00) 
À : mvysny/aedict <aedict@noreply.github.com> 
Cc : andrejrenard <a.j.renard@skynet.be> 
Objet : Re: [aedict] Possibility to add own (private) example sentences with
  their translation (#537) 

Hi Andre,

  you can add the sentence two ways:



1. swipe the sentence to the left - new buttons will pop up to the

right, just click the "Add to notepad" button.



2. You can long-click the sentence. After the sentence is selected, you

can then select "Add to notepad" from the upper-right menu.



Please let me know if this helps.

Thanks,

Best regards,

Martin
