### ISSUE TITLE
Add notepads as categories in JLPT Quiz (to be renamed?)

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#538]

**Comment by mvysny** [comment]
You can launch JLPT quiz from the contents of any notepad category, by touching the notepad tab for the second time, and then selecting "Quiz from this category". You can also launch JLPT quiz of the contents of the entire notepad, by clicking the upper-right three-question-marks icon (Notepad quiz).
If this is not what you meant, please comment here in a more specific way on what exactly you are missing. Thanks!

**Comment by andrejrenard** [comment]
Le 2015-07-13 11:31, Martin Vysny a écrit :
>
> You can launch JLPT quiz from the contents of any notepad category, by 
> touching the notepad tab for the second time, and then selecting "Quiz 
> from this category". You can also launch JLPT quiz of the contents of 
> the entire notepad, by clicking the upper-right three-question-marks 
> icon (Notepad quiz).
> If this is not what you meant, please comment here in a more specific 
> way on what exactly you are missing. Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mvysny/aedict/issues/538#issuecomment-120870186>.
>
It is just to access all quizes in one place.

**Comment by mvysny** [comment]
Aha! In the JLPT Quiz screen, right under the "Heisig Lesson 56", a new list should be added: the Notepad categories list, is that correct? Good idea, let me do that.

**Comment by andrejrenard** [comment]
Le 2015-07-13 13:12, Martin Vysny a écrit :
>
> Aha! In the JLPT Quiz screen, right under the "Heisig Lesson 56", a 
> new list should be added: the Notepad categories list, is that 
> correct? Good idea, let me do that.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mvysny/aedict/issues/538#issuecomment-120892785>.
>
Yes.

**Comment by mvysny** [comment]
Fixed in 3.28
