### ISSUE TITLE
Larger font for words in word quiz (kanji first)

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#540]
Same size as in kanji quiz. Reduced in answer.

**Comment by mvysny** [comment]
Hi Andrej, thank you for letting me know. Unfortunately, this is not possible. In the kanji quiz, I know that there is only going to be a single kanji, therefore I can use larger font to show the kanji. However, when the word quiz (or even worse, example sentence quiz - you can cram example sentences into notepad and quiz from the notepad contents) is used, there will be multiple words. If large font was used, the words could not fit into a single screen on a small mobile device, along with other information such as reading, translation, the kanji pad and other elements.
I can increase the font size, but only if the text is so small that it is barely readable.
