### ISSUE TITLE
Why is suru sometimes absent from sentence analysis

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#541]
![screenshot_2015-07-21-08-29-53](https://cloud.githubusercontent.com/assets/12773344/8794349/4b750adc-2f83-11e5-86dd-3c68a8c8d40e.png)

**Comment by mvysny** [comment]
Thanks for letting me know, let me look at it.

**Comment by mvysny** [comment]
Interesting, 為る is present in jmdict as both in naru and suru. In this particular sentence however, it should be present as suru.

**Comment by andrejrenard** [comment]
Yes it seems it is a mistake of the sentence analysis parser which 
transforms して into 為るand then into なる.

**Comment by mvysny** [comment]
Fixed in Aedict 3.28. Note that you will need to update the dictionaries; also, you will need to remove the example sentences from recently-viewed and the notepad - this fix will not work on old stored versions of example sentences.
