### ISSUE TITLE
Is it possible to parametrize the speech synthesizer?

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#542]
Voice and speed

**Comment by mvysny** [comment]
I can add setting for pitch and speech rate, let me play with this a bit.

**Comment by andrejrenard** [comment]
Well I am not sure I would appreciate to spend a whole week with a lady having the current voice...


Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Martin Vysny <notifications@github.com> 
Date : 21/07/2015  13:46  (GMT+01:00) 
À : mvysny/aedict <aedict@noreply.github.com> 
Cc : andrejrenard <a.j.renard@skynet.be> 
Objet : Re: [aedict] Is it possible to parametrize the speech synthesizer?
  (#542) 

I can add setting for pitch and speech rate, let me play with this a bit.

**Comment by mvysny** [comment]
Different voices are supported only since Android 21. Speech rate can be configured in Phone's Settings / Language / Text-to-speech / Speech Rate. And, I don't think that changing Pitch is going to increase your satisfaction with the lady's voice ;)

**Comment by mvysny** [comment]
I tried the different voice API. There are three voices on my phone, which are able to speak Japanese (the default Google TTS service). All of those three voices sounded exactly the same, perhaps these voices differ in some different parameters, latency or others, which are unimportant for Aedict and for this issue. So, no point in adding Voice configuration.
You will need to purchase a commercial Japanese TTS.
