### ISSUE TITLE
floating window click behaviour

### ISSUE THREAD

**Issue by aliceinwire** [mvysny/aedict#552]
it would be nice if you can customize the click behavior in the menu.
i would like as now, with click to toggle between little and medium, and using a long click for show the more big version with icon.

**Comment by mvysny** [comment]
Hi Alice, I'm not sure if I understand correctly. Would you like to have even bigger version of the floating window, accessible by long-click? That can be arranged. What do you mean by 'with icon' though? Can you please share a quick drawing of what do you have in mind? Thanks!

**Comment by aliceinwire** [comment]
ah sorry, i discover that you can toggle to small and medium by sliding touch. and i think is enough nice :)

**Comment by mvysny** [comment]
Thanks :) Yes, that feature is definitely under-documented, I will create a tip dialog for that.

**Comment by mvysny** [comment]
Fixed in 1.1-next.
