### ISSUE TITLE
Kanji Draw fails with IllegalStateException

### ISSUE THREAD

**Issue by kcroker** [mvysny/aedict#559]
When switching to Aedict from elsewhere and trying to draw kanji.  Invalid state: closed

**Comment by mvysny** [comment]
Hi, I'm sorry about that.  Can you please obtain the stack trace of the crash, as described here?http://aedict.eu/faq.html section aedict3 log. Thanks!

**Comment by mvysny** [comment]
Sorry, I found the bug, should now be closed. Please wait until Aedict 3.33 is released.
