### ISSUE TITLE
Really Big Information "i" next to kanji very distracting

### ISSUE THREAD

**Issue by kcroker** [mvysny/aedict#560]
This information should be available, but should not be so prominently placed as most people never care about this stuff. Since kanji is graphical, having an enormous graphic, almost 1/2 the size of the kanji itself interferes with visual recognition in my case.  Please remove these Information icons.

**Comment by mvysny** [comment]
Hm, I will try to make the icon smaller. Alternatively, I can move the information to another tab... I will fix this in Aedict 3.33 by making the icon smaller. If this still interferes with the kanji, please reopen and I will think of another solution.

**Comment by mvysny** [comment]
Fixed in Aedict 3.33
