### ISSUE TITLE
aedict floating windows

### ISSUE THREAD

**Issue by aliceinwire** [mvysny/aedict#562]
starting the floating window instead of setting page,
usefull for using 3rd party application like start it from tasker.
actually i have it associated to the assistant button, and i would like to open/focus the floating window and not the setting. (only if is already working/running ?)

**Comment by mvysny** [comment]
Please open Settings and make sure that the "always available" setting is checked. You can now show the floating window simply by clicking the Aedict Reader notification icon.

**Comment by aliceinwire** [comment]
I know about that, just get used of using the assistant helper for the old floating windows i was using. and it was nice.

**Comment by mvysny** [comment]
Hmm, can you please share a screenshot of the assistant helper you are using?

**Comment by aliceinwire** [comment]
sorry the name is "assistant request", i think is the button that start usually google now button

**Comment by mvysny** [comment]
Gotcha. The default way to start an app is to start its default activity. Every app has one, including Aedict Reader. The default activity for the Reader is the built-in Browser. However, the Popup itself is not an Activity per se, so it cannot be started as one.
However, there is a way. Please check if the Assistant is able to broadcast intents - if yes, just broadcast an Intent with precisely this action: sk.baka.aedictreader.action.NOTIFICATION
This should show the Popup itself.

**Comment by mvysny** [comment]
Hi Alice, can you please tell me whether sending the action sk.baka.aedictreader.action.NOTIFICATION helped or not? Thanks :)

**Comment by aliceinwire** [comment]
sorry bit busy studying, not tried yet.

On Fri, Sep 25, 2015 at 3:38 PM, Martin Vysny <notifications@github.com>
wrote:

> Hi Alice, can you please tell me whether sending the action
> sk.baka.aedictreader.action.NOTIFICATION helped or not? Thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mvysny/aedict/issues/562#issuecomment-143142126>.
>



-- 
アリス フェッラッシィ
Alice Ferrazzi

Gentoo,  If it moves, compile it!
My_overlay: https://github.com/aliceinwire/overlay
Gentoo Euscan: http://goo.gl/YNbU3h
Mail: Alice Ferrazzi <alice.ferrazzi@gmail.com>
PGP: 2E4E 0856 461C 0585 1336 F496 5621 A6B2 8638 781A

**Comment by mvysny** [comment]
No problem ;) Mr. Min Xuan Ng reported that launching intent with the action sk.baka.aedictreader.action.NOTIFICATION works correctly. Closing as fixed, please reopen if this does not work for you.

**Comment by aliceinwire** [comment]
just tried, is perfect. thanks as always
