### ISSUE TITLE
Amazon Appstore updates

### ISSUE THREAD

**Issue by seizonsenryaku** [mvysny/aedict#564]
Please update to the latest version(3.35). I'm afraid that if I update the dictionary I may break something due to version mismatch. I'm also having force close issues that I'm hoping are fixed in the newest versions.
Thanks!

**Comment by mvysny** [comment]
Sure, published. Please wait for the automatic upgrade.

**Comment by seizonsenryaku** [comment]
Can you update again? I updated the dictionaries and now can't see kanjikanji information due to bug #567

**Comment by mvysny** [comment]
Sorry about that, updated the Amazon version to 3.36
