### ISSUE TITLE
Failed to find Kanjis error

### ISSUE THREAD

**Issue by Okra555** [mvysny/aedict#566]
Hello, since the latest Aedict update, Kanji Pad extension is not being recognised.

I receive the following error when doing any strokes. Standard Kanji still works, but not the paid for extension. Is this a bug? Worked fine until just recently. Using Kindle store versions.
![screenshot_2015-09-14-23-47-03](https://cloud.githubusercontent.com/assets/14283766/9863810/4c8b7ddc-5b3b-11e5-9566-d6a2a183d14e.png)

**Comment by seizonsenryaku** [comment]
I have the same issue here. I believe it is because the latest kanjipad version available at Amazon is 1.3 instead of 1.5.

**Comment by mvysny** [comment]
Hi, thank you for letting me know. I am very sorry about that. I think that at some point, Amazon rejected to upload an app with no UI. At that time I stopped updating the Kanji Pad. However, I have now submitted the 1.5 Kanjipad update to the Amazon, it should be live any time now. Please update and let me know if the update works properly.

**Comment by Okra555** [comment]
Hello, yes this now works. Update 1.5 has solved the issue. Thank you.

**Comment by seizonsenryaku** [comment]
Works fine for me now, thanks.

**Comment by mvysny** [comment]
Thank you for letting me know, closing as fixed.

**Comment by a2de** [comment]
Not sure if I should open a new issue but I have been having this issue on Android 6.0.1 (KanjiPad 1.6)

**Comment by mvysny** [comment]
Thank you for letting me know. Please let us discuss this here. I am
unfortunately extremely occupied, but maybe I can help you. Please send any
screenshots or even device log stacktrace, any error message displayed, it
would help tremendously. Thanks!

**Comment by a2de** [comment]
Sure thing! here's the log (filtered aedict) and a screenshot.

![photo_2016-10-31_00-00-29](https://cloud.githubusercontent.com/assets/22232082/19845487/1ff9536e-9efd-11e6-91d0-98a0ad232c1b.jpg)


```
build.board: MSM8974
build.bootloader: unknown
build.brand: oneplus
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: A0001
build.display: MOB30Z release-keys
build.fingerprint: oneplus/bacon/A0001:6.0.1/MHC19Q/ZNH2KAS1KN:user/release-keys
build.hardware: bacon
build.host: sultan-box
build.id: MOB30Z
build.manufacturer: OnePlus
build.model: A0001
build.product: bacon
build.radio: unknown
build.serial: 8a25642f
build.tags: release-keys
build.time: 1477423664000
build.type: user
build.user: sultan
version.codename: REL
version.incremental: c7b3b0cdeb
version.release: 6.0.1
version.sdk_int: 23

10-30 22:51:08.990 W/ActivityManager(1122): Unable to start service Intent { act=sk.baka.aedictkanjipadext.action.ACTION_SEARCH_SERVICE flg=0x10 pkg=sk.baka.aedictkanjipadext } U=0: not found
10-30 22:51:08.991 W/ActivityManager(1122): Unable to start service Intent { act=sk.baka.aedictkanjipadext.action.ACTION_SEARCH_SERVICE flg=0x10 pkg=sk.baka.aedictkanjipadext.underground } U=0: not found
10-30 22:51:08.995 E/*zer$GooglePlayAnalyzer(14849): KanjipadExt Service probably died
10-30 22:51:08.995 E/*zer$GooglePlayAnalyzer(14849): android.os.RemoteException: Failed to connect to Aedict KanjipadExt 1.5 Search Service, is Aedict KanjipadExt 1.5 or higher installed?
10-30 22:51:08.995 E/*zer$GooglePlayAnalyzer(14849):  at sk.baka.aedict.remote.KanjipadExtClient.<init>(KanjipadExtClient.java:29)
10-30 22:51:08.995 E/*zer$GooglePlayAnalyzer(14849):  at sk.baka.aedict3.util.KanjiPadAnalyzer$GooglePlayAnalyzer.analyze(KanjiPadAnalyzer.java:77)
10-30 22:51:08.995 E/*zer$GooglePlayAnalyzer(14849):  at sk.baka.aedict3.unitedkanjisearch.KanjiDrawFragment.searchForKanjis(KanjiDrawFragment.kt:104)
10-30 22:51:08.995 E/*zer$GooglePlayAnalyzer(14849):  at sk.baka.aedict3.unitedkanjisearch.KanjiDrawFragment.access$searchForKanjis(KanjiDrawFragment.kt:27)
10-30 22:51:08.995 E/*zer$GooglePlayAnalyzer(14849):  at sk.baka.aedict3.unitedkanjisearch.KanjiDrawFragment$onCreateView$1.onStrokeEnd(KanjiDrawFragment.kt:81)
10-30 22:51:08.995 E/*zer$GooglePlayAnalyzer(14849):  at sk.baka.aedict3.kanjidraw.StrokePainterView.onTouch(StrokePainterView.java:192)
```

**Comment by mvysny** [comment]
Hmm, from the log I can see that you are using the OnePlus One. Do you have the Amazon Underground installed on your phone? Which source have you installed Aedict from?

From the stack trace It also seems that you are using an older version of Aedict. Which Aedict version have you installed please?

Also, these two lines are intriguing:

```
10-30 22:51:08.990 W/ActivityManager(1122): Unable to start service Intent { act=sk.baka.aedictkanjipadext.action.ACTION_SEARCH_SERVICE flg=0x10 pkg=sk.baka.aedictkanjipadext } U=0: not found
10-30 22:51:08.991 W/ActivityManager(1122): Unable to start service Intent { act=sk.baka.aedictkanjipadext.action.ACTION_SEARCH_SERVICE flg=0x10 pkg=sk.baka.aedictkanjipadext.underground } U=0: not found
```

From those it is clear that Android itself cannot find the KanjiPadAnalyzer service provided by the KanjiPadAnalyzer app. Maybe Aedict app has some permissions disabled, or maybe Aedict has been installed from Amazon Underground and KanjiPadAnalyzer from Google Play? I do not know ;)
