### ISSUE TITLE
3rd / 6th Edition Heisig Option - Unable to Switch (Dictionary Issue?)

### ISSUE THREAD

**Issue by ChristopherJonJensen** [mvysny/aedict#568]
I am currently running aedict on a Samsung Galaxy Tab 10.1 and a Nexus 4. 

Recently, after an update, I noticed that Heisig numbers were defaulting to 3rd Edition, with all dictionary entries under the Kanji tab now including the following fields: "Stroke, Grade, JLPT Level, SKIP, Radical, Parts, Unicode, Heisig 3rd." When I tried to change this in the options, I saw that my Heisig Edition was still set to 6, though the option text now reads "Sort Quiz Progress Review Grid based on Heisig Index." 

On my tablet, where I had not updated the dictionaries, the Heisig numbers were still displaying correctly. 

Has dictionary support for 6th Edition numbering been removed? If so, is it possible to revert to an older version of the dictionaries?

Thanks for your time (and for this terrific product),
-Chris

**Comment by mvysny** [comment]
Hi Christoper, thank you for posting of the bug. This change has actually been introduced not by the dictionary upgrade, but rather by upgrading Aedict to 3.32 and higher, as a fix of bug #545 . Please see http://aedict.eu/changelog.html for more details. Generally, the quick fields are not fixed to "Stroke, Grade, JLPT Level, SKIP, Radical, Parts, Unicode, Heisig 3rd." - you can now fully customize what items you wish to see.

After the change, the "Settings Heisig setting" only controls the Progress Review Grid. To show the 6nd Heisig index, just touch the little information (i) button right below the kanji itself, find the "Heisig 6th" row and touch the "Pin" icon to the left. You can pin and unpin any information piece you deem important; only the pinned items will appear in the quick list located to the right of the kanji.

Please let me know if this helps.

**Comment by ChristopherJonJensen** [comment]
Hi Martin,

Thank you very much for your prompt reply. Not only was this not 
actually a bug, but rather the inclusion of some additional (and very 
nice) functionality.

Also, thank you for all your work on this excellent tool. I am living in 
Japan now and make use aedict multiple times every day. It would not be 
an exaggeration to say that it has had an appreciable effect upon my 
quality of life!

Best wishes,
-Chris

**Comment by mvysny** [comment]
Thank you very much Chris for your praise, I am glad Aedict is helpful. Please let me know if there is anything I can improve.
If you like Aedict, perhaps you may find some Aedict extensions helpful, for example https://play.google.com/store/apps/details?id=sk.baka.aedictreader&hl=en
