### ISSUE TITLE
"Export Notepad to CSV" freezes Aedict

### ISSUE THREAD

**Issue by kuroi-hayabusa** [mvysny/aedict#575]
This feature crashes (in both options: send to disk or to apps). Version Aedict 3.38.6.

**Comment by mvysny** [comment]
I tried "Save to Disk" and this worked for me. I see no crash report at my Google Play console either. Can you please either submit the crash via standard Android mechanism (if possible), or please try to obtain the crash from Android log

**Comment by kuroi-hayabusa** [comment]
Actually, the app freezes rather than "crashing". When I select "Save to Disk" or "Save to app", it just freezes until I get the message from Android "Aedict itn't responding. Do you want to close it?".
This happens everytime I try in the two devices I have it installed.

I have several categories which a few hundred entries each in the notepad.

I have just sent the report (standard google report). Please let me know if this is sufficient.
Thanks for this epic app!

**Comment by kuroi-hayabusa** [comment]
Update: If I keep selecting "wait" to the "Aedict isn't responding" message, I eventually get the next menu and I am able to save the file (CSV). There are 3800 entries in my notepad, so I guess it needs the time to process it. I think I got a bit anxious when I got the "no responding" message.

**Comment by mvysny** [comment]
Understood. Yes, the export process is quite slow, I will need to show a "Please wait" dialog until it is completed, to remove "Aedict isn't responding" messages.

**Comment by mvysny** [comment]
Implemented the "Please wait" dialog in Aedict 3.38.7

**Comment by kuroi-hayabusa** [comment]
It seems there is still a problem: while the export file is being created, if you tap on any area of the screen except the dialog itself ("please wait"), the process is cancelled (no message, you just go back to the notepad). 

On the other hand if I do not click anyware or keep keep clicking on the dialog (so the phone screen does not go off) it finalises the export but it seems to take a lot of time (30mins for 4500 entries). I guess we cannot do much about that :)

On a related matter, as an enhacement: could the export to CSV be done to a single category, as an option, instead of the complete notepad? This could help with the processing time issue too.

Thank you!

**Comment by mvysny** [comment]
Sure, you can export just a single category, simply by long-clicking any item, then clicking the "Select-all" button and choosing "Export as Anki-Compatible CSV". Please try it out and let me know.

**Comment by mvysny** [comment]
You can also speed up the export by not including the example sentences field in the result CSV (the %examples% field, see http://aedict.eu/export.html for details). Example sentences lookup is slow and may slow down the export more than 100x.
Reopening, to show the "Canceled" notification if the export has been canceled.

**Comment by mvysny** [comment]
Please let me know if the export is actually sped up when the %examples% field is removed.

**Comment by mvysny** [comment]
Fixed in 3.39.5.
