### ISSUE TITLE
Popup/Reader

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#583]
The floating window triggered by copy is awesome. At the same time, the Reader mode felt confusing - I selected a single kanji, shared with the app, got large white screen with single kanji in the top left. Perhaps you could trigger one mode or the other depending on the length of the text?

**Comment by mvysny** [comment]
Hi Jakub, thank you. I can imagine that copy-to-clipboard launching a popup while the share action launching the analysis screen can be confusing. What length of the text should mark the boundary, perhaps 100 characters? Or even better, perhaps the popup should always be shown, with a new button which launches the "Reader" mode - what do you think?

**Comment by yacoob** [comment]
Ah, now we're talking. A github repo! For context: the first update in this thread is a quote from my Google Play review. :D

As for the issue itself: do you have any function that can classify/tokenize the text? If you do, then the decision can be made based on the number of tokens: <=5 - pop up, >5 - reader.

**Comment by mvysny** [comment]
Fixed in Reader 1.3.4, please let me know if the fix works for you.
