### ISSUE TITLE
Strange/German names for Heisig indexed kanji

### ISSUE THREAD

**Issue by bengaskin** [mvysny/aedict#584]
Hi there,
A long-standing issue in aedict for Heisig Remembering the Kanji information...
It looks like that the kanji from Remembering The Kanji volume 1 (pre-2010 editions) are pretty good but....

Others have seemingly German name in aedict.

Example: 冥 "unterwelt" in aedict (index 2841), was Hades in RTK3 [2841].

Around 2010 Heisig released an appendix for users of RTK1(to be used with all volumes of RTK1 I believe, certainly I used it with my RTK1vol3).

Search Google for "Newly Approved General-Use Kanji - Nanzan Institute", there is a pdf available at nanzan university, official from Heisig himself.

For RTK1vol3 and RTKvol6 in aedict, I believe both should have ideally dual index numbers...
300a {2841}, to handle both the RTK1 appendix and also the prior-published RTK3 index. The Heisig name in English is simply Hades.

I haven't checked thoroughly, but I would guess there could be over 200  kanji in aedict that don't have Heisig's English names but are in the combined RTK1 (including appendix) canon. To relate to RTK1, they would mostly all have index numbers under approximately 2200 and end with a,b,c, or d. Most end in a.

Many thanks for your consideration.

**Comment by mvysny** [comment]
I apologize for such a late reply. I do not posess the Heisig book myself, but I am not surprised that the index numbers do not match: current state of Heisig indices is basically a pile of bits and pieces collected throughout the internet. I have to look at the PDF you write about, perhaps it will contain all information I need for the Heisig integration to work properly.

**Comment by mvysny** [comment]
Unfortunately the PDF only contains several new characters. What I would need is a full list of, say, 2000 kanjis, with index numbers for all Heisig editions.

**Comment by mvysny** [comment]
There has been some activity in creating such data file in #423, but unfortunately it looks like it is dead now.

**Comment by mvysny** [comment]
The Jim Breen's Kanjidic2 does contain index numbers, but it does not contain kanji names at all... I am attaching current heisig data files here, please feel free to review them and fix if necessary... perhaps we may ask some guys at reddit for help? Anyway, attaching the files.

**Comment by mvysny** [comment]
Can't attach the files here (github limitation), just write me to vysny@baka.sk and I'll send them to you via mail.

**Comment by bengaskin** [comment]
Rtk official data electronically available (mysql)

Just letting you know what I've been using for the last year is the rtk official app on the Google play store published by an Indonesian developer under the moniker "mirai apps".

The app crashes a bit if you use it heavily. And it doesn't have a huge number of downloads. It's a pay-app. It really is official though: it's even linked to from the university site that Heisig is or was based at:

http://nirc.nanzan-u.ac.jp/en/publications/miscellaneous-publications/remembering-the-kanji-ap/

Despite the limitations of the app (i actually like it especially because I spent a large amount of time typing in notes to customize it to my needs... It just crashes a bit), the data that it uses is extremely accurate.

It has rtk1:5th Ed and rtk1:6th Ed, and also rtk2 and rtk3 indexes and names.

The 5th Ed keywords include post-2010 jouyou editions like this 1054a 尻 buttocks (please excuse the example, it's just the first one that came to mind that I know changed in 2010).

If it was already indexed in RTK1:6ed or RTK3, it can appear more than once with two indexes.

So in this case 1054a 尻 buttocks, but also 2220 尻 buttocks.

For me personally I'm fairly indifferent to rtk 3rd,4th,5th edition because they're all very similar, and I'm used to the very small variation in keywords, and there are no differences in index numbers. They're all good. Rtk6 has different indexing without the a,b,c,d suffixes so I don't use it because it doesn't match my prior learnings and paper book.

The GOOD NEWS is that if you install the app on your phone  (mine is rooted for what it's worth... It might have some impact..?) You can view the mysql files that include all the keywords and index numbers. The mysql files are not encrypted.

If you comb through the data you could get all the information you need to replace the German rtk names with English names, especially for the rtk1 post-2010 kanji (around 120-150 from memory), and all the rtk3 kanji.

It might be easier to do away with rtk3 and change aedict to support rtk5 and rtk6 so you don't have too many things to check and compare.

Anyhow, just letting you know.

I'm not sure exactly how I might be able to help without duplicating work, but if you think of something let me know how.

So, I'm sure your busy, and this might not be a high priority, but I thought at least I'd let you know.

The mirai app is why I haven't been desperate to get correct keyword information in aedict, but even still, having everything in one app instead of two would be wonderful.

Cheers

**Comment by mvysny** [comment]
Thanks for letting me know! It is good to know that there *is* accurate data on Heisig numbers. Yet, reverse-engineering mysql database may be a breach of copyright issues, so I'm not really comfortable doing that. But, if you could ask the Mirai developer to point us to the source of data, and that source of data would happen to be free to use under reasonable conditions, that would be really helpful.

**Comment by bengaskin** [comment]
It's the official app. As far as I can tell it seems to be commissioned by
the author. I suspect it would still come back to asking permission from Mr
Heisig himself. If you're happy for me to ask on your behalf I don't mind
doing a bit of the legwork, but please let me know.

**Comment by mvysny** [comment]
That would really help me out - thank you kindly! Please feel free to do this.

**Comment by mvysny** [comment]
I'm not sure what's the status on this. I vaguely remember that there has been some communication regarding this, but I'm not sure.

Closing since this is quite an old bug. Please feel free to reopen though, if the more accurate Heisig data is available.

**Comment by alex-eg** [comment]
Hello!
As of current Aedict Android version (with monthly subscription), this bug is still present.

The bug causes me some inconvenience every now and then, so I prepared a compilation of all RTK kanjis with their 6th edition number and English keyword, which I attach to this post. As I understand, it might help with fixing the issue.

[rtk_kanjis.tar.gz](https://github.com/mvysny/aedict/files/3521020/rtk_kanjis.tar.gz)

**Comment by mvysny** [comment]
@alex-eg This is awesome, thank you so much! I'll update the indexer to take advantage of this new information and I'll test a bit, to make sure that kanjis mentioned in this bug have a proper English heisig name now.

**Comment by alex-eg** [comment]
You are welcome!
And thanks to you for such an awesome dictionary app!

**Comment by mvysny** [comment]
Thank you for your kind support, both financial and for making the 6th index!

I've uploaded the new kanjidic dictionary, please upgrade all dictionaries and please let me know if everything is in order now.

**Comment by alex-eg** [comment]
Everything is ok now, I checked a couple of kanjis, known to have German translation earlier.
Now they are displayed correctly in English.
Thank you!
