### ISSUE TITLE
Listing all kanjis using a part

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#585]
Hi Martin,
Would it be possible from the parts and kanji tabs to list all kanjis and parts direct parent of a kanji/part (the reverse of the parts view)? As a table of (clickable) kanjis/parts ordered by stroke number?
Andre

**Comment by mvysny** [comment]
This is a very interesting feature, and this should be possible. Let me look at this.

**Comment by mvysny** [comment]
Fixed in 3.38.14.
