### ISSUE TITLE
Reader: potential privacy problem

### ISSUE THREAD

**Issue by yacoob** [mvysny/aedict#586]
If you copy some text into clipboard that does NOT have a kanji, you'll get a pop up from Aedict Reader telling you about it. The pop up contains the copied text. This is problematic, as copy/paste mechanism is sometimes a way people use password managers. This means, your password is being flashed on the screen. I'd suggest dropping the copied text from the pop up, and reduce the message to just the warning.

**Comment by mvysny** [comment]
Thank you, you are absolutely right.

**Comment by mvysny** [comment]
Fixed in 1.3.6
