### ISSUE TITLE
Notepad quiz enhancement

### ISSUE THREAD

**Issue by kuroi-hayabusa** [mvysny/aedict#588]
Hi Martin, I propose the following enhancements for your consideration:

1- Would it be possible to add a filter option when setting the quiz depending on a flag/field set to any word ("custom tags and colors" feature could be used for this. This could be used to filter out words you master and you do not want to include in the quiz (for example quiz only "red" words).

As you progress it can be helpful, as you want to focus mostly in new words or those you want to reinforce (but you could also use it to filter out words you want to save in the notepad but you want to learn/practise later).

I am aware that we have the SRS/Leitner method available, but I personally think this option could be a good help.

2- As option, could it be possible to review the "fail" words after a quiz. I am not sure how you could present this (maybe exporting them in a "quiz result category" in the notepad to be checked later after each quiz). I think it would help a lot to reinforce the study.

3- I think the quiz GUI is really good, but I think it could be improved making it more customizable. For example, instead of the "guess all reading" or even the "kanji practice" windows, sometimes I would prefer having a larger font (kanjis) and even direct access to information buttons: buddies, kanji, example,...

4- Only kana words appear as blank questions in "kanji first". This is correct by definition, but would it be possible to display the "kana" for these words only in this case.

**Comment by mvysny** [comment]
Hi, thanks for letting me know. I am somewhat reluctant to add more quizzing features, as there is AnkiDroid for that... but I will think it over.

**Comment by kuroi-hayabusa** [comment]
Hi, I understand, but please consider at least point 1. I am not a big fan of Anki :) and the quiz in Aedict links perfectly to the rest of the features of this great app, like kanji info, examples, buddies,...
I guess as an alternative, I can move "learnt" words in different categories. 
Thank you in any case!

**Comment by mvysny** [comment]
Fair enough :) I wil implement 1. and 2. For now I will only implement the tag-color-based filtering, no tag text-based filtering if this is okay with you.

**Comment by mvysny** [comment]
Implemented in Aedict 3.39
