### ISSUE TITLE
Support for Google Quick Search Box / Google Now

### ISSUE THREAD

**Issue by dijurido** [mvysny/aedict#589]
Hello,

thank you very much for creating such an amazing dictionary application. I am using Aedict for many years now and it helped me about a thousand times not only to understand my japanese friends better but also to boost my own japanese language skills. Thank you very much for all your efford!

I loved the feature of Aedict2 that you can get search results from Aedict2 also by using the Google Quick Search Box (I am still on Android 2.3). Aedict3 doesn't support this any more.

Is it possible to implement this feature again?

Best regards
Dijurido

**Comment by mvysny** [comment]
Hi, thank you very much for your kind support. Uff, that's quite an old Android you are using :) Does your phone perform well with Aedict3? The Google Search Box has been removed from newer Androids. I haven't removed the Search Box support per se, but I may have changed something which accidentally broke the support, and nobody complained ;) I hope that the integration is still possible, without breaking Aedict3 on newer Androids.

**Comment by dijurido** [comment]
Hi, thank your for your reply.

Actually Aedict2 is the reason why I am still using this old phone. :) It is a Xperia Pro from 2011 with a full QWERTZ-keyboard which also allows to type in japanese. I only need to flip out the keyboard, start typing a japanese word and I get the search results from Aedict2. So alltogether I can translate any japanese word in less than 2 seconds. I am happy to say: Aedict2 combined with the Xperia Pro is for me the most powerful and convenient japanese dictionary on earth.:)
I can upgrade my phone to a newer version of Android but for me the quick searching with Aedict ist more important than new features.

As for Aedict3:
Aedict3 ist performing well on my phone. It takes the application longer to start/load but I get search results a quick as with Aedict2.

**Comment by mvysny** [comment]
I agree, I am starting to dislike the software keyboard myself :) I have fixed this issue and re-introduced the old 2.3 global search stuff. However, accidentally I have marked Aedict to require Android 3.0 at minimum, reverted back to 2.3. However, I cannot keep 2.3 compatibility for long... Perhaps you can try to launch Aedict3 from an icon or from a notification bar instead, or perhaps you can look at this, perhaps you may find this to be a replacement for quick search: https://www.youtube.com/watch?v=zGALYnUrbJY - the popup window also supports text search, more info here: http://aedict.eu/reader/

**Comment by mvysny** [comment]
Please do not forget do enable Aedict3 in the Global Search settings - enter the Search, then press the Menu button, then Settings and enable Aedict3 as a searchable source.

**Comment by mvysny** [comment]
Fixed in Aedict 3.38.14

**Comment by mvysny** [comment]
I apologize, I have to drop backward compatibility with Androids older than 4.0.4: #712
