### ISSUE TITLE
Some parts have no content

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#591]
I found 2 (right part of 残 and upper part of  甬) but there can be more.
They are dead ends we cannot add to a notepad and to which we cannot add a tag

**Comment by mvysny** [comment]
Hmm, this is interesting. Kanji 戋 0x620b is not present in the Kanjidic, neither is マ (it is katakana letter MA). Therefore, I cannot obtain proper entries for those two characters and therefore they cannot be further worked with, unfortunately.
There is however something you can do: can you please ask Jim Breen to add this specific kanji 戋 0x620b to the kanjidic?

**Comment by andrejrenard** [comment]
But there are lots of them. The best would be to develop a routine to find them and ask Jim to adapt his database. I am not sure about Jim's db. Is there only one version?

**Comment by mvysny** [comment]
I'm not sure if I understand correctly. AFAIK there is exactly one free Kanji database, the Jim Breen's Kanjidic2: http://www.edrdg.org/kanjidic/kanjd2index.html

**Comment by mvysny** [comment]
Andrej, could you please paste some more missing characters here? Thanks!

**Comment by jimmubreen** [comment]
Kanji 戋 0x620b is not in the Kanjidic2 database because it's not in any of the 3 JIS standards that identify the kanji used in Japan (JIS X 0208/0212/0213). See: http://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E6%88%8B
It may seem an arbitrary limit to draw, especially as with Unicode people in Japan can, and do, use characters outside that set, but it does make the task of database management much more manageable.

**Comment by mvysny** [comment]
Thank you very much Jim. It now makes sense for 戋 to never appear in Kanjidic2.
So, Andrej, what now? If you wish to attach tags to that particular character, I would need to create a dummy Kanjidic2 entry, which will only contain given kanji and no other information - no onyomi, kunyomi, readings,SKIP nor any other information. I can imagine this for users to be very confusing...

**Comment by andrejrenard** [comment]
Hi Martin
I think it's still worth to create the "dummy" kanjis to be able to add them to notepads, to attach them a tag and to search for their junctures.
Andre

**Comment by mvysny** [comment]
I tried to do just that, and it seems to be working. I cannot do this for the マ character though, because it is actually a katakana letter, not a kanji. However, this should work for all other parts.
Fixed in 3.39.1
