### ISSUE TITLE
Where are the kanji parts coming from?

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#592]
Some obvious parts seems to be lacking.
For example 疋 in 走.
But there are many more examples like these.
I guess it's history at face value. Not always useful though.
Is there a way to "improve" the parts source/file?

**Comment by mvysny** [comment]
Hi, sure, there is a way. I am periodically polling the data from the
kanjivg project.  Please head to the kanjivg homepage for more information:
http://kanjivg.tagaini.net/

**Comment by andrejrenard** [comment]
Thanks Martin. I will suggest some modifications to kanjivg.

**Comment by mvysny** [comment]
Thanks - this way, everyone using kanjivg will benefit from the fix. I will
leave this bug opened until the missing parts are added both to kanjivg,
and by me to aedict.

**Comment by mvysny** [comment]
Closing since this bug relates to kanjivg Rather than to aedict.
