### ISSUE TITLE
New interface

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#594]
Better readibility indeed but I found the new black icons for notepads and tags on the main screen too intrusive. In grey instead? 
And what about a colored tag icon in place of the lateral bar?

Thanks for the jubctures. Really useful.

**Comment by mvysny** [comment]
No problem ;) I will make those icons greyish.

**Comment by mvysny** [comment]
Just to be sure, please attach a screenshot of the screen with the intrusive elements. You can perhaps highlight those elements, say in some drawing program with a reddish circle or something.

**Comment by andrejrenard** [comment]
Perhaps the black filled arrow could be emptied keeping just a colored edge?

![screenshot_2015-11-26-16-35-41](https://cloud.githubusercontent.com/assets/12773344/11426489/eed419d2-945c-11e5-98a7-7074983a74e6.png)

**Comment by mvysny** [comment]
I have made the icons smaller and blueish, please let me know if this is acceptable.
![device-2015-11-26-173319](https://cloud.githubusercontent.com/assets/254091/11427541/e90bb9f4-9463-11e5-9c1d-7462cab76c23.png)

**Comment by andrejrenard** [comment]
I still believe it's a bit too intrusive. Icons and colors are secondary informations compared to semantics ones. But do not rely on me only to take a decision.

**Comment by mvysny** [comment]
That blue-on-red looks terrible. I'll return it back to black, hopefully when the icons are smaller they will not be as obtrusive as before. Fixed in Aedict 3.39.1
