### ISSUE TITLE
Send as flashcard not working correctly

### ISSUE THREAD

**Issue by Dinges666** [mvysny/aedict#596]
Not sure if I'm doing this right but...

Since yesterday, after an update of ankidroid, the send as flashcard doesn't work correctly anymore. You can't choose what's going to be in the card anymore, and you can't select which deck it gets added to.

At the moment, if you use it, you will see the message that 1 card has been created. If I look in ankidroid right afterwards a new deck called Aedict 3 is created, and instead of 1 card, it will have 3 seemingly identical ones.

So not sure if this is supposed to be solved at ankidroid's end or at your end, but I would like to have the functionality back if possible.

**Comment by mvysny** [comment]
I have written to Tim Rae (the author of AnkiDroid) about this: (I have exported 2 cards). Anki shows that it has 6 cards in the deck, yet studying them only shows 2 cards.

The response: Generally users don't want to study all 3 cards on the same day, so Anki automatically postpones "related" cards until the next day. You can disable this behavior by going to "deck options" from the reviewer -> new cards -> bury related new cards.

It would probably be best if Tim could comment on this.

**Comment by mvysny** [comment]
Related issue: #454

**Comment by diogovk** [comment]
@Dinges666 I was also confused about this at first.
But the 3 cards are not identical. They are:
(Front)->(Back)
Meaning->Kanji/Reading
Kanji->Reading/Meaning
Kanji/Reading->Meaning

Anki then has some "intellingence" that stops you from reviewing the same "Fact"(i.e. same information in different cards) in the same day, and postpones cards accordingly.

**Comment by timrae** [comment]
It's working as expected. You can edit the new aedict note type to display the cards however you want. Once you customize the note type to how you want it, you'll be able to add cards to AnkiDroid much faster

**Comment by Dinges666** [comment]
Then it seems I misunderstand something. When I choose to send as flashcard, it gets added automatically to a deck, instead of the one I want it to go to(as before). Is that not supported anymore, or am I missing something? I did look at the settings and manuals to see if it's there, but either it's not or I overlooked it(quite possible)

And I apologize for reporting wrong about the cards, I didn't notice because I never use Kanji/Reading->Meaning so I confused it with Kanji->Reading/Meaning and because it suddenly got added without me saying so.

**Comment by mvysny** [comment]
I'm not using AnkiDroid much so I have to rely on others regarding this :) However, the API allows me to specify the Deck Name, so I can ask for the Deck Name prior performing export. Would this help?

**Comment by Dinges666** [comment]
Being able to set a default deck or asking prior to export would probably help...I say "probably" because I don't use a lot of functions in ankidroid and anki, and I basically stopped when it was good enough for daily use. I probably would have to change some options to actually make the new version work for me, but that's for me to figure out and hasn't much to do with aedict.

Thanks for responding so quickly btw, and for not getting angry at my goof-up.

**Comment by mvysny** [comment]
Oh, no problem. Actually, you made a point: you intuitively tried to use a feature and it felt confusing. This is definitely a bug in Aedict or AnkiDroid - using stuff intuitively should bring expected results. Unfortunately, there is not much I can do as this is more on AnkiDroid's side I believe. No offense, but a friend of mine also complained AnkiDroid to be initially complicated and not very intuitive. But let us focus on the bug here.
I will implement Aedict to ask for the deck name prior export. Let us see if this helps.

**Comment by timrae** [comment]
> I will implement Aedict to ask for the deck name prior export

You can get a list of deck names from the API, please check the javadoc. I would prefer that you gave you the option to "not ask me again" on the first export, as the whole point of the new API for me is to export cards from Aedict without any additional button presses.

> Is that not supported anymore, or am I missing something? 

You can disable the API under advanced settings in AnkiDroid, which should result in Aedict choosing the old method of the sending the data to AnkiDroid. Note however that will disable it for **all apps**, which is probably fine now, but will likely prevent you from doing some cool stuff in the future. 

I'd recommend persevering with the new method a bit longer and providing feedback to @mvysny on how Aedict can be improved to support your workflow.

**Comment by timrae** [comment]
> No offense, but a friend of mine also complained AnkiDroid to be initially complicated and not very intuitive.

Some people do find AnkiDroid to be unintuitive at first, but what they usually mean is that they find the concept of spaced repetition unintuitive. This is answered in our FAQ:

https://github.com/ankidroid/Anki-Android/wiki/FAQ#how-can-i-study-my-cards-exactly-when-i-want-to

**Comment by mvysny** [comment]
Added Settings / Export / AnkiDroid Deck Name. When set, Aedict will directly export to this deck and will never ask.

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.2
