### ISSUE TITLE
Exports only 1st example sentence to Ankidroid

### ISSUE THREAD

**Issue by corndruid** [mvysny/aedict#597]
After looking up a word in the dictionary and moving to the Examples tab, there is the option to long-click a single entry and Send as Flashcard. But no matter which entry I select, only the first example sentence of the list is sent to Ankidroid.

**Comment by mvysny** [comment]
Thank you for letting me know, fixing now.

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.2
