### ISSUE TITLE
Use a snackbar to show the dictionary updates available message

### ISSUE THREAD

**Issue by timrae** [mvysny/aedict#598]
Instead of a Toast, it would be nice if you used a [snackbar](http://developer.android.com/reference/android/support/design/widget/Snackbar.html) with an action button to start the update. Dictionary updates occur on a sufficiently frequent basis to make it annoying to go into settings to update.

**Comment by mvysny** [comment]
Good idea, thanks!

**Comment by mvysny** [comment]
Fixed in 3.39.3
