### ISSUE TITLE
Reader: Quick adding to list

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#600]
Quick adding to list. Please add a button so you can quickly add a word or words to a list for future review.

**Comment by mvysny** [comment]
This can be implemented by adding a new button to the Reader, Add To Notepad. This button, upon clicking, will ask Aedict to analyze given text and then add it to the Notepad automatically. Aedict should ask for a category and add the items there.

**Comment by mvysny** [comment]
> And yes, I know that I can add by switching into the Aedict app, but I was hoping for a one push button that brings up your lists so you can quickly add the word/s to a list without switching into the Aedict app. It would be really helpful for when you are reading an e-book and you want to quickly add a word and continue on reading. I say this because I feel that switching into another app really takes me out of the story. 

Launching Aedict is thus not an option. Perhaps the Reader should pack a simple entry list named "For Future Review" - a full-blown Activity which lists marked entries. Upon clicking on an entry, Aedict entry detail activity can be launched. User can mass-select entries and delete them.

**Comment by Shoeslayer** [comment]
Thanks for adding this for me. That "For Future Review" list sounds like a good idea. So, if I understand it correctly, you press a button that adds your selected words to the "For Future Review" list(or section?). I'm guessing accessing this list would bring you into the Aedict app. Then from there, you can pick and choose which words to delete/transfer to different lists.

My idea was to have the add-on do all that. For example you selected a sentence "私は寿司が好きです。" Then you press an "Add to List" button. The add-on then separates the sentence into it's different parts for you to select. 
Like this(the 。 are selection buttons):
。私
。は
。寿司
。が
。好き
。です
You select the one's you want, then it lists your lists in the same fashion.

I don't mind if you go with the "For Future Review" button(seems easier to implement than mine). Just thought I'd throw in my idea out there.

**Comment by Errol246** [comment]
Is this list intended to work with the export to Anki  function? Is there a button that facilitates the instantaneous creation of Anki cards for each of the words on that list? That would be useful.

**Comment by mvysny** [comment]
@Shoeslayer I really love your idea of separating the sentence into words and check the ones to process further. After you select all of the words, a dialog may pop up, asking what would you like to do with those words. Let us start with two options: the "Add to Notepad" (with the usual "Select Notepad Category or Create New Category") and "Export To AnkiDroid" (which should solve the idea that @Errol246 is proposing).

---
[Please support Aedict if possible](http://aedict.eu/sponsors.html)

**Comment by mvysny** [comment]
Oki doki, finally implemented this feature :) The Mode Switcher screen got upgraded and now shows the list of current words. The words are all selectable and can be selected and deselected. Select any combination you wish and click "Add To Quick List" button - Popup will add selected words to a Quick List. You can gradually fill the Quick List with any words you desire; then simply press "Show Quick List" to show the list in Aedict3. You can then do anything - mass-add all entries to the Notepad, launch a quiz, export them to AnkiDroid... Please test out this feature and let me know what you think.
Implemented in Reader 1.3.10.

**Comment by Shoeslayer** [comment]
Great Job!

Works very nicely. There doesn't seem to be any huge problems, but there
are a few small things that I've noticed.


   1. It's possible to add the same word twice(or more) to the quick list.
   However, I am not able to select individual words/kanji on the pop-up to
   delete them. The only option is to delete the entire quick list. Having an
   option to re-select and delete individual words/kanji would be nice.
   2. Having said that, it would be nice if selecting individual
   words/kanji would bring up the definition again on the "reverse side" of
   the pop-up.
   3. When you copy a new selection, the mini quick list on the pop-up
   doesn't update until you switch to the "reverse side" where the definition
   is and switch back.

That's all so far. Thanks for all your hard work!

**Comment by mvysny** [comment]
Thanks for letting me know!
1. Hmm, there is not much space to allow of re-selection and deleting of individual words from the quick list... tough :-) Would it help if I fixed the Quick List so that it would never contain duplicates? Actually, the Quick List was not meant to hold data persistently - it is just a simple assistant which allows you to grab words while reading an article. It is expected that you transfer the list to Aedict and store it in a Notepad, and then delete the Quick List.
2. You can actually long-touch the word/kanji button, to learn the definition. To show definitions of words in the Quick List, currently you need to show the Quick List in Aedict.
3. Thanks for letting me know, I'll fix this.

**Comment by Shoeslayer** [comment]
I see.

Well, removing the possibility of duplicates would be best then.

Thanks again for this update. Really appreciate it!

**Comment by Errol246** [comment]
Thanks for implementing this feature, it works very well. Well done!

Another feature request for me would be to allow words looked up in Aedict3
to be added to a quick list for later review without the reader. I need to
prioritise which words to learn and therefore would like to be able to pick
and choose after a reading session.
2016/03/22 22:22 "Martin Vysny" <notifications@github.com>:

**Comment by mvysny** [comment]
@Errol246 thanks :-) I think your feature request is not related to Reader - could you please open a new feature request for this feature?

**Comment by mvysny** [comment]
@Shoeslayer fixed: no dupes are now allowed in the Quick List; Quick Add buttons are now correctly updated. Fixed in Reader 1.3.11
