### ISSUE TITLE
Reader: Swipe-to-close not always working 

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#601]
I found the swipe to "action" option. Noticed that swiping doesn't work all the time. Sometimes it takes 3-4 swipes before it performs the action(using a 5.2 inch phone). Is there a trick to get it working 100% of the time?

**Comment by mvysny** [comment]
the activation of the swipe depends on how much
you try to swipe the popup out of the screen. Apparently, the trigger
value is set very high and the Popup is often not dismissed when it
should be. This is no problem, I will try to lower the trigger value a
bit; we need to find a delicate balance here, so that the Popup is not
dismissed unwantedly.

**Comment by Shoeslayer** [comment]
Thanks for adding this too. I tried it and realized that when I "throw" the pop-up to the left or right it doesn't work all the time. So, I tried what you said brought it to the edge and it works all the time. Especially helpful how it becomes more transparent to signal the swipe is being registered.

**Comment by mvysny** [comment]
Thanks for letting me know. I would advise against closing/dismissing "thrown" popups, as I can imagine this would happen a lot unwantedly - for example, when you want to "shoot" the popup upwards but you don't want it to be closed.
So, if you agree, I will close this as won't fix.

**Comment by Shoeslayer** [comment]
Yeah, I agree. Now that I figured it out, it's not a problem.

**Comment by mvysny** [comment]
Closing as WON'T FIX as agreed.
