### ISSUE TITLE
Add same word/kanji to multiple lists.

### ISSUE THREAD

**Issue by Shoeslayer** [mvysny/aedict#603]
I was wondering if it'd be possible to add the ability to add the same word/kanji to a multiple lists. I believe that if you try to do that now, it just erases it from the old list and adds it to the new one. I ask for this because most of my lists are the names of books I'm reading, games I'm playing, etc. I like knowing where I've seen the word/kanji before if I do end up searching for it again. That way, if I end up adding the same word/kanji to many lists, I'll know I'm having trouble with it and can then focus on it more.

**Comment by mvysny** [comment]
Hi, I apologize for such a late reply. By list you mean the notepad category? If I remember correctly, one user asked specifically for this deduplication feature. No worry though, I can add a setting for this. Just please confirm that it is indeed the notepad category you mean

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.4

**Comment by mvysny** [comment]
To enable this, please open Settings, User Data and make sure that the "Notepad: Add Unique Only" setting is unchecked.

**Comment by Shoeslayer** [comment]
Wow, thanks for implementing the feature so quickly. I just have one more
thing regarding this feature and I'll be out of your hair. You know how
there is a icon that shows which notepad the word is in if you search for
it. When I add the same word to multiple notepads, then press the "go to
notepad" icon that is next to the word when you search for it. It only
takes you to the first notepad that this word was added to and ignores the
other(s). I suggest that the "go to notepad" icon say "Multiple"(or
something similar to inform the user the words in multiple notepads)
instead of the first notepad's name that this word was added to. Then, when
you click on the "go to notepad" icon of a word that's in multiple
notepads, it brings up a pop-up window showing you which notepads the word
is in(the pop-up window can be just like the one you get when you add a
word to a notepad). Then from there you can press which notepad you want to
go to.

I really appreciate all the help you've given me recently. I'll make sure
to recommend this app to other Japanese learners.

**Comment by mvysny** [comment]
Thank you for the suggestion, that is a good idea. Reopening, please give me some time to implement this :)

**Comment by mvysny** [comment]
Implemented in Aedict 3.39.5
