### ISSUE TITLE
Reader: Add a button for kanji listing

### ISSUE THREAD

**Issue by andrejrenard** [mvysny/aedict#604]
Many clicks are now needed to access a list of all kanjis of the selected text.
It would be nice to have a button next to the left "list" button to show a list of all kanjis with their meaning and their tag. Also ideally clicking on one in the list should open its kanji view in Aedict.

Very useful app. Thanks Martin and happy new year.

**Comment by mvysny** [comment]
Thank you, Happy New Year to you, too :)

**Comment by mvysny** [comment]
Fixed in Reader 1.3.10. I have added new button to the mode setting "list" menu - confusingly it has the same Aedict icon as the button on the main button bar... Nevertheless, long-touching this button will reveal that it will only handle kanji characters from the copied text to the Aedict.
