### ISSUE TITLE
list of buddies

### ISSUE THREAD

**Issue by kuroi-hayabusa** [mvysny/aedict#605]
In the current version, you get only entries "starting with" the selected word in the "buddies" tab. I believe it would be interesting to have a complete list (words containing the string in any position). Or maybe have it as a setting option (like the one in the search menu: words ending with, stating with, any position...).
I love the buddies feature. It is an excellent tool to increase your vocabulary.

**Comment by mvysny** [comment]
Good idea, thanks for letting me know. I'll implement this.

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.4
