### ISSUE TITLE
"代々" finds results only with JP match "Exact" and "EndsWith" but does not find anything with "StartsWith" or "Substring"

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#606]
1) "代々" finds results only with JP match "Exact" and "EndsWith" but does not find anything with "StartsWith" or "Substring" which is a bug or really confusing feature.

**Comment by mvysny** [comment]
Verified. It seems that 々 is somehow special to Lucene and borks the search results. I will investigate more and I'll let you know.

**Comment by mvysny** [comment]
Fixed. Please update to JMDict newer than Jan 7th, 2016 and let me know if this is fixed.

**Comment by Necsord** [comment]
From my understanding JMDict is just a dictionary which is fetched by Dictionary Manager from 3rd party server. Is there any way to check what is the current version or date of JMDict installed? Also is there any place to track release of JMDict update?

**Comment by mvysny** [comment]
I will eventually index the JMDict file published by Jim Breen later on today, and I will upload the indexed versions to my server. You can check updates to these indexed versions, by launching Aedict's Settings, Dictionaries, Dictionary Manager.

**Comment by mvysny** [comment]
Also, Aedict checks for new dictionary versions once per day and will notify you, should there be any updates to the dictionary files.

**Comment by Necsord** [comment]
Works fine with today's JMDict update, thanks!

**Comment by mvysny** [comment]
Thanks for confirmation, that's good to hear.
