### ISSUE TITLE
Interrogation marks break the search in aedict

### ISSUE THREAD

**Issue by nake90** [mvysny/aedict#607]
Hi all,

When searching some text that has interrogation marks ('?') in it the whole text is skipped and no results are returned.

This is most probably because of the new search mechanic added a few updates ago that allowed to search for incomplete sentences by using the '?' character if I'm not mistaken. But it is extremely inconvenient when used with aedict-reader because no results show up at all when for example I'm having a conversation in LINE and I don't understand a question they asked me. In that case I have to minimize, open aedict, paste there the text and delete the question mark manually.

The solution I propose is to delete the special characters from the text to search in aedict-reader before sending it to the search engine, or adding a mode to aedict that when the search comes from the reader the special characters are not used as such.

Thank you very much in advance!

**Comment by mvysny** [comment]
Thanks for pointing this out. You're right - when the query contains ?* then probably the sentence analysis is accidentally turned off. Let me look at this.

**Comment by mvysny** [comment]
This issue was present in Aedict itself, rather than in the Aedict Reader. I have fixed this in Aedict 3.39.5, please be patient until the upgrade is released.
