### ISSUE TITLE
Direct Anki export, don't export Furigana/Ruby

### ISSUE THREAD

**Issue by derpda** [mvysny/aedict#608]
I just bought this app, very good first impression.
As a heavy Anki User both on Android and Desktop, export to Anki is an must for any dictionary app for me.
I use Imiwa? on an iPad I own and so far its export function was unbeaten. Aedict3 has the custom csv export which, on first try, I like. I will open a separate issue related to that though. I could not use direct Anki export in any app yet as all of them fail to do what I would like them to.

Now to my issue:
When exporting directly, I would like to only export the Kanji (ie 日の出) without any Furigana/Ruby.
The Japanese Support in Anki does the Furigana for me and I accordingly use two fields for Expression and Reading. I need the Expression field to generate audio files with AwesomeTTS.
What I would love to see would be a fourth option for direct export in the form of "Kanji, Meaning", ie "日の出, sunrise".

Best regards and thanks for making the app =)

Peter

**Comment by mvysny** [comment]
Hi Peter, thank you very much for your kind feedback, I'm glad that you like Aedict. Aedict is able to export entries both to the Desktop Anki (via CSV) and a direct export to the AnkiDroid app (which you can install on your Android-based phone for free).

When exporting to the CSV, you can disable the furigana support by unchecking the Settings / Export / Export Ruby Furigana checkbox.

When exporting directly to AnkiDroid, there are multiple fields exported: the Furigana, but also the Kanji version (exported as the 'Expression' field) and the Reading (exported as the 'Reading' field). You can then edit the Card Model in AnkiDroid, to not show you Furigana, but to show you the 'Expression'+'Reading' fields.

Please let me know if this helps.

**Comment by derpda** [comment]
Hi mvysny,
Thanks for answering. CSV export seems to work like a charm and I have used the direct export of a Kanji list already, which also worked flawlessly. I very much appreciate those two features and I think they cover most of what I need the app to do for me.

This issue is exclusively about the direct Anki export of a single word to AnkiDroid. As I understand, there are two basic ways to do this:
1. Share (First Entry Only)
This option fills two fields in a card of my choice. Basically very useful. However, the reading is always included on one of the two. I don't need to import the reading at all and actually adding it to either the English side or the Kanji side makes this feature unusable for me. On the English side, it defeats the purpose of even studying the card, as the solution is already there. Coming up with the Kanji, should that be the task, is then way too easy.
Having it in the Kanji field prevents me from using AwesomeTTS to add sounds to the cards and prevents the addon Japanese Example Sentences from finding example sentences.
Suggestion: Add option to simply share Kanji and Meaning, no Reading at all. I wonder if anybody actually uses the option to put the reading with the English meaning...
That would make this a very nice feature, especially because I can use my own card layout.

2. Export to AnkiDroid
This one I can't seem to influence with the settings at all, apart from it sending the cards to a deck of my choosing. It includes a lot more information than the 1 option, for example what type of word it is as well as example sentences. I don't necessarily need that information and the example sentences are actually rather in the way, as I generate them with an Anki addon later on. But that could easily be worked around by changing the note type and only carrying over the relevant information. That of course is somewhat annoying. My ideal setting for this would be:

Expression field: Only Kanji
Reading field: Exactly that what is now in the Furigana field
Meaning field: Meaning
Furigana field: Nothing. Japanese support for Anki uses the fields Expression and Reading, complying with the default syntax of that very commonly used Anki addon seems to be a good idea to me.
Grammar: Just as it is, not very important to me.
GrammarShort: Same

In general I would prefer the first option, as it lets me use my own card type. Both are fast, which is nice.

I hope that made my issue clear!
Thanks again for answering.

Best regards,

Peter

**Comment by mvysny** [comment]
Thanks! 
1. No problem, I'll add such format. 
2. Hmm. Changing the note type, albeit a bit annoying, is the official way to go. Tim of ankidroid made that clear to me. Yet, I can create a new Anki model for your purposes of integrating Anki with awesometts ; you can then switch to this model in the settings. But,  if fixing of just the 1. Is enough for you, perhaps we can skip this point for now.

**Comment by derpda** [comment]
Thanks for answering again! 
Fixing just 1. will do plenty! 
If on number 2 switching is the official way then so be it. Obviously I'm not as much involved into those processes as you so I trust your judgement on this.

**Comment by mvysny** [comment]
Thanks! Just a quick question: I am adding the export format front=kanji, back=english. Would you also like additional format of front=english, back=kanji ?

**Comment by derpda** [comment]
Awesome! I think one format is fine, let's not overcrowd the setting menu. Should it not fit, I can simply adjust my Anki cards field order, no big deal. Looking forward to the feature! 
I'm probably gonna get the Aedict reader soon, I'm using Rikaisama on my PC already and the reader would be the equivalent to that for my phone. Maybe I'll have some feedback on it for you shortly!

**Comment by mvysny** [comment]
Sure, no problem ;) Please try it out and let me know what you think. I have added the kanji/english Share format, please activate it in Settings / Export / Export Flashcard front/back. Fixed in Aedict 3.39.5
