### ISSUE TITLE
Button to directly add to notepad

### ISSUE THREAD

**Issue by derpda** [mvysny/aedict#609]
Hi mvysny,

first of all, thanks for making and maintaining aedict.
I'm really pleased with the custom csv export option! One thing however:

When I look up a word, I would really like a quick option to add it to a notepad. 
I imagine a lot of users use a single notepad to store all their vocab and then export it to Anki.
If possible, a setting to make the "Add to notepad" button add the word to the last used notepad, as opposed to opening a selection menu for notepads, would be great.

Another option would be a swipe, which might actually be even more practical.
What I mean is the following:
In the list of search results, hold and swipe a word right/left to add it to the last used notepad. 
Fastest way and very, very practical.
This feature is implemented in Imiwa? for iOS. When I read a book in Japanese, I just want to quickly know the meaning of a word and add it to a list for future study as fast as anyhow possible. If that takes too long, reading becomes a pain.

I checked if a similar issue was posted already but didn't find one, hope I didn't overlook it!

Best regards,

Peter

**Comment by mvysny** [comment]
Hi Peter, thanks for letting me know and thanks for reporting your issue here. Swipe actually is implemented and should work everywhere except the Notepad screen and the Entry Detail screen (because those screens have tabs and the swipe gesture switches between the tabs in those screens). 

You can try the Swipe gesture for exaimple in the Main Screen with the search bar. Just try to search for a word (and make sure that the quick search is enabled). Then, simply swipe the word to the left (swipe-to-right does nothing, please make sure you swipe-to-left). Four buttons should appear: Add to Notepad, Copy To Clipboard, Tag Entry and Send To.

Another way to add any entry to the Notepad is to long-touch the entry, then click the "Add To Notepad" upper-right button. Not as fast as the Swipe-To-Left, but works everywhere.

Please let me know if this works for you.

**Comment by derpda** [comment]
Hi mvysny,
thanks for the quick answer!
Well, that kind of swipe mechanism works, kind of. 
This is no major issue, but I certainly would like for it to work with one gesture. The swipe would probably the best option for that in my opinion. What I would love to see would be a function like 
"Swipe left" => "Word added to last used notepad" 
No choices after swiping, just immediate adding to the notepad. 
I don't know if other users are interested in the feature and sadly I don't know anybody else who uses this excellent dictionary. 
My best comparison is, as mentioned, the Imiwa? dictionary for iOS, which has exactly the feature I'm describing and I have used it extensively.

I hope this helped make my point clear =)

Thanks for answering again and I'm curious to hear your opinion on this.

Peter

**Comment by mvysny** [comment]
Well, you're the first to request such a feature ;) . However, as a user of the Imiwa? dictionary (which is pretty good from what I heard), this is an important feedback. Please feel free to let me know what else you are missing from Imiwa? (and what you find better in Aedict than in Imiwa?) ;)

Back to the issue at hand. I could perhaps add a "swipe-to-right", which would activate the "Add to Notepad" functionality directly. Perhaps I could add a configuration setting where you could configure which action to trigger directly by swiping to right: Add To Notepad, Copy To Clipboard, Tag Entry, Send To. The advantage of this solution is that you can still swipe to left and choose from the menu, as it is done presently. I hope this will not be very confusing, what do you think?

**Comment by derpda** [comment]
I think that might work very well. Personally, I don't need the "swipe-to-left" function but I'm sure you have good reason to have it in there. 
Now that you say it, one thing that I would consider a good idea would be to have the keyboard open automatically when the app opens, or at least when opening it over the "Always Available" option. Just a small thing to make things smoother.

As for the comparison to Imiwa?, there are a few things I actually like better about Aedict. I like the immediate access to all the search options, although a button to hide them would be nice. For example a button of the length of the search field saying "↓↓↓ Search Options ↓↓↓" or something would be nice to make things a little more clear. 
I think it's really hard to design a simple, clear interface with a lot of functionality. But maybe that would be one step.

As for this issue, I think a "swipe-to-right" function would be very nice and would certainly solve the issue for me.

Peter

**Comment by mvysny** [comment]
Regarding the keyboard: there is setting for that :) Just make sure that the "Settings / GUI Tuning / Search / Omnisearch: Show Soft Input" is checked.

Regarding swipe-to-right: that's great. Let me implement it this way as agreed, then.

**Comment by derpda** [comment]
Thanks!
I saw that setting but didn't quite understand what it means -  I should've just tried! =D

Maybe I should make a new Issue for this, tell me if you would like me to, but for now I'll just pitch it here:
Could you make example sentences searchable? As in, add a "Example search" category (in addition to Word Search and Kanji Search)? Searching english idioms or phrases would then be possible which would be really helpful =)
I hope I'm not missing a setting or menu again, I haven't been using this dictionary for long enough as obviously. But I want you to know that I really like it and was happy to pay the small price for it. I think I'll get some of the addons in the near future =)

I'm looking forward to the "swipe-to-right" feature!

**Comment by mvysny** [comment]
The setting: yeah, the description is somewhat confusing. How about this? "When checked, the software keyboard will always be shown when the Main Search Screen with the omnisearch box is shown."

Regarding the Examples Search: it is possible: In the Main Search Screen, just click the "Advanced Search Settings" button (the upper-right icon which kinda looks like a wifi signal strength ;). A panel should be shown; in that panel, make sure that in the "Search in" radio button section the "Examples" radio button is selected.

Thank you very much again for your support. Your contribution is very important as I have no means to get the money elsewhere, like Facebook does for example...

**Comment by mvysny** [comment]
Hmm, unfortunately the Swipe library I'm using does not support both swipe-to-left and swipe-to-right on a single item... How about an alternative: there will be no swipe-to-right; instead I will add a configuration Setting where you will be able to select buttons which should appear in the swipe-to-right menu. By default all buttons will appear, but you could change that to any combination of buttons, including just a single "Add To Notepad" button. Is this acceptable?

**Comment by derpda** [comment]
Thanks for the examples search thing. I clearly should check more before I make comments here, sorry about that. Kinda embarrassing, I had actually used the feature before. No idea what I was thinking.

Anyway, about the swipe issue, the main point for me was to make it as quick as possible. Being able to adjust the number of buttons after the swipe might be a slight improvement, but if you could allow a setting to simply let swiping add the word to a notepad without any further tapping, that would be perfect. This might be too much to ask and don't hesitate to tell me if it is. 
I would really like to hear the opinion of other users on this.

Thanks for responding so much! Quote from a movie (forgot the name) "Not perfection, improvement!". I see things moving, I'm happy =)

**Comment by mvysny** [comment]
Hm, if you check just a single button, then that button can actually be auto-activated on swipe - I have no problem with that. Let me check if this is possible with the Swipe library...

**Comment by mvysny** [comment]
BTW thank you for entering a public bug report instead of writing privately to me. This way, the information can be Googled by others as well... thanks ;)

**Comment by mvysny** [comment]
Implemented in Aedict 3.39.5 - please head to Settings / GUI Tuning / Other / Quick Entry Swipe Actions and make sure that only the "Add To Notepad" is checked.
