### ISSUE TITLE
Reader: only shows a single kanji when iconified

### ISSUE THREAD

**Issue by epyon1873** [mvysny/aedict#628]
aedict reader after iconfiy , only show one kanji  ( LG G3   / Androd 6.0 )
Also, the icon show the Furigana of kanji ?

![capture _2016-02-26-10-18-37](https://cloud.githubusercontent.com/assets/17487695/13342305/355a758e-dc7b-11e5-9ee2-07ef749b4690.png)

**Comment by mvysny** [comment]
This is actually intended and has been requested by one user. The old behavior was to show four smaller kanjis, or two kanjis followed by a short translation. Unfortunately, it is not possible to cram more info into such small window ;)
Please let me know if the "two kanji + short translation" solution is acceptable for you - if yes, I will add a setting which you may use to activate this mode.

**Comment by epyon1873** [comment]
It is very grateful to know that can have this setting

Most of time i know the kanji but don't how to read it (furigana).

If the setting have the choice
1. two kanji + short translation
2. two kanji + furigana
2016年2月26日 16:00 於 "Martin Vysny" <notifications@github.com> 寫道：

**Comment by mvysny** [comment]
Added a setting with three values:
1. Single Large Kanji (the current and the default behavior)
2. Kanji + Reading (furigana)
3. Kanji + Translation
Fixed in Reader 1.3.10

**Comment by epyon1873** [comment]
When will upload to play store ?
currently play store version  still 1.3.9

**Comment by mvysny** [comment]
I have a couple of other bugs to fix, so please be patient - hopefully at the end of this week the update will hit the Google Play.
