### ISSUE TITLE
Pitch not shown for all words

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#642]
For example higashi 東

**Comment by Chinchilla-white** [comment]
Another example: 出口

**Comment by Chinchilla-white** [comment]
Wrong :入り口

**Comment by mvysny** [comment]
Thank you for letting me know. Which reading is wrong for 入り口?

**Comment by mvysny** [comment]
Fixed, please update JMDict.

**Comment by Chinchilla-white** [comment]
What is the little circle between ぐ　and ち　？

**Comment by mvysny** [comment]
The only information about that little circle (°) I have is that it is called "nasal". Perhaps this one? https://en.wikipedia.org/wiki/Dakuten

**Comment by Chinchilla-white** [comment]
I see.  I remember now there's a column 'nasal' in the DB.  Could you add an option to hide the "nasal" sound or simply remove this "nasal" circle altogether?  This "nasal" sound is pronounced by NHK presenters as standard Tokyo accent.  But it's also considered outdated by some Japanese.  Thanks a lot!

**Comment by mvysny** [comment]
Yup, that's the one. Sure, I'll add a configuration option for that.

**Comment by mvysny** [comment]
Closing; the configuration option will be added as a fix for #644
