### ISSUE TITLE
An extra little circle shown after hiragana depicting pitch?

### ISSUE THREAD

**Issue by Chinchilla-white** [mvysny/aedict#644]
In the hiragana depicting pitch accent, it seems that a little circle appears after a hiragana with ten ten and with a high pitch (so it has a line above it).

e.g. There is also a little circle between が　and し in ひがし.

**Comment by mvysny** [comment]
That is correct. As discussed here #642 , the little circle ° depicts the 'nasal' information: perhaps this one? https://en.wikipedia.org/wiki/Dakuten. This "nasal" sound is pronounced by NHK presenters as standard Tokyo accent. But it's also considered outdated by some Japanese. I will add an option to hide the "nasal" sound - perhaps even the nasal sound should not be displayed by default.

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.11
