### ISSUE TITLE
Color tag in CSV export

### ISSUE THREAD

**Issue by kuroi-hayabusa** [mvysny/aedict#648]
Could the color tag value be included as an additional field in the CSV export format? I am thinking particularly in the tag color because it would be helpful to filter easily the result lists. But I guess the tag text would be also nice to have in a different CSV field.

**Comment by mvysny** [comment]
I *think* that the tag text can be exported to the CSV: Just use `%tag%` as described here: http://aedict.eu/export.html . Tag color is not exported yet - should I use the color name (e.g. "blue") or the HTML hex color code, e.g. `#33B5E5`?

**Comment by kuroi-hayabusa** [comment]
Excellent. I would prefer the colour name but the hex code would be also fine.

**Comment by mvysny** [comment]
I have added a new tag, `%tagcolor%`, which will either resolve to an empty string if there is no tag color attached, or it may have one of the following values: `blue`, `green`, `magenta`, `orange`, `red`.
Fixed in Aedict 3.39.11
