### ISSUE TITLE
Copy specific entry in Daijirin

### ISSUE THREAD

**Issue by sugoibachiri** [mvysny/aedict#650]
Sometimes the Daijirin shows several entries. See attached.  It would be great, if the entries could separately copied into the clipboard. At the moment it is possible to copy all entries at once. 

![2016-03-20 15 33 30](https://cloud.githubusercontent.com/assets/17965530/13905300/41d35cec-eebc-11e5-9f01-55fb88f06d1b.png)

**Comment by mvysny** [comment]
Thank you for letting me know. I'll think of something :)

**Comment by mvysny** [comment]
Let us try a simple implementation. Just long-touch the 1/2/3 area and select "Copy To Clipboard". I have also added the "Search" menu item which will search for that very term. Please let me know if this works for you. Fixed in Aedict 3.39.11
