### ISSUE TITLE
Online: remember settings of previous session

### ISSUE THREAD

**Issue by pouncingant** [mvysny/aedict#660]
When I close/reopen my browser (Firefox 45.0.1) I find that on navigating back to aedict-online I need to reset my dictionary choices and other settings.
Expected behavior would be the use of cookies to store settings.

P.S. So far as I recall, this is the first time I've submitted a bug-report on github; I apologize if I missed any crucial information/conventions.

**Comment by mvysny** [comment]
Thanks for letting me know. This is true - currently the settings are kept server-side only, and forgotten after some time if you are not registered. A workaround is simply for you to register - just registering is enough, you don't need to subscribe subscribed and registering is free of charge.

Meanwhile I'll investigate the possibility to store the settings (just the settings, obviously I can't store Notepad/SRS/other user data this way ;)

**Comment by mvysny** [comment]
After you register, you can check the "Remember me" check box in the login screen. After that, a special cookie will be stored in the browser, which will automatically log you in, which should apply all of your settings automatically.

Closing as fixed, please feel free to reopen if this is not working as you expect.
