### ISSUE TITLE
Number of strokes in Kanji Search window

### ISSUE THREAD

**Issue by kuroi-hayabusa** [mvysny/aedict#662]
At the moment the number of strokes is present in the "kanji parts" window, in the kanji search menu. But I find useful to have it also in the result window, when searching for a particular kanji. 
This is done, for example, in jisho.org (radical). 
Could this be implemented in aedict?

**Comment by mvysny** [comment]
Hi, I apologize for such a late reply. Sure, I'll implement this.

**Comment by mvysny** [comment]
Implemented in Aedict 3.39.17

**Comment by mvysny** [comment]
Please review if this is what you wished for:
![device-2016-04-22-102913](https://cloud.githubusercontent.com/assets/254091/14736081/17442074-0875-11e6-8dbd-5188c917d9f6.png)

**Comment by kuroi-hayabusa** [comment]
Hi Martin, this is great. Thank you!
