### ISSUE TITLE
Entry detail line break duplicates characters

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#666]
Hi, as seen in the attached screenshots, landscape mode looks fine, but in portrait mode, the secondary pronunciation せろんちょうさ seems to have the ちょ appearing twice (once on each line). Actually, I'm not sure the line breaks are needed at all on my screen, especially on the very last reading, where さ is on its own line.
![screenshot_2016-05-02-17-08-05](https://cloud.githubusercontent.com/assets/254091/15039754/9f109b38-12af-11e6-98fb-b91d59f592ed.png)

**Comment by mvysny** [comment]
Hi Mike,

 thank you for the screenshot, I can see the issue. However, this may 
be hard to fix - I am only using standard Android formatting patterns
in 
a standard Android text component. Therefore, the bug is most probably 
present in the Android text component, and there is not much I can do


  Yet, please try to disable the Settings / GUI Tuning / Dictionary 
Entry Screen / Show Pitch Accent (just set it to "None:") and please
let 
me know if this helped.

**Comment by mvysny** [comment]
Android 4.0.4 on Samsung Galaxy S2, model SPH-D710.

**Comment by mvysny** [comment]
Setting "Show Pitch Accent" to "None" fixes the repeated ちょ

**Comment by mvysny** [comment]
Hmm, apparently the "overline span" which
indicates the high pitch is the cause of this problem on your phone. I
can not completely fix this issue as I cannot reproduce it on my phone.
However, there are possible workarounds:

1. simply not showing overline in your phone - only the downstep
characters (the down arrow) will be shown.
2. not showing pitch information at all
3. by showing the middle-pitch not as "overline", but as
"strikethrough", which should behave correctly but will cause the kana
to be not as readable.

Please let me know which solution would be acceptable for you.

**Comment by mvysny** [comment]
Mike: Oh, that's too bad about the overline; I like the overline. But if I had to choose among those three options, I'd choose number 1.

**Comment by mvysny** [comment]
I'll fix this as follows: I will keep the overline enabled by default, but I will add a new configuration option to Settings / GUI Tuning / Dictionary Entry Screen / Pitch Accent: 
Show Mid Pitch: "Mark Mid Pitch characters with" 1. Overline 2. Strike-through 3. Do not mark

**Comment by mvysny** [comment]
Added additional setting: Mark with Red Color. Fixed in Aedict 3.39.18

**Comment by mikemorr** [comment]
The red color seems not to work on my phone (Galaxy S2, Android 4.0.4). I tested it with Holo Light and Holo Dark themes.

**Comment by mvysny** [comment]
Hmm, this is weird. The Does the "Strike-through" option work correctly?

**Comment by mikemorr** [comment]
Yes, the strike-through works :)

**Comment by mikemorr** [comment]
Interestingly, when I set it to Overline, the overlined kana are white (vs. gray for the low-pitched kana). But when I set it to RedColor, the kana are all gray.

**Comment by mvysny** [comment]
Hmm, this is crazy - I can see the Red text on my phone no problem. Please make sure that you have Aedict 3.39.19 installed, and please try the Red Text setting again.
This Android fragmentation is really horrible :(

**Comment by mikemorr** [comment]
Yes, unfortunately the red text isn't appearing for me in 3.39.19. Video demo: https://youtu.be/s8whnqlu5cU

**Comment by mikemorr** [comment]
I'm happy to try any test APKs, if you'd like.

**Comment by mvysny** [comment]
I probably discovered the cause of this issue. The problem is that I tell the text to be grey, and at the same time I tell it to be red. While HTML can handle it, it seems that some Android can't. I'll devise a workaround.

**Comment by mvysny** [comment]
Fixed span-related issues (I have been trying to reuse span objects, and Android hates that). Should be fixed in Aedict 3.39.20.
