### ISSUE TITLE
Search threads badly lag UI thread

### ISSUE THREAD

**Issue by kcroker** [mvysny/aedict#671]
An old bug has returned: when trying to draw Kanji on the Nexus 5, it is impossible because the UI thread lags so badly.  The search using English or Kana in dictionary also lags very badly.  

This is the most essential aspect of the application, please fix soon?

**Comment by mvysny** [comment]
I have just uploaded an upgrade which should definitely help with the Kanjipad. However, I am not aware of any lag in the regular English search. Please try to upgrade to Aedict 3.39.18 (you will have to wait though until it gets distributed over Google Play) and please let me know whether the problem still persists.

**Comment by mvysny** [comment]
Please upgrade to Aedict 3.39.19, a major bug has been fixed.

**Comment by mvysny** [comment]
Kanjipad-related slowness has been fixed in #669 which should also fix the Reading/Parts search. Closing as fixed, please reopen if the problem persists.
