### ISSUE TITLE
Minor cosmetic: Gray wrench icon vs. white icons

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#672]
In the menus, the wrench or spanner icon appears grey, whereas the other icons are white. Screenshots attached.
![screenshot_2016-05-11-14-48-42](https://cloud.githubusercontent.com/assets/2184268/15192569/c8a84b62-1787-11e6-9620-75e3724bf4b5.png)
![screenshot_2016-05-11-14-49-00](https://cloud.githubusercontent.com/assets/2184268/15192572/d0a3bfea-1787-11e6-9249-d88fee7e35ee.png)

**Comment by mvysny** [comment]
Yeah, I am using an ancient Android icon accidentally ;) Fixing now, thanks.

**Comment by mvysny** [comment]
Fixed in 3.39.20
