### ISSUE TITLE
Copy all feature of vocab doesnt copy somethings.

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#673]
I noticed when using Aedict on my android tablet that the copy all feature doesnt copy all details on some words.

For example selecting copy all on 何れ, gets the following copied to clipboard:

何れ [どれ]: which (of three or more), whichever, any, well, now, let me see

But the actual data displayed on screen is:
何れ [どれ]: which (of three or more),whichever, any (with も after a -て form verb), well, now, let me see

The entry is a Jmdict entry.  That extra information can be useful so would be useful to copy.  I know that I can press and hold on individual entries to get all the info for anyone of the particular listed entries but this is slow.

It would also be useful to have the option to copy the green word parts of speech meanings listed with a lot of entries, typing these manually is slow and error prone.

**Comment by mvysny** [comment]
Thanks for letting me know. I will add a fourth menu item, "Everything including Inf and greenish Dict Codes" which will include everything.

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.21
