### ISSUE TITLE
Conversion of ん followed by vowel

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#675]
In 3.39.20, doing an exact search for へんあい also searches for へない, even though the user entered kana rather than romaji.

**Comment by mvysny** [comment]
Currently the deinflection engine performs the deinflection on a romaji string, which will basically convert へんあい to henai and will deinflect it to heru. This is not easy to fix...

**Comment by mvysny** [comment]
Yet, I have tried to search for exact term of へんあい. While it will find the "heru" words, it will not find へない. I have created a separated issue for this: #677

**Comment by mvysny** [comment]
Marking as closed (it doesn't find へない ;). Now moving to fix #677
