### ISSUE TITLE
Example sentence for ru/ichidan verbs on inflection tab seems wrong.

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#678]
I noticed  on my android tablet  that the example sentence for one of the ichidan verb inflections seems to be incorrectly entered.  For example typing 走る into aedict and going to the inflections tab the 
走ります inflections example sentence:

Jえrry は すぐ へや から でます。
Jerry will come out of the room soon.

Should Jえrry be ジェリ or ジェリー

![screenshot_2016-05-26-20-28-24](https://cloud.githubusercontent.com/assets/19387982/15587900/483a40ae-2383-11e6-8677-d3574deafccb.png)

**Comment by mvysny** [comment]
Thanks for letting me know. I think that there is some autoconversion from romaji to kana going on, which obviously fails on the word "Jerry". Yet, it is next to impossible to implement a generic english->katakana pronounciation-based conversion, so I will probably fix this some other way ;)

**Comment by mvysny** [comment]
Fixed romanization engine, which now handles jeri->ジェリ correctly; also fixed the example sentence. Fixed in Aedict 3.39.21
