### ISSUE TITLE
Dictionary auto-update

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#679]
The notification on launch is useful, but no notification and updated dictionaries would be even better :)

**Comment by mvysny** [comment]
Instead of a "there are dictionary updates" notification, would you instead like the Dictionary Manager to pop up automatically and start downloading? I'm not sure this is a good idea, especially when your internet connection is a limited data plan connection...

**Comment by yacoob** [comment]
Given that constrain, you can make a toggle "automatically download updates", off by default. Some apps also add "auto download only on wifi" - in which case people start complaining that the download happened when they've connected their phone to a metered wimax hotspot :D Android itself allows users to mark a saved wifi network as "metered", but I don't really know how many people actually do that.

**Comment by mvysny** [comment]
I didn't knew that either :) Thanks for the tip.

Okay, for starters, let's just add the "automatically download updates" setting.

**Comment by mvysny** [comment]
Implemented in Aedict 3.39.21
