### ISSUE TITLE
Possible mismatch between Kanji font and Stroke order diagram.

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#682]
I noticed the kanji 辶 only has one dot displayed in the font glyph but it shows two dots in the SOD.  See attached for image.  I am not sure if this is a local font issue on my android tablet or an actual issue, so I am posting just incase.

![screenshot_2016-06-03-09-18-00](https://cloud.githubusercontent.com/assets/19387982/15773278/fcedb702-296d-11e6-9678-c9f446473205.png)

**Comment by mvysny** [comment]
This particular kanji is often source of great confusion, even for me ;) . On my computer the kanji above shows with two dots when browsing this page; on my phone that very kanji shows with a single dot only. Quoting https://en.wiktionary.org/wiki/%E8%BE%B6 

> When applied to a character, it may become either ⻌ or ⻍ or ⻎. They also depend on computer fonts.

Therefore, this pesky character when used as Unicode U+8FB6 may be rendered in three different ways. There are three additional Unicode characters for this particular kanji; the three variants rendered properly (⻌ or ⻍ or ⻎) are U+2ECC, U+2ECD and U+2ECE, respectively. Yet, it seems that various data files reference to this character differently:

- KanjiVG only references U+8FB6 (and renders it with two dots) and U+2ECC (and renders it with one dot);
- KanjiDic only references U+8FB6 - it does not provide any data for U+2ECC, U+2ECD nor U+2ECE

So it is unclear for me what should I do... It seems that this issue can only be solved by a Unicode/Japanese master :)

**Comment by terrywallwork** [comment]
Hi mvysny,

Dont worry about it just wanted to make sure you knew about it. :)

Sorry for the noise.

**Comment by mvysny** [comment]
No problem ;) I am not able to fix this on my own, unfortunately, closing. Please reopen if a viable solution is found.
