### ISSUE TITLE
Clicking on example sentences for inflections gives webpage 404 error

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#685]
On my android tablet if I go to the inflections tab for a verb and display the example inflections and click on one  the webpage that I am sent to is gone 404.

See attached images.
![screenshot_2016-06-06-13-14-21](https://cloud.githubusercontent.com/assets/19387982/15821715/81847c62-2be9-11e6-8293-2507be4edf42.png)
![screenshot_2016-06-06-13-14-32](https://cloud.githubusercontent.com/assets/19387982/15821727/8d9bd676-2be9-11e6-8a11-43d697a7b4d8.png)

Would be nice to have this lead to a useful page.

**Comment by mvysny** [comment]
It seems that Tim has restructuralized his page: the new page is located here: http://ww8.tiki.ne.jp/~tmath/language/verbs.htm but the lesson numbers are off. I am not sure whether I should publish a copy of the old site, or modify Aedict to use the new site instead...

**Comment by terrywallwork** [comment]
I would go with updating to the new site (assuming its not a massive logistical issue)

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.22
