### ISSUE TITLE
Future updates for Aedict-apps on Amazon App-Shop?

### ISSUE THREAD

**Issue by nabemono** [mvysny/aedict#688]
Hi, my android device only supports the Amazon App-Shop.

I want to buy 
Aedict3 Japanese Dictionary (the paid version, not the Amazon Underground Version)
+ Aedict3 KanjiPad Extension
+ Aedict KanjiDraw Practice

Sadly unlike your up to date apps on Google Play the Amazon apps didn't get updates since 09/2015.
Will updates be provided for these apps in the future? Or is there another way to buy the up to date versions of your apps?

Have a nice weekend!

**Comment by mvysny** [comment]
Thanks, and I apologize for not updating those apps. It takes a bit more time on Amazon, and there is a review process, so I tend to first stabilize the app on Google Play, then reIease it on Amazon. I think that the app is quite stable now so I will release updated versions right away.

**Comment by mvysny** [comment]
Okay, KanjipadExt 1.6 and Aedict 3.39.22 are now in Amazon Under Review, so hopefully they should be out any time soon.

**Comment by nabemono** [comment]
Hi, can you please refresh the versions on amazon again?
Thanks a lot!

**Comment by mvysny** [comment]
Updated, sorry about the delay. Yet, income from Amazon is peanuts (like 10 eur monthly) so it's hard to keep the motivation to update frequently.

**Comment by nabemono** [comment]
Thank you very much! No need to feel sorry.

Perhaps it is easier, if I change to the Google Play Versions someday in the future. Is there a possibility to get an discount?

**Comment by mvysny** [comment]
Sure, nowadays Google Plus supports some kind of discount codes / promo campaigns, so I can create one-time code or something similar. Say, with a 50% discount?

**Comment by nabemono** [comment]
I am sorry for the late reply. Unfortunately I had same serious matter to take care of.
Thank you for your great offer! If I could get 58% instead of 50% discount I could use remaining balance on Googe Play to re-buy the Apps. Would this be possible?
Have a nice weekend.
