### ISSUE TITLE
Suggested improvements to study module

### ISSUE THREAD

**Issue by sanada1615** [mvysny/aedict#690]
At present, the study module is only listed as "JLPT Quiz"--implying we can only study for the JLPT, and not the word lists that we make ourselves. In fact, there seems to be no way to separate study for my vocabulary list, and study for the JLPT. On top of that, the study system is only setup for kanji review (and poorly at that), so it is not at all useful for studying words, phrases, and other aspects of the language. I keep faithfully making vocabulary lists, but I have no way to effectively study them. I tried an Anki export, but don't have the time to figure out how to take the Aedict fields and populate Anki cards with them in an effective way (plus, the Aedict output doesn't include example sentences).

It would also be good to have example sentences appear when you are dealing with a vocabulary problem, or even example sentence problems with fill-in the blank options for study practice (with English translation (no blank) so it's not too hard/impossible).

Finally, there's currently no way to pause a quiz, which means there is no way to record partial progress. It's not even clear that a completed quiz is recorded, since the only options for answering a question are Yes/No. You could try using the SRS point system common to other SRSs (Anki, Pleco's onboard SRS system). But at a minimum, progress, even partial-progress, should be saved.

**Comment by mvysny** [comment]
Regarding the quiz pausing: the SRS point system is actually supported - just head to Settings / Quiz Settings and enable "Enable SRS/Leitner" setting. The description is a bit misleading - Aedict will in fact remember SRS numbers not only for kanjis, but also for words and example sentences as well.

You can study your own vocabulary list as follows:
1. create a Notepad category and fill the vocabulary words there.
2. Touch the category name tab to select the category.
3. Now, touch the category name tab for a second time. A popup will appear (I agree that this is actually a hidden functionality and I definitely need to improve this).
4. Touch "Quiz from this category". A quiz will start, which will quiz you the words/kanjis/example sentences from this particular category. If SRS is enabled, the quiz entry list is prioritized and sorted according to the SRS data.

Please let me know your thoughts on this.

**Comment by sanada1615** [comment]
Thank you for responding so quickly!

I've checked out this feature--yeah, I had no idea that clicking on the
category would make a menu appear.

So, I think that perhaps when i made my vocabulary list, I unknowingly
added JLPT 2 kanji to the list, and there is no way to remove them. They
are at the top of the list, and since there is like 1000 of them, they are
all I see.

Another suggestion--adding words to a study list is such an important
thing, but we must use the drop down menu to access add to notepad. Would
it be possible to add a single button next to the word that does this on
the definition page?

I would say that the overall GUI and format for studying is primarily
geared for kanji still, with the massive drawing space. I don't see any
sample sentences appearing for vocabulary--maybe you mean that I can add
whole sentences as study items? I see no way to do that, and I would still
hope to see example sentences worked into the quiz together with the
vocabulary. I find a major flaw in Anki is that lack of example sentences
in the JLPT vocabulary sets (you might include those too, rather than just
kanji?).

I would also add that typing by hand on and kun readings is too slow, so I
choose not to do it (and, the on-yomi section punishes you for using
hiragana, when most input keyboards make it too difficult to enter katakana
that is not a recognized word). There is also no way to be quizzed on the
English definition of a word.

Thanks, and sorry if I'm being harsh!

**Comment by mvysny** [comment]
> Thank you for responding so quickly!
>
> I've checked out this feature--yeah, I had no idea that clicking on the
> category would make a menu appear.

Yup, this UI definitely needs improvements. Created #691 for this.

> So, I think that perhaps when i made my vocabulary list, I unknowingly
> added JLPT 2 kanji to the list, and there is no way to remove them. They
> are at the top of the list, and since there is like 1000 of them, they are
> all I see.

Hmmm, where is this vocabulary list of yours stored? Is it stored in a Notepad, or somewhere else? Please, let us continue this general discussion here: https://groups.google.com/forum/#!forum/aedict-users - mailing list is better suited for a general discussion than a bug tracker; also, other users may join in and share their knowledge on how they create and use their vocabulary lists.

> Another suggestion--adding words to a study list is such an important
> thing, but we must use the drop down menu to access add to notepad. Would
> it be possible to add a single button next to the word that does this on
> the definition page?

In some screens (the main search screen for example), you can swipe the result word to the left. This will show quick actions which can be performed over this particular word, one of the action being "Add To Notepad". You can configure the quick action list in Settings / GUI Tuning / Other / Quick Entry Swipe Actions.

Some screens however do not allow you to swipe, as the swipe gesture conflicts with tab change gesture. In such screens, you can simply long-press the word, selecting it in the process. Then, simply touch the upper-right "Add to Notepad" Action Bar icon. You can simply long-click action bar icons, to reveal what they do.

> I would say that the overall GUI and format for studying is primarily
> geared for kanji still, with the massive drawing space. I don't see any
> sample sentences appearing for vocabulary--maybe you mean that I can add
> whole sentences as study items? I see no way to do that, and I would still
> hope to see example sentences worked into the quiz together with the
> vocabulary. I find a major flaw in Anki is that lack of example sentences
> in the JLPT vocabulary sets (you might include those too, rather than just
> kanji?).

You actually can add whole sentences as study items, simply for example by navigating to the word's Examples tab, long-clicking a sentence, perhaps selecting multiple sentences (or even all sentences - there is button for that, in the upper-right Action Bar), and choosing "Quiz" from the upper-right Action Bar menu.
Yup, the quiz is indeed tailored mostly for kanjis, yet you can for example use the kanji space to draw kanjis present in the word itself.
Yet, please let us continue the discussion on this topic on the Aedict Users mailing list if you will.

> I would also add that typing by hand on and kun readings is too slow, so I
> choose not to do it (and, the on-yomi section punishes you for using
> hiragana, when most input keyboards make it too difficult to enter katakana
> that is not a recognized word). There is also no way to be quizzed on the
> English definition of a word.

I'm not using JP keyboard myself, so I haven't realized this ;) of course, the on-yomi section should definitely not punish you for entering the correct reading, regardless of whether you inputted it in hiragana or katakana. If this is indeed so, can you please create a new bug report at this bug tracker for this particular bug?

> Thanks, and sorry if I'm being harsh!
No problem, thanks for letting me know and making Aedict even better ;)

**Comment by mvysny** [comment]
I'm not sure what the status of this bug is. I believe all questions have been answered properly. If not, please open a new feature requests, one for every particular issue.
