### ISSUE TITLE
[3.39.23] Commonality rating displaying wrong, no newspaper frequency

### ISSUE THREAD

**Issue by SeanHogan** [mvysny/aedict#694]
Hi, the commonality rating on kanji seems to be broken. A lot of them
say 1002 in the kanji-breakdown view for a word, and when i click on them to bring up the kanji page, it says 0 for the commonality.

Also, could you add or is there a way to see the newspaper frequency for a kanji?
On jisho.org this shows up on the kanji info page: http://jisho.org/search/%E6%97%A5%20%23kanji "1 of 2500 most used kanji in newspapers"

Phone:
LG-D851 (model number)
LG G3
Android 6.0
Kernel 3.4.0

Thanks,
Sean

**Comment by mvysny** [comment]
Hi, thanks for letting me know. Regarding the commonality rating - thank you for letting me know, this is weird, I'll investigate this.

Regarding the newspaper frequency - sure, I can add this information.

**Comment by mvysny** [comment]
Aedict 3.39.24 will now show the newspaper frequency information. Note that you will need to activate this item by pressing the (i) icon below the kanji.

**Comment by mvysny** [comment]
Fixed the issue of commonality being reset to 0 in Aedict 3.39.24
