### ISSUE TITLE
Crash on Kanji search (BlackBerry 10)

### ISSUE THREAD

**Issue by platvase** [mvysny/aedict#700]
When using the Kanji search feature the app will crash and give an "Unfortunately, Aedict has stopped". This happens specifically when the kanji icons are tapped. I ran the self check and 15 tests passed, 0 failed and 6 crashed. I have included a screen shot of which crashed.

I understand that BlackBerry is most likely not a large seller, but it would be greatly appreciated if a fix were possible as Aedict is really useful.

![img_20160919_010717](https://cloud.githubusercontent.com/assets/22289903/18625887/5d1a16e2-7e06-11e6-9504-a18788323ef4.png)
![img_20160919_010721](https://cloud.githubusercontent.com/assets/22289903/18625893/640bada8-7e06-11e6-929e-8a715d24490d.png)
![img_20160919_011508](https://cloud.githubusercontent.com/assets/22289903/18625938/a9b8636e-7e06-11e6-876a-59ec07c640fd.png)

**Comment by mvysny** [comment]
Thanks for letting me know. Yes, I sold like 5 copies of Aedict on BlackBerry :-D I think that BlackBerry version of Aedict is quite outdated. I will try to update Aedict first, and I'll let you know.

**Comment by platvase** [comment]
Thanks a lot for taking a look. Its highly appreciated.

**Comment by mvysny** [comment]
Please try out the new 3.39.26 and please report any further crashes. If Aedict will still crash, I'll reopen the bug.

**Comment by platvase** [comment]
Thank-you so much. I can confirm the fix on both a Z10 and Q10 both running 10.3.2.

**Comment by mvysny** [comment]
Thank you, that's great to hear ;) If there is anything else, just open another github issue.
