### ISSUE TITLE
Aedict deinflects to nouns

### ISSUE THREAD

**Issue by tyress** [mvysny/aedict#701]
For example, if I put in makenai or まけない,  the first result is 巻く、and there is a note on the bottom that says 
まけない-まける : I do not do something
まける-まける、まく: I'm able to do something

Seems ok, but it's also repeated for words that can't be conjugated, like nouns 幕 and 膜

**Comment by mvysny** [comment]
That is true, thank you for pointing this out. Unfortunately, the deinflection engine works without access to the dictionary. Therefore the engine does not have information whether the deinflection product actually makes sense or not ;) But, the dictionary matcher engine can take this information in account and filter out non-verb and non-adjective words created with deinflection. I'll look at that.

**Comment by Todew** [comment]
This still seems to be happening, is there any chance of progress?
Also some verbs are incorrectly deinflected; for example entering either かえって or かえて finds exactly the same verbs (as well as the noun かえる.)  From what you said it looks as if this can't be changed, is that correct?

**Comment by mvysny** [comment]
Sorry, I had no time to look at this. It's not as straightforward. I thought about just searching for verbs, but what if someone is searching actually for a noun? But I have an idea: search the original term without limitation, and union the search results with the search in verbs for deinflected term. Let me write a couple of tests and play with this.

**Comment by mvysny** [comment]
Fixed in Aedict 3.46
