### ISSUE TITLE
Dictionaries erased with every backup of phone data

### ISSUE THREAD

**Issue by sanada1615** [mvysny/aedict#702]
Using MIUI 8's (and 7's before) local backup function, which saves all app, file, and personal data to a giant backup file, consistently erases all of the dictionaries. Unfortunately, the backup doesn't save notepad data. Not sure why dictionaries get erased after backing up, and why the backup never contains the notepad data.

**Comment by mvysny** [comment]
This is really weird. The local backup should only write a single big zip file to the backup directory, nothing more. And the zip file should definitely contain the notepad data. You can verify this, by opening the zip file on your desktop computer and checking that it indeed contains the "notepad.bin" file. Have you perhaps changed the backup directory location on your phone?
You can learn the location of the dictionaries by performing the "Dictionary Health Check" as stated in FAQ: http://aedict.eu/faq.html . Then, please try to observe what happens to the directory when the backup is performed.
This is indeed really weird. It is possible that perhaps your SD-Card is malfunctioning?

**Comment by mvysny** [comment]
I do not own MIUI myself so I'm not familiar with how the backup works exactly. Maybe it only backs up files up to a certain size? The dictionaries are very large (300+ MB of size) so maybe they are ignored by MIUI backup.
Closing since there is info missing, please reopen when there is more information.
