### ISSUE TITLE
あわてて is deinflected, but あわてる doesn't appear in search results

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#709]
Hi,
When I do an Exact Japanese search on あわてて, the top of the screen shows it deinflecting to あわてる, but あわてる doesn't appear in the search results; it goes to Sentence Analysis Fallback. Perhaps this is caused by an apparent additional deinflection which I don't fully understand, from あわてる to "あわて (I am doing X.)"; maybe it's seeing あわてる as an abbreviation of "あわている"?
![screenshot_20161122-114720](https://cloud.githubusercontent.com/assets/2184268/20533034/1b837882-b0aa-11e6-9da5-55ec4e836870.png)

**Comment by mvysny** [comment]
Thanks for letting me know. Regarding the search: this is of course a bug, I will fix it.

Regarding the awateru to awate deinflection: this is the "Te form + iru" which is sometimes shortened into -teru. Please read more here: http://ww8.tiki.ne.jp/~tmath/language/verbs.htm#52

**Comment by mvysny** [comment]
Of course, I will add more verbose deinflection information to be shown in Aedict, so that it is more clear what deinflection Aedict chose.

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.27
