### ISSUE TITLE
Kanji search very slow

### ISSUE THREAD

**Issue by Keksus1** [mvysny/aedict#713]
Using a Nexus 5X and the Kanji search by drawing is very slow. I often have to wait for more than 10 seconds before it shows me a list.

**Comment by mvysny** [comment]
Thank you for letting me know. Are you using internal kanjipad, or are you using the Aedict Kanjipad? http://aedict.eu/kanjipadextension/index.html

**Comment by mvysny** [comment]
Also, would you please be interested in helping me out by capturing logs from your phone? The details are here: http://aedict.eu/faq.html Section "Aedict 3 log"

**Comment by Keksus1** [comment]
I am using the paid Aedict Kanjipad and Android 7.0

Not sure if I did everything correctly with the log. I just started logging, then used the search function and tried looking up a few Kanji with the Kanji Pad. Then saved the log.

https://mega.nz/#!nYYjkLrR!AGVUugITK-F12h9TDjYA52sxynnIjnRrz3IH8vDXabA

**Comment by mvysny** [comment]
Thank you very much, the log cat is perfect! It made me realize that the logging was not as accurate as I thought. Can you please upgrade to KanjiPad Ext 1.6.2 (released just now) and try to capture the logs again?

**Comment by Keksus1** [comment]
Ok. I upgraded. Here's the new log:

https://mega.nz/#!fJBFxKpA!eoqGiwNaZJSBO6uMbs1hPwdSgprvubMfsYPfH75y3Fk

**Comment by mvysny** [comment]
This is weird: I can clearly see that search for 10+ strokes takes 1 second (which is not ideal), but it's far from the ~10 seconds you speak of. What's even more weird, the logs from the Kanjipad extension are not present at all in the log, so I can't really see what's going on unfortunately. I have tried to artificially slow down the kanji analysis to take 1 second, but even with that I can't reproduce the ~10 second delay - I'm getting 1-2 seconds tops.

**Comment by mvysny** [comment]
Is the issue still present please?

**Comment by Keksus1** [comment]
I think it was back a while ago. But after a short test with the most current version (3.46) the problem does not exist and it works perfectly fine.

**Comment by mvysny** [comment]
Awesome to hear, thanks!
