### ISSUE TITLE
Listing methods

### ISSUE THREAD

**Issue by steel1260** [mvysny/aedict#715]
Hello
I have a category in which there are few thousands of words. Every time i want to review the words on the bottom, it always takes me 30+sec to scroll down. Could you add more listing method such as by date or by Japanese alphabet

**Comment by mvysny** [comment]
Hi, well, there is the "search" functionality, accessible from the Action Bar, located at the top-right  (the magnifier glass icon). But, of course, sorting definitely makes sense. I will implement it. I should probably sort by readings, naturally, either by romanized version or by Japanese alphabet (the hiroha uta sorting?). But what about entries with multiple readings? I will probably use the first common reading. What do you think?

**Comment by steel1260** [comment]
Romanized alphabat is the way to go, NO doubt .
I also go for first common reading

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.29
