### ISSUE TITLE
Possible Kanji/Hiragana dakuon handakuon display issue

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#718]
There is a possible display issue when displaying certain AEdict entries.  See the image attached, it seems to display both a dakuon and handakuon at the same time indicated by yellow arrow?

![aedict screenshot](https://cloud.githubusercontent.com/assets/19387982/21081544/2a531cc0-bfc1-11e6-92b3-f8222979d846.png)

**Comment by mvysny** [comment]
Hi, that's actually not the handakuon character, but instead it marks the "nasal" pronounciation character. You can configure whether to show the "nasal" character at Settings / GUI Tuning / Dictionary Entry Screen / Show Pitch Accent.
Yet, I'm unsure what that "nasal" stuff actually means. The source data for pitch accent contains it and thus I'm showing it, but I can't find any more information regarding this. Could you please look into this and let me know? Perhaps this nasal thing shouldn't even be displayed, or maybe a completely different character should be used to mark the nasal mark?

**Comment by terrywallwork** [comment]
@mvysny Ah sorry for the spam.  I had no idea that was what it was.

The nasal stuff just means that when you say the sound the tongue is further back in the mouth and near the roof of the mouth when said.  Making the sound muddy.

Example:
gi  would sound more like (gni)  ga gna  etc.

I cant give audio examples because my Japanese speech is not good enough.

Japanese stack exchange has a explanation but I cant comment on how accurate it is, sorry :)

http://japanese.stackexchange.com/questions/177/pronouncing-%E3%81%8C-as-nga

Again sorry for the false report.

**Comment by mvysny** [comment]
Oh, no problem at all! This thread may serve for future users to also discover the meaning of that weirdly-placed handakuon character.

Btw thank you for the link, this part is interesting, quoting: "One thing I found very interesting was that the two pronunciations are (very) occasionally distinguished using a handakuten. i.e. nga = か゜. See for example this article." https://en.wikipedia.org/wiki/Dakuten

So the handakuten character actually *is* used to mark the nasal pronunciation. So I'm relieved that Aedict actually uses the correct character ;) Therefore, there is no need to change that, thus closing this bug. Please feel free to reopen if some other character should be used instead.
