### ISSUE TITLE
search box not wysiwyg bug/feature request

### ISSUE THREAD

**Issue by bengaskin** [mvysny/aedict#720]
Hi there,

Something I find counter-intuitive in aedict is that the top blue bar doesn't have consistent behaviour.　What it shows to the user as result-state is not the same state as the starting point the user gets when using the bar to search (again).

eg. if I search for たいしょう, I get results for 対照 among others. I can then click into a search result, and the top bar shows 対照 (further, if I keep navigating from words to kanji to words I could end up with the top bar showing something quite different from my original search request).

What I would expect, is that if I enter the search bar, I could delete a character to bring me back to 対. Or add on a character to get something like 対照液 (taishoueki).

There is a long round-about workaround which involves using the copy-to-clipboard menu option, choosing the top, ie. kanji-only, option, pasting back into the search box and then searching again.

My recommendation would be that at any time the result showing in the top bar should be the starting text for the new search.  This keeps full wysiwyg functionality.

As nice-to-haves (but not needed) the previous functionality could still be available by having one level "back" (pressing the back button on your phone) take you back to the search result before you clicked into the item.

There are other ways to get the same nice-to-have-but-not-needed functionality too, example having a mini drop-down search history from the search box when in edit mode or a search history menu item.

Fundamentally, I don't mind retyping my search, but as my Japanese gets higher and I use more and more multi-kanji compounds, it becomes more and more likely that I'll want to refine my search to have more or less kanjis or quickly copy directly out of the search box.

Can you please have a look into this?

P.S. A note about my example, I realise 対照液 isn't a separate dictionary entry in aedict, but I didn't know this when I first searched for it.  And even still, it's nice to search for it like this because then I can see both 対照 and 液 in the results together.

**Comment by mvysny** [comment]
Currently the quick search is by pre-filled with the last search term, both in the quick search and in the main search screen "omnisearch". This behavior can be tuned in Settings / GUI Tuning / Search / Pre-fill Omnisearch.

However, your suggestion makes sense. I'll simply copy anything that's in the title to the search bar, and we'll see.
The search history is unfortunately not possible, since Android does not allow that.

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.29, please let me know whether it works to your expectations.

**Comment by bengaskin** [comment]
Thank you very much, yes works as expected.

Regards

Ben

**Comment by mvysny** [comment]
Awesome, glad to help :)
