### ISSUE TITLE
Crash on Anki Export while in dictionary

### ISSUE THREAD

**Issue by cboe** [mvysny/aedict#731]
Hello,

Aedict v3.39.29 seems to crash when trying to do an export to Anki (CSV or direct) while having a selection inside a dictionary. It seems to work fine with normal search results selected, but inside a created dictionary in the notepad the app crashes after a few seconds instead of showing the export screen. I've attached a log.

[log.txt](https://github.com/mvysny/aedict/files/787074/log.txt)

**Comment by cboe** [comment]
I'm now attaching a proper log :)

[log.txt](https://github.com/mvysny/aedict/files/787076/log.txt)

**Comment by mvysny** [comment]
Hey, thanks! Sorry about the crash. Accidentally the crash was already reported by Crashlytics, so I already fixed it. I'll push a fixed version of Aedict today soon.

**Comment by mvysny** [comment]
Fixed in 3.39.30
