### ISSUE TITLE
Link to Tatoeba for しか pulls in examples for Chicago

### ISSUE THREAD

**Issue by pt-dev** [mvysny/aedict#742]
Search for しか and pick the 'only, nothing but' meaning.
Choose 'Examples'. All the Tatoeba sentences are for Chicago.

I'm aware this could be a Tatoeba bug as well. 😊

**Comment by mvysny** [comment]
Thanks for letting me know Yeah, Aedict probably tries to be too smart and will also search for hiragana shika, finding a lot about Chicago ;) While this is handy for JMDict, it apparently isn't as handy for example sentences. I'll remove this feature for Example Sentence search. 

What puzzles me is that, apparently this feature is not used from the main screen search - if you search for しか in the main screen in examples, you won't get any Chicago results.

**Comment by mvysny** [comment]
Okay, searching for しか in the main screen with searching in Examples will also return countless Chicago-related results :-) Clearly, searching for "shika" should return Chicago-sentences since it must search for both hiragana and katakana. Yet, searching for しか shouldn't match katakana...

**Comment by mvysny** [comment]
Oh, actually perhaps it should: apparently kirei can be written both in hiragana and in katakana, e.g. `とてもキレイでした。 It was very beautiful.`  or `なんてキレイな写真なんでしょう。 What a beautiful picture!`
Yet I am still inclined to fix this since those Chicago sentences are virtually useless as examples for しか.

**Comment by mvysny** [comment]
![device-2017-04-02-202418](https://cloud.githubusercontent.com/assets/254091/24589410/5f5f7d86-17e2-11e7-850e-7a707795c1f7.png)
Fixed in Aedict 3.39.34
