### ISSUE TITLE
Can't delete entries any more

### ISSUE THREAD

**Issue by jeanchalard** [mvysny/aedict#746]
V3.39.33
Repro steps : from the top page, with many entries in 'recently viewed'. Select a few entries to be deleted and open the overflow menu at the top right. Then tap 'delete selected'.
Expected : the entries are deleted.
Actual : nothing is deleted.
Notes : when opening the menu it looks like the entries get deselected, which explains why the command does nothing. There is also a visible flicker of the list whenever the overflow menu opens, which might be related.

**Comment by mvysny** [comment]
Thanks for letting me know, and sorry about that :) Fixed in 3.39.34
