### ISSUE TITLE
Aedict Reader popup text input search missing input box

### ISSUE THREAD

**Issue by bgx90** [mvysny/aedict#751]
After tapping the magnifying glass icon in Aedict Reader's popup window, Reader switches to text input search mode, but there is no text input box. This makes searching using input text in the popup impossible. 

Aedict Reader version: 1.3.14
Aedict version: 3.39.35
Device: Nexus 5
Android version: 6.0.1

**Comment by mvysny** [comment]
Yes, I just noticed that behavior, I apologize. I will investigate.

**Comment by mvysny** [comment]
This is what I get for following Android recommendations and extending AppCompatEditText instead of EditText. Reverted back to EditText, now the bloody thing works again :)
Fixed in Reader 1.3.15
