### ISSUE TITLE
する verbs do not have inflection pane

### ISSUE THREAD

**Issue by dovej** [mvysny/aedict#757]
する verbs are currently marked as a special noun class but do not have an inflections pane.

**Comment by mvysny** [comment]
Thanks for letting me know, I'll look at this.

**Comment by mvysny** [comment]
JMDict's conjugation for する: http://nihongo.monash.edu/cgi-bin/wwwjdic?1W%B0%D9%A4%EB_vs-i

**Comment by mvysny** [comment]
Fixed in Aedict 3.42. If you now browse for 為る then you should hopefully see a correct inflection table. Please review and let me know of any issues.
