### ISSUE TITLE
S Finder support

### ISSUE THREAD

**Issue by silverpierce** [mvysny/aedict#759]
The old Aedict dictionary is able to be searched with Samsung's Finder app but for Aedict 3, even though search is turned on for the Finder app doesn't yield any results from it.

**Comment by mvysny** [comment]
Thanks for letting me know. I do not own a Samsung phone myself, so I need to ask this. I think that at some point in time, there was an API which an app could offer, to make itself searchable, but I feel like it was deprecated or something like that. I'll ask in the forums.

**Comment by mvysny** [comment]
https://stackoverflow.com/questions/43980013/integrate-with-samsung-finder

**Comment by mvysny** [comment]
Unfortunately there was no help granted, and no reply so far. Closing as won't fix; please reopen if there's any new information about how to integrate with the Finder.
