### ISSUE TITLE
Adding a meaning/example sentence in “export to ankidroid“ results in adding it twice

### ISSUE THREAD

**Issue by kymatx** [mvysny/aedict#763]
I think this bug occured after the latest update.
![screenshot_2017-05-25-18-12-31](https://cloud.githubusercontent.com/assets/17027528/26459533/14fa81e6-4177-11e7-88d4-196f68934187.png)

**Comment by mvysny** [comment]
Thanks! The Export dialog has been rewritten in Kotlin, and as a part of this rewrite this bug should now be fixed. Fixed in 3.39.39
