### ISSUE TITLE
OmniSearch bug

### ISSUE THREAD

**Issue by eji30** [mvysny/aedict#767]
I really like it that I can make the search to be at the bottom because it's a better setup when I'm using my phone one-handedly. But, when I try to add something to the notepad, the notification '1 entries added to notepad' blocks the search bar entirely - it's a bug. I think the correct scenario should be: if omnisearch is at the bottom, the notification should also be reversed - it should be on top, so I wouldn't have to wait for it to be gone to type something again. Yoroshiku onegaishimasu.

Aedict version: 3.39.36

**Comment by mvysny** [comment]
Hey, good catch, thanks!

**Comment by mvysny** [comment]
Snackbar officially doesn't support the top mode so I implemented this via a small hack. Fixed in 3.39.37

**Comment by mvysny** [comment]
Probably those should show in bottom mode only in the MainActivity ;)

**Comment by mvysny** [comment]
Fixed.
