### ISSUE TITLE
Incorrect furigana when analyzing 落ち着かせ

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#769]
In the attached screenshot, the kanji 着 has the furigana ちゃく, but it should have つ, as in 落ち着く.
![screenshot_20170615-213438 2](https://user-images.githubusercontent.com/254091/27518560-57b7ad56-59eb-11e7-8d05-25a351a64ea5.png)

**Comment by mvysny** [comment]
Unfortunately Aedict can't deconjugate 落ち着かせ, and thus splits it into 落ち, 着, かせ, and then discovers the JMDict word 着:ちゃく.
So, can you please provide more information about this particular conjugation, ku->かせ ?

**Comment by mikemorr** [comment]
I think it is the continuative (ren'youkei) form of the causative ochitsukaseru.

**Comment by mvysny** [comment]
I agree, you're right. Unfortunately ochitsukaseru is not in JMDict, and Aedict is not wise enough to conjugate ochitsuku to ochitsukaseru and then to ochitsukase. But maybe I can bent it just a little...

**Comment by mvysny** [comment]
Fixed in 3.39.39
