### ISSUE TITLE
pitch accent in anki export

### ISSUE THREAD

**Issue by laxa88** [mvysny/aedict#770]
would be nice if possible to customize the csv export or have some default export for the furigana to also include pitch accents.

**Comment by mvysny** [comment]
Hmm, it's not clear how to represent overlined up-pitch accents. Maybe with ꜛ , down-pitch with ꜜ, like ꜛkaꜜkio 牡蠣を

**Comment by laxa88** [comment]
the current method in aedict is actually fine with me -- red for up-pitch, and down-arrow (ꜜ) for down-pitches. the up-arrow can be difficult to discern if the words are small on the screen (i use ankidroid a lot)

**Comment by mvysny** [comment]
Unfortunately I don't think I can export values with custom formatting... or maybe I can export values with html formatting in them? Let me check.

**Comment by laxa88** [comment]
i don't know the inner working of how aedict exports the anki cards, but i did notice some javascript when customizing the deck. Perhaps you could retain the up-pitch and down-pitch symbols, and use javascript to format them accordingly.

**Comment by mvysny** [comment]
Implemented in 3.39.39, export to Anki will use html formatting and will mark the pitch red. Note that by default the furigana field is shown, which does NOT contain the pitch colors. Only the "reading" field contains the pitch colors. So, in order to see the pitch color, you will have to edit the card model in AnkiDroid.

**Comment by mvysny** [comment]
Since this fix clashes with #777 it will be reverted. You can still activate the html formatting by checking `Settings / Export / Export Pitch as HTML`
