### ISSUE TITLE
Aedict export (ability to edit the expression field freely)

### ISSUE THREAD

**Issue by aedicted** [mvysny/aedict#771]
Hello everyone,

whenever looking up something in Aedict and selecting export, while one can change the meaning and example fields in that menu, the original looked-up term in Japanese can only be selected from a few suggestions.

However, in certain cases, it might be desired to edit that, especially if the word consists of a combination of Kanji and Hiragana because then by default, the Furigana placement is completely off center and just wrong. So between any transition, a space is required between the characters in order to fix that. Furthermore, with words consisting of many Kanji like "修辞疑問" with the reading "しゅうじぎもん", I'd personally prefer to split the furigana field into "修[しゅう]辞[じ]疑[き]問[もん]" because then, each reading is really centered above each single Kanji giving you an idea what which Kanji stands for instead of the whole word.

In either case, it would be more comfortable to be able to edit the expression field right within the export dialog instead of being stuck to the selection:

![screenshot_20170517-093531](https://user-images.githubusercontent.com/25736656/27570873-62c1b05a-5b3c-11e7-8ed2-0872468aad96.png)

![screenshot_20170517-093755](https://user-images.githubusercontent.com/25736656/27570887-761d9696-5b3c-11e7-8286-54649913ada7.png)

Would be great if that feature could be implemented.

Cheers!

**Comment by mvysny** [comment]
Thank you for letting me know. Now I know why there was a selection bar in the first place: AnkiDroid's furigana representation is ambiguous, in a sense that it's not easily visible to how many characters the reading applies. And thus if you free-style edit the text, the original knowledge of kanji+reading is lost.

No worries though - I have still switched to a free-edit mode, and I have implemented an algorithm which guesses the kanji+reading back from the free-style text. If the algorithm produces weird results, just let me know.

Implemented in Aedict 3.39.39
