### ISSUE TITLE
Add option to update ankidroid export entry

### ISSUE THREAD

**Issue by laxa88** [mvysny/aedict#772]
Thank you so much for the recent .39.39 update with adding the pitch-accent, it works great!

I already have about 4000 entries in my ankidroid deck, and discovered that re-adding existing entries that did not have pitch accents do not actually update them. I could use the "allow duplicate" setting to re-export an entry, but i would rather just update existing entries.

Perhaps also add "update/overwrite" options in the setting, for every editable value in the entry (besides the unique entry), e.g.:

- toggle update custom notes
- toggle update meaning
- toggle update example sentences
- toggle update tags

**Comment by mvysny** [comment]
I'm not sure that is possible: AnkiDroid export only allows to add items - it does not allow to delete them nor overwrite them. The 'duplicate' setting actually filters the list to be added by checking for present items in AnkiDroid; when Aedict finds out that a particular item is already present in AnkiDroid, it simply does not add it.

**Comment by laxa88** [comment]
oh, that's quite unfortunate. thanks for the heads up!

**Comment by mvysny** [comment]
No worries; if you like, we can ask Tim of AnkiDroid to add this feature into the AnkiDroid API. We will however have to wait until the new API is tested and new AnkiDroid is deployed.
