### ISSUE TITLE
Plus button in Inflections tab is hard to see in dark theme

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#773]
See attached screenshot. The + button in the upper right corner (for switching between basic inflections and all inflections) is difficult to see in the dark theme.
![screenshot_20170630-202723](https://user-images.githubusercontent.com/2184268/27757869-8c1a52cc-5dd5-11e7-8d15-48cf0dcf927e.png)

**Comment by mvysny** [comment]
Thanks! Fixed in 3.39.39
