### ISSUE TITLE
Hang/freeze on lookup of certain kanji from Reader Popup

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#775]
Aedict 3.39.39, dark theme, on Android 6.0.1.

Steps to reproduce:

Enable "Watch Clipboard" feature in Aedict Reader.

Copy the kanji 慇 or 懃 to the clipboard, causing the Aedict Reader Popup to appear with an explanation of the kanji as expected.

Tap the popup to reveal its tabs/buttons.

Tap the top left tab/button (Aedict あ icon) for "Show words in Aedict".

Observed behavior: Phone screen says "Aedict Search" and nothing else. Phone hangs / becomes sluggish.

**Comment by mvysny** [comment]
Good catch, thanks! I wonder what is causing this behaviour...

**Comment by mvysny** [comment]
Actually the issue was in the kanji->kana reading matcher in Aedict. Optimized, fixed in Aedict 3.39.39
