### ISSUE TITLE
Aedict -> Ankidroid export bug in 3.40: first character only

### ISSUE THREAD

**Issue by aedicted** [mvysny/aedict#776]
The Kanji / readings field has been made editable during export to Ankidroid now.

However, when one seperates the Kanji readings to have the furigana centered for every Kanji seperately, the expression field only contains the first character in AnkiDroid instead of the whole input.

**Comment by mvysny** [comment]
Could you please give me an example on what I should input into the furigana field, to reproduce the issue? Thanks! ;)

**Comment by aedicted** [comment]
Sure, for example:

目に立つ

Actually, as I just noted, the bug also occurs when one doesn't edit
anything. When exporting the 目に立つ for example, the Kanji / Readings field
becomes 目[め]に立[た]つ (which would have to be changed to 目[め]に 立[た]つ in order
to have the furigana centered correctly), but the flashcard only displays
目つ then, which wasn't the case with the older version of Aedict.

**Comment by mvysny** [comment]
Thanks! Fixed in 3.41
