### ISSUE TITLE
Aedict-online.eu offline? 

### ISSUE THREAD

**Issue by sugoibachiri** [mvysny/aedict#785]
Dear Martin, 

Today I tried to access https://aedict-online.eu, but I only get error page "HTTP ERROR 404 page not found. Firefox and Android mobile 7. Any idea? Kind regards

**Comment by mvysny** [comment]
Hmm, this is weird. 404 could be caused by upgrading aedict online, but I haven't touched it recently. Currently it works for me, can you please try now?

**Comment by sugoibachiri** [comment]
Martin, it is working now. Thank you!

**Comment by mvysny** [comment]
Sure, Happy to help
