### ISSUE TITLE
Lots of search results for national flag emoji (Regional Indicator Symbols)

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#791]
I notice if I enter the US flag emoji 🇺🇸 into the word search, I get lots of search results for particles and common words. It seems to me that I should get no results for such a search.

**Comment by mvysny** [comment]
Thanks! This is caused by Aedict mistakeously considering 🇺 as kanji.

**Comment by mvysny** [comment]
Fixed in Aedict 3.42, Reader 1.3.21
