### ISSUE TITLE
Should ろ imperative verb inflection form be added?

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#792]
I came across the verb 見ろ　which is apparently the imperative form of 見る.  But 見ろ inflection form is not listed in AEDict inflection list.

Should it be added?  Or is there a reason it is not listed?

Thank-you, I hope this is not a silly question.

**Comment by mvysny** [comment]
I believe that the imperative version is base 5 which is miyou according to http://ww8.tiki.ne.jp/~tmath/language/verbs.htm#48 - can you please double check that?

**Comment by terrywallwork** [comment]
Hi Again,

Did some searching and the ろ ending for verbs that would normally end in る seems to be frequent:

See the following dictionary entries with example sentences:

http://ejje.weblio.jp/sentence/content/%E9%A3%9F%E3%81%B9%E3%82%8D
http://ejje.weblio.jp/sentence/content/%E8%A6%8B%E3%82%8D
http://ejje.weblio.jp/sentence/content/%E8%B5%B0%E3%82%8D

My Japanese is not good enough to be sure but it seems like the ろ ending is the (plain/impolite) command/imperative form.

Does that mean that よう form is equivalent?

Do you think it would be worth me trying to contact Tim Sensei to ask?

**Comment by terrywallwork** [comment]
Update asked on Hinative and got this responce:

https://hinative.com/en-US/questions/4533417

Apparently verb imperative forms are what they are here is the link to the site he pointed me to:

http://www.fluentu.com/blog/japanese/japanese-commands/

**Comment by mvysny** [comment]
Thanks, it definitely seems legit: http://ww8.tiki.ne.jp/~tmath/language/verbs.htm#44
Unfortunately, deinflecting Base4 for godan verbs produces lots of false positives (e.g. mite -> mitu even though it's 見ru ichidan, yet the deinflector is stupid and doesn't know that), so for now I will implement only the deinflector for ichidan -ro verbs.

**Comment by mvysny** [comment]
Well, I made the impossible possible and implemented a rudimentary deinflector for Base4. Enjoy ;)

**Comment by mvysny** [comment]
Implemented in Aedict 3.42

**Comment by terrywallwork** [comment]
Excellent :)

Thankyou doer of the impossible :)
