### ISSUE TITLE
Export to AnkiDroid not working?

### ISSUE THREAD

**Issue by kuukunen** [mvysny/aedict#794]
I have the newest Aedict 3 and there seems to be a feature for exporting to AnkiDroid. I am not entirely sure what it is supposed to do, but when I tap it, something flashes, but nothing else happens.

The "Share (First Entry Only)" function works, sort of, but that is just one entry, and of course it's all wrong for my AnkiDroid card format.

I'm not sure if this becomes more of a feature request, but it would be extremely nice and hopefully not too hard to implement to have a "custom CSV" style exportation where you get to specify each field for either the Share feature or the fixed  (?) "Export to AnkiDroid" feature, because I have my own card format with English Japanese kana, kanji and hints, etc.

I think something like I want would be possible by exporting to custom CSV then importing on desktop Anki... Then uploading, downloading, syncing, etc...

But that is a lot of a hassle, because basically my use case is: I see/hear a new word, I check what it means from Aedict, I want to learn it so I add it to AnkiDroid.

I am a programmer myself so I'd be happy to commit a patch, but of course that's not possible right now. I'm sort of tempted to try to make some sort of Android csv->apkg converter, but I figured it would be better to check here first, since it feels like a feature some other people might appreciate too.

**Comment by mvysny** [comment]
> I have the newest Aedict 3 and there seems to be a feature for exporting to AnkiDroid. I am not entirely sure what it is supposed to do, but when I tap it, something flashes, but nothing else happens.

The "Export to AnkiDroid" feature uses the AnkiDroid API to hand over the exported data directly to the AnkiDroid Android app. You can find more information here: #454

Aedict should ask for the target deck; if there is just one deck then the data is exported automatically there. The flashing thing is probably a progress dialog, however it is too short to notice. I should probably always show the target deck selection dialog, to avoid the confusion.


> The "Share (First Entry Only)" function works, sort of, but that is just one entry, and of course it's all wrong for my AnkiDroid card format.

Yes, that uses the ancient way of sharing text, it just sends two lines (two sides) of the card.

> I'm not sure if this becomes more of a feature request, but it would be extremely nice and hopefully not too hard to implement to have a "custom CSV" style exportation where you get to specify each field for either the Share feature or the fixed (?) "Export to AnkiDroid" feature, because I have my own card format with English Japanese kana, kanji and hints, etc.

You actually can: there is a configuration option in `Settings / Export / Custom CSV Export Format` which controls the format when exporting selected entries via `menu / Export as Anki-compatible CSV`. You can read more about the formatting string here: http://aedict.eu/export.html

>  I'm sort of tempted to try to make some sort of Android csv->apkg converter, but I figured it would be better to check here first, since it feels like a feature some other people might appreciate too.

I actually tried to implement that, yet apkg is basically a zipped sqlite database with no description, so after several attempts to link things together via ids in an undocumented format I gave up. But please feel free to talk to Tim Rae of AnkiDroid regarding that.

**Comment by kuukunen** [comment]
> The "Export to AnkiDroid" feature uses the AnkiDroid API to hand over the exported data directly to the AnkiDroid Android app. You can find more information here: #454

Yea, I did end up there when Googling it. Although as an end user, it's of course not very useful. :P

> Aedict should ask for the target deck; if there is just one deck then the data is exported automatically there. The flashing thing is probably a progress dialog, however it is too short to notice. I should probably always show the target deck selection dialog, to avoid this kind of confusion.

Actually it does nothing whether or not I have multiple decks. Or in the beginning I had one deck shown plus the Default deck that is hidden. I also tried adding some other decks and adding cards to the Default deck.

Still, I can't see any dialog and I can't see any cards anywhere in AnkiDroid. I checked through logcat quickly but couldn't see anything relevant happening when trying to export, either in AnkiDroid or in Aedict.

And looking into it a bit closer, the flashing actually only happens when exporting entries from the Notepad, not when doing it from "DICT" tab.

> You actually can: there is a configuration option in Settings / Export / Custom CSV Export Format which controls the format when exporting selected entries via menu / Export as Anki-compatible CSV

Yea I found the menu option, that's what I was actually referring to when saying "custom CSV". Just that it doesn't seem to be possible to import it to AnkiDroid directly. So of course the other way of doing it would be to ask Tim Rae if they wanted to implement CSV importing.

And even with the "Export to AnkiDroid" feature, it seems it wouldn't really be possible to customize it for my flash card format.

So it seems this issue is actually two somewhat separate things: bug "Export to AnkiDroid not working" and feature request "It would be nice to support custom Anki(Droid) cards". Which might also be delegated to AnkiDroid side as "Add support for importing custom CSV." Or, well, I don't know if the bug is on AnkiDroid side as well. 

For more technical info, I'm on Samsung Galaxy S7 edge. Android version 7.0. (Could be a problem with Samsung's silly custom stuff too.)

I did a logcat on when I click the "Export to AnkiDroid" from "DICT" tab. I couldn't see much in it, but there IS some sort of permission request on ActivityManager that happened every time I selected the export. 
Aedict pid: 13501, AnkiDroid pid: 11148 (not shown), Aedict uid: 10060 (shown in ActivityManager's line)
https://gist.github.com/kuukunen/23c56acba45937b54353a4aad70ea239

**Comment by mvysny** [comment]
> Export to AnkiDroid not working

Perhaps there's issue with permission? Please see #782 for details.

> It would be nice to support custom Anki(Droid) cards

Actually Aedict doesn't export formatted front/back of the cards anymore. With the new API, Aedict exports all information it has, as-is, to the AnkiDroid; the formatting is then done by AnkiDroid itself. You can check e.g. here for information on how to change the card template per-deck in AnkiDroid: https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting

**Comment by kuukunen** [comment]
OK. I looked a bit into it again. I'll write the workaround at the bottom, so people might notice it better. I'll possibly open a separate feature request issue on the other stuff, since it's clearly not related, so I'll just focus on the bug. But first of all I'd like to apologise for not finding the other issue before, even though I find some of the other ones.

Basically I noticed the same behaviour as someone mentioned on the other issue: when I go to turn on the "Read and write to the AnkiDroid database" permission in the settings, it would turn on, but it wouldn't stay on when checking the menu again. AnkiDroid's setting would work just fine. And as someone said, the other curious thing compared to AnkiDroid is if you try to switch it on and then off, it would say "This app was designed for an older version of Android. Denying permission may cause it to no longer function as intended. [Cancel] [Deny Anyway]", presumably referring to the pre-23 API level.

I tried all kinds of different things, and I can't even manually enable the permission through adb with package manager. However, trying to do that FINALLY gave me something useful in logcat: "PackageManager: Cannot grant runtime permission to a legacy app".

So, I'm pretty convinced what's happening is that because AnkiDroid is 23+ API level, it can set the runtime permission just fine. And it's also possible the whole "Cannot grant runtime permission to a legacy app" has come as a security feature in a newer/different Android version.

Why does it work sometimes at all then? I assume it's because if you install Aedict first, the whole "com.ichi2.anki.permission.READ_WRITE_DATABASE" doesn't even exist so you can't request it. And with the "legacy apps" (on newer Androids?) you can only change permissions on install time... or possibly revoke and re-grant permissions that were granted on install time, you can even see "install permissions", granted or not, separated from the others when you do "adb shell dumpsys package com.ichi2.anki | grep perm".

In the end I don't think it's an _actual_ bug in Android, since it seems like it's something that was put there on purpose... but obviously the UI should say something about it. I don't think custom permissions between pre-23 and post-23 apps is a common thing. I can't even find anything other than the actual Android sources if I Google for "Cannot grant runtime permission to a legacy app".

Unfortunately I think the only proper solution would be to increase API level, but of course that's a huge hassle code-wise.

**Workaround: Make sure you install Aedict AFTER AnkiDroid. If you already have both, uninstall JUST Aedict and reinstall it.**

**Comment by mvysny** [comment]
Thank you for your time and for your analysis! Yet I am still convinced that it *is* a flaw in Android, since:

1. custom permissions were not banned explicitly
2. Android must grant permissions to pre-24 apps

Yet, Android clearly does not, and explicits all sorts of weird behaviour until AnkiDroid is installed and the `com.ichi2.anki.permission.READ_WRITE_DATABASE` springs into existence. 

Yet, this is of no importance since it is not up to us to do anything about this behavior, and it is not in our power. The only course of action available to us is to encourage users to do the workaround. I will update Aedict's error message to urge the user to reinstall Aedict, and reference this bug.

Unfortunately, I can't API-bump Aedict because of reasons explained at #741

>   I'll possibly open a separate feature request issue on the other stuff, since it's clearly not related

Sure, please feel free to open a new feature request in this bug tracker.

**Comment by mvysny** [comment]
Also related to #723 and #782
