### ISSUE TITLE
Verbs no longer show inflection tab...

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#796]
Just got the most recent update and for verbs the inflection tab section is no longer present.  Other types of word still seem to have inflection tab.

See screenshots.
![screenshot_2017-09-20-13-29-57](https://user-images.githubusercontent.com/19387982/30643925-97b6f518-9e08-11e7-9c22-ed69df4fdfe7.png)

### Thank you for making the time to report a bug and make Aedict better!

Thank you for your interest in Aedict. Prior submitting bugs, please make sure that you have newest Aedict from Google Play, Blackberry store or Amazon App store.

A screenshot is often worth a thousand words, so please make sure to include one ;)

Income from Google Play and other stores is rather small, and is made even smaller by the 30% fee charged by Google and 20% VAT charged in most countries. Please consider supporting the project on Patreon: 

https://www.patreon.com/bePatron?u=2914375

**Comment by mvysny** [comment]
You're right, thanks for letting me know. It's weird since for other ichidan verbs such as taberu the inflection pane shows properly. Let me look at this.

**Comment by mvysny** [comment]
Fixed in Aedict 3.43.
