### ISSUE TITLE
Entry detail screen: make the "Add to Notepad" button always visible

### ISSUE THREAD

**Issue by lostatlast** [mvysny/aedict#800]
Hi everyone! I am intensely using the notepad function I Aedict3. It's usually very friendly. Problem is, when the found word is a verb, the notepad button is replaced by the quiz button. The quiz function i something I never plan to use. I'd rather access the notepad quickly. And maybe even add automatically to the list I am using until I select a new one. 
I see that if I were using a larger screen, like a tablet, it could be solved. Or that if I rotate the screen the notepad button appears next to the quiz button. But on my phone, with normal orientation, I have to touch the 3 vertical dots and choose "add to notepad" every time. As I am making a list of words from an N1 book, this has become rather annoying and it's slowing me down a little. 
Well, it would be great to know if I can change this or have it implemented in the future. 
So my request is: hide quiz button or swap its place with notepad button.

Thanks mvysny! 

### Thank you for making the time to report a bug and make Aedict better!

Thank you for your interest in Aedict. Prior submitting bugs, please make sure that you have newest Aedict from Google Play, Blackberry store or Amazon App store.

A screenshot is often worth a thousand words, so please make sure to include one ;)

Income from Google Play and other stores is rather small, and is made even smaller by the 30% fee charged by Google and 20% VAT charged in most countries. Please consider supporting the project on Patreon: 

https://www.patreon.com/bePatron?u=2914375

**Comment by mvysny** [comment]
Yeah, that makes sense, thanks for reporting. Fixed in Aedict 3.44

**Comment by lostatlast** [comment]
Great, thanks!

2017-09-26 12:01 GMT+02:00 Martin Vysny <notifications@github.com>:
