### ISSUE TITLE
Example search starting with numeral returns wrong results

### ISSUE THREAD

**Issue by Todew** [mvysny/aedict#803]
An example search starting with a numeral followed by kana returns too many reaults.  E.g. search on 3まい returns all examples containing 3 even if not followed by まい   i.e . ３か, ３に, 3じ etc.  This is the same as if you search just on 3.  This makes it hard to search for examples using counters.
I wouldn't say this is urgent but I just came across it and thought it was worth mentioning.

**Comment by mvysny** [comment]
Thanks for letting me know, this is definitely something I need to look into.

**Comment by mvysny** [comment]
Fixed in Aedict 3.46
