### ISSUE TITLE
Filter should be disabled when not visible in the main screen

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#811]
It is confusing when a filter is applied to a search even though the filter configuration is not visible on screen: the user may receive less results than expected, for no apparent reason. See https://groups.google.com/forum/#!topic/aedict-users/DGqndqydoto for more information.

**Comment by mvysny** [comment]
The current filter configuration should be displayed in the "query" part of the screen (right above the results); but I guess it's not immediately obvious what that means.

I'm thinking to not to apply any filtering when the filter bar is hidden. What do you guys think?

**Comment by jimmubreen** [comment]
Absolutely! Or alternatively when returning results (or saying there are no results) include an alert that there are active filters.

**Comment by mvysny** [comment]
Currently there is a small info box that lists all enabled filters. For example:
![screenshot_20171129-151318](https://user-images.githubusercontent.com/254091/33376895-224ee564-d518-11e7-8d86-cce68e048fa7.png)
(Please note the `[common only]` text). But perhaps I should also include something like "with filters enabled: [common only]" and perhaps include the filter icon? Or would you still prefer filters to be disabled when they're invisible?

**Comment by jimmubreen** [comment]
Hi Martin,

Sorry for the late/slow reply.
Yes, I think it should say that a filter is active. My preference would be
for filters not to be sticky, and for the default to be "off", but then
maybe sticky/non-sticky filters could be a settable option.

Jim


On 30 November 2017 at 00:17, Martin Vysny <notifications@github.com> wrote:
> Currently there is a small info box that lists all enabled filters. For
> example:
>
> (Please note the [common only] text). But perhaps I should also include
> something like "with filters enabled: [common only]" and perhaps include the
> filter icon? Or would you still prefer filters to be disabled when they're
> invisible?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Jim Breen
Adjunct Snr Research Fellow, Japanese Studies Centre, Monash University
http://www.jimbreen.org/

**Comment by mvysny** [comment]
I like the idea of having the stickiness configurable, I'll implement it that way.

**Comment by mvysny** [comment]
Fixed in Aedict 3.48
