### ISSUE TITLE
Increase Kanji Quiz Size

### ISSUE THREAD

**Issue by dezorianguy** [mvysny/aedict#814]
As requested my ideas about how to improve on the Quiz feature of Aedict.
Font size is microscopic as of now. So I would suggest you increase displayed Kanji and hiragana by around 80%, as the Kanji already are displayed that size when starting a "Jojo Grade" Quiz for example (visibility even further increased by putting it infront of a grey background).

![screenshot_2017-12-12-21-55-36-978_sk baka aedict3](https://user-images.githubusercontent.com/34491104/33908562-1da7ce74-df89-11e7-85e9-287868b03131.png)
![screenshot_2017-12-12-21-55-53-129_sk baka aedict3](https://user-images.githubusercontent.com/34491104/33908563-1dca8f90-df89-11e7-9ffa-ec427cf98c57.png)

**Comment by mvysny** [comment]
I'm not sure I understand. There are two layouts used in the kanji quiz. The first one is the single kanji layout (shown on both of your screenshots); the other is a quick overview layout (shown when quizzing jmdict entries and or example sentences).

1. Which layout would you like to increase the font size in?
2. Can you please provide drawing of the suggestion of how big the kanji needs to be? You can just draw your suggestion freely on top of the screenshot.

**Comment by dezorianguy** [comment]
As of now, as you mentioned correctly, the big sized Kanji (with the greyed background) are only used when a single kanji is to be displayed.
I'd wish to have the same size for all the JMDICT entries of my notepad. As of now, when starting a jmdict quiz the kanji in question appears in the font size of the hiragana/katakana readings next to the "kanji in question" of the images I uploaded above.

I don't know how I would draw it. The desired size of the quizzed kanji is right in the screenshots. :)
If you start a quiz from your notepad, you do not get this big sized kanji from the images above, right (or am I doing something wrong)? ;)

**Comment by mvysny** [comment]
Aha, now I understand. So the big-sized Kanji size is fine; it's the size of the JMDict entry that's too small. Let me increase the font size and I'll post a screenshot.

**Comment by mvysny** [comment]
Increased the font size by 80%. While on shorter entries this improved the usability quite vastly:

![device-2018-01-15-155738](https://user-images.githubusercontent.com/254091/34945832-57e0dd8a-fa0d-11e7-8c2b-25c4c32fce71.png)

on larger entries the entry itself obscured the kanjipad; on smaller devices the kanjipad becomes nearly invisible and unusable:

![device-2018-01-15-155854](https://user-images.githubusercontent.com/254091/34945837-5e975f6e-fa0d-11e7-9d0d-38a98f6f3e2d.png)

![device-2018-01-15-155711](https://user-images.githubusercontent.com/254091/34945840-630246b8-fa0d-11e7-91c1-ca152d4d7e88.png)

Let me try a compromise: an increase of 40%

**Comment by mvysny** [comment]
With 40% increase the kanji pad is still large enough:

![device-2018-01-15-161034](https://user-images.githubusercontent.com/254091/34946224-b1f4a698-fa0e-11e7-8c4d-6f7392aba4d2.png)

Please let me know if this font size is big enough.

**Comment by dezorianguy** [comment]
Yeah, thanks for taking care of this. The first ones indeed look a bit overkill. :)
I would need to try a specific size before I can tell you how it feels. But the last uploaded image looks very promising. Of course it shouldn't look to crowded in the end. It is that the prior quiz had a reaaaally small font size, so any increase is a blessing to me. :D

**Comment by mvysny** [comment]
Fixed in Aedict 3.48
