### ISSUE TITLE
Not updated anymore on Amazon store?

### ISSUE THREAD

**Issue by L0upBlanc** [mvysny/aedict#815]
Hi, I would like to know if there is any plans for a future update on Amazon? There was no update since the 3.40 version and I still have issues with the translation in multiple languages which makes the display unreadable when I'm looking for the translation.

**Comment by mvysny** [comment]
Oops, sure, I'll update. Thanks for notifying me!

**Comment by mvysny** [comment]
It's just that it's pita to update apps on Amazon, and they review the updates, so I try to update to only stable versions. And then I forget to update.

**Comment by L0upBlanc** [comment]
I was just worried it won't be updated anymore. Great to know it's ongoing! Thanks for your answer. :)

**Comment by mvysny** [comment]
No problem :) the latest version is live
