### ISSUE TITLE
Happy New Year (issue)

### ISSUE THREAD

**Issue by Todew** [mvysny/aedict#816]
Translation of Happy New Year, kana does not match kanji:
"明けましておめでとう。 [あける おめでとう。]

明けましておめでとうごぁいます
Tony

**Comment by mvysny** [comment]
Unfortunately there is nothing I can do. The example sentences do not contain their kana transcription, only the readings of words in base form. Aedict does its best to reconstruct reading of the sentence  from this sketchy infirmation, but If verb is irregular it is very hard to do.

**Comment by mvysny** [comment]
You can join the tatoeba project and contribute a proper transcription for that particular sentence. Aedict will then pick it up

**Comment by Todew** [comment]
Thanks.  Unfortunately as a beginner I am not at all qualified to help 
translate anything.
Happy New Year anyway.

**Comment by mvysny** [comment]
Happy New Year :raised_hands:
