### ISSUE TITLE
Feature Request : J-J dictionnary

### ISSUE THREAD

**Issue by Vaanen** [mvysny/aedict#818]
Hello, so i really love this app, it's awesome ! Really don't regret paying the fee, been using it for around a month or two and its vital to my studies.

However, i will have to make the switch to full japanese at one point and thus would need J-J definitions. Unfortunately, it seems there is no J-J dictionnary in Aedict. Would that be possible to be added  ? That would be awesome, because some words don't even have a real english translation so it's very hard to understand them and i'm more and more relying on japanese definitions. Also an option for not downloading the english translation of Sentences ? They kinda mess up the formatting anyway by going straight before the new sentence with a comma, and i don't want them anyways.

Would really make it the best and most complete dictionnary app for all stages of learning, since the J-J switch is inevitable at one point and i would hate to have to stop using it because it has too much features i can't live without anymore. Thanks !

**Comment by mvysny** [comment]
Hi, happy to hear that you like Aedict :)

The only J-J dictionary currently available in Aedict is the Daijirin dictionary; however that dictionary is not free and you need to purchase it separately. You will need to follow these steps: https://www.patreon.com/posts/daijirin-support-7532983

Of course, if you know about a good free J-J dictionary, just let me know and I will try to add it to Aedict.

Regarding the possibility to hide the english translation of example sentences - I'm not sure what you have in mind. Please take a screenshot of the phone screen and use GIMP or other drawing program to draw your ideas there. Then, just attach the image here. Thanks!

**Comment by Vaanen** [comment]
Thank you ! I will look into the daijirin, there is one at 26 euros on the appstore, prettyvexpensive but i think it will be worth it.

for the sentences, it lllks like this

**Comment by StaySkeptic** [comment]
As a workaround it may be a good idea to add a lookup feature for online japanese dictionaries. It's at least make it a bit easier to keep switching when you need to.

**Comment by Vaanen** [comment]
Frankly, if yiu want j-j dictionnary i highly suggest buying daijirin and
contacting the developper to add the dictionnary. its absolutely incredible
and works much better than their own application, and having both english
and japanese translation at the same time makes the transition much
smoother. its one of the best investment i made, its only 30 bucks so i
cant recommend it enough

**Comment by mvysny** [comment]
> the next sentence directly follows the english translation and it kinda looks funky, thats why i would like to know if there is a possibility of putting the english translation in another field, or just avoiding the english translation alltogether and have an option to just get the japanese sentences ?

Nope, currently the examples are always as "KANJI - READING - ENGLISH" to a single field and this can not be currently changed. Please open a feature request with the suggestion and an explanation why this is a good idea.

> also, when i put a custom sentence separator, if i reboot the app, some space is added at the end which kinda breaks (very very slightly) the formatting. this is not a big deal at all, just thought about sharing this info

Android stores those in a XML internally and that could do funky stuff - add spaces, newlines etc. Nut sure whether there is anything I can do about this. Yet please open a bug report and I can try to look into that.

> As a workaround it may be a good idea to add a lookup feature for online japanese dictionaries. It's at least make it a bit easier to keep switching when you need to.

You can do that now. Open the kanji details, then click the three-dot upper-right overflow and "Show in External Dictionary". By default four online dictionaries should be defined, you can add or remove those in Settings / GUI Tuning / Dictionary Entry Screen / External Dictionaries.

**Comment by mvysny** [comment]
Since there is no other J-J dictionary than Daijirin right now, closing this issue as won't fix. However, if you will find a JMDict-compatible J-J dictionary available for free, please reopen this issue and post the link to the dictionary.

**Comment by baongoc124** [comment]
Sorry for hijacking this. But as Patreon is now dead. I cannot check the link for instructions of how to add Daijirin. If anyone still has it, please give a helping hand! Thank you!

**Comment by mvysny** [comment]
Thank you. I've also added the instructions to activate Daijirin into the Aedict Blog here: https://mvysny.github.io/aedict-blog/Daijirin/
