### ISSUE TITLE
inflection list description tweek

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#822]
I noticed that on the verb inflection list one of the inflecion type is listed as:

No wa

Would a more descriptive explanation be useful, such as:

The act of of doing X ...
![screenshot_2018-03-01-18-50-53](https://user-images.githubusercontent.com/19387982/36863944-0767e3d2-1d83-11e8-9812-4cfd3c6f3534.png)
![screenshot_2018-03-01-18-52-50](https://user-images.githubusercontent.com/19387982/36863956-14f32516-1d83-11e8-943b-fc6982c80d33.png)

Or some ther form of phrase.

**Comment by mvysny** [comment]
Thanks! Fixed in Aedict 3.49
