### ISSUE TITLE
Feature Request - Clipboard vocab sense tweak.

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#823]
Hi,

I have had one formatting tweek that maybe useful for people who use the Aedict clipboard copying feature.

I noticed that when copying a vocabulary entry (green dictionary code version) to the clipboard that the different sense entries are just combined together.  There is no way to visually see when one sense ends and another begins with the clipboard copy, see:

着る, 著る [きる]: (P, v1, vt) to wear (in modern Japanese, from the shoulders down), to put on, to bear (guilt, etc.)

It would be useful if there was some sort of visual indicator such as ; or even place each sense on its own line:

着る, 著る [きる]: (P, v1, vt) to wear (in modern Japanese, from the shoulders down), to put on; to bear (guilt, etc.)

Or:

着る, 著る [きる]:
(P, v1, vt) to wear (in modern Japanese, from the shoulders down), to put on;
to bear (guilt, etc.)

Or even better:

着る, 著る [きる]:
1. (P, v1, vt) to wear (in modern Japanese, from the shoulders down), to put on;
2. to bear (guilt, etc.)

Personally I would like some way to specify the clipboard copy format but I get that it would be harder work for you.

Thank you 😁

**Comment by terrywallwork** [comment]
Changed title as this is a feature request.

**Comment by mvysny** [comment]
Thanks! You're right - I need to separate senses with `;` while separating glosses with `,`, to make a distinction.

Since you can select multiple entries and copy them to clipboard, I strive to keep one entry per line.

Fixed in Aedict 3.50.8
