### ISSUE TITLE
Feature request: Export to Ankidroid setup on prefs to export two-ways at the same time 

### ISSUE THREAD

**Issue by ShiroiKuma0** [mvysny/aedict#824]
Use case: I currently have export to Ankidroid set up in preferences in “Export Flashcard front/back” as “Kanji, Reading + English”. 

This allows me to train new words, so I test their knowledge in Japanese. 

However, I'd also like to keep this and also test for the knowledge from English—so for this I'd like to also export “English, Kanji + Reading” for the same cards to the same deck, so it will test me both ways. 

So I'd like to request, to add this compound option to the settings, which would then export two cards for the selected word at the same time.

**Comment by ShiroiKuma0** [comment]
Also, I think a prior version of Aedict exported example sentences to the back card, unless I did it all by hand, which I doubt. It's a very useful feature—can you bring it back?

**Comment by ShiroiKuma0** [comment]
Also, it just occurred to me—if you just added a pulldown option of the front/back content to the window, that pops up when you select to export the card, it would be easy to export the two cards consecutively. Currently, it's unfeasible because after every export you have to go to settings, flip front/back and export again, very cumbersome.

**Comment by ShiroiKuma0** [comment]
Upon further inspection—maybe this request is unnecessary, I've fiddled somehow with Ankidroid, and although Aedict only exports one card, even the proper reverse one is created in the deck, don't know how, but it's working…

**Comment by mvysny** [comment]
Ah AnkiDroid export, a source of constant confusion :-)

The AnkiDroid export now works in a way that Aedict exports raw data for every card exported (you can now export multiple cards at once). Then Aedict pre-creates three AnkiDroid card types:

* Kanji front, Reading+English back
* Kanji+Reading front, English back
* English front, Kanji+Reading back.

The card type is generally a set of instructions for AnkiDroid how to display the raw data. You can freely create, edit and remove the card types in the AnkiDroid itself; you can therefore include your own new card types.

You can find more information here: http://aedict.eu/faq.html (search for AnkiDroid). For more info please consult AnkiDroid documentation.

I believe this answers your question, therefore I'll mark this as closed.
