### ISSUE TITLE
[FR][Aedict 3] Support for exporting sample words for kanji entries

### ISSUE THREAD

**Issue by RemiNV** [mvysny/aedict#825]
Similarly to the %examples% item in custom exports, I would really appreciate a %words% item that would output 2 or 3 words examples; contents would be identical to the first 2 or 3 entries in the "Words" tab when opening a kanji in Aedict3 (with "Any reading of X" in the dropdown).

Rationale: examples are not very useful when exporting single kanjis (especially for flashcards), since the kanji may be used in an uncommon word or even a name, and it's hard to visually locate the word in the sentence quickly. Word examples are very important when learning kanji through flashcards, though.

I realize that you have little bandwidth for FRs right now, but I would really appreciate this addition - thanks for all the work so far !

**Comment by mvysny** [comment]
Thanks, that's a great idea! So for example for the `本` kanji the `%examples%` would be replaced by "本; 本当に; 日本; 本当, 本當" ?

**Comment by RemiNV** [comment]
Yes, with the associated readings (hiragana) and meanings of each word, that would be great !
Having a separate %words% tag to keep current behavior would be nice, but considering that sentence examples are not so useful for kanji entries, replacing %examples% would work well too.

Thanks !

**Comment by mvysny** [comment]
Will do! Yup, let's leave `%examples%` as it is. I will introduce a new export tag `%words%` as you suggested.

**Comment by mvysny** [comment]
Implemented in 3.49
