### ISSUE TITLE
There should be an option to disable inflection recognition

### ISSUE THREAD

**Issue by mkju** [mvysny/aedict#827]
There should be an option to disable inflection recognition. At least for me it just produces unnecessary clutter in search results.

**Comment by mvysny** [comment]
Hi, do you mean that the search bar should optionally perform no deinflection of the input provided?

**Comment by mkju** [comment]
Yes.

**Comment by mvysny** [comment]
Added the `Settings / GUI Tuning / Search / Deinflect` setting. Implemented in Aedict 3.49.
