### ISSUE TITLE
Aedict 4

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#828]
Since Android will enforce lazy permissions as described in #741 Aedict will be required to ask for all SD-Card accesses, which is ridiculous and quite incompatible with the feature "custom location of dictionaries". However, I can't just simply force the dictionaries to be in a folder allocated by Android for Aedict because that often resides on internal memory (Android lying its ass off here) and the users will be pissed. After years of tweaking of the dictionary location it seems that it's working for everyone more or less, and I will not dare to touch that and risk a shitstorm of complaints.

Therefore I take this as an opportunity to introduce a new, backward-incompatible Aedict version and make all ground-breaking and incompatible changes that have been piling up:

1. Enforcing dictionaries to reside on a directory allocated by Android. This requires no permissions and should therefore work properly.
2. Removing the old way of storing notepad/tags/srs as a files. The old way is dumb and does not work at all with huge notepads which some users do have, because it requires all data to be present in-memory which is the source of frequent OutOfMemoryError crashes. Use a database from the very beginning.
3. Remove CouchBase. CouchBase is a database which uses lots of CPU all the time; the Android CouchBaseLite is utter crap (they've dropped the ForestDB without any explanation which left Aedict screwed) and frequently fails to synchronize with the Gateway (randomly drops attachments, and then the sync internally crashes that there is no attachment, wtf). Evaluate a replacement.
4. Change the payment model from one-time to a yearly subscription. One-time payments simply do not generate enough revenue; I therefore have to have a job. And since I have kids as well, that leaves me with very few time to spare on any further development of Aedict.
5. Changing the payment model also helps to fight the piracy - Aedict is currently a paid app with no protection, and so hackers reverse-created Aedict APKs from the app installed on their phones and uploaded Aedict into other playstores.

**Comment by mvysny** [comment]
The min Android SDK level needs to be 19 (Android 4.4 and higher): I will be storing the dictionary files into `getExternalFilesDir(String)` and APIs 18 and lower require `WRITE_EXTERNAL_STORAGE` permission for that. I can't use `WRITE_EXTERNAL_STORAGE` permission since I would have to ask for it basically everywhere in the code.

**Comment by mvysny** [comment]
Possible CouchBase replacements:
1. Using Sync Adapters. I've saw the API. I'd rather kill myself than use that horrible shit.
2. Use Firebase: https://firebase.google.com/docs/database/android/start/ disadvantages: probably Aedict Online can't connect there; also to scale for 5k users I'd need $25/month which is okay: https://firebase.google.com/pricing/
3. Use other forms of sync: https://www.quora.com/What-is-the-best-way-to-sync-local-user-data-with-server-data-for-mobile-apps

**Comment by mvysny** [comment]
The subscription-based approach will also allow me to unlock certain parts of Aedict for free. I'm thinking that the search+entry details should be free; everything else (SRS, Quiz, Notepad, maybe Kanjipad?, export to AnkiDroid?) will need a subscription. This is just an idea and remains to be seen.

**Comment by thaumasiotes** [comment]
With respect to the payment structure, are you aware of [Pleco](http://www.pleco.com/)? They are the  standard Chinese dictionary app, and they use a payment model basically equivalent to Aedict 3 -- the base application is free, but they sell a variety of pay-one-time paid addons. The major difference (as far as I can see) is that their paid addons are heavily focused on licensed dictionaries.

I apologize if you've already considered this, but my selfish reason for mentioning it is that professional dictionaries add a lot of value for the user too -- I own 5 paid dictionaries through Pleco in addition to the two they make available for free.

**Comment by mvysny** [comment]
Unfortunately Pleco's model may not be applicable to Aedict: Pleco has 1 million+ users and is able to generate sustainable revenue even if only 0,1% of users purchase something one-time only. Opposed to that Aedict has 5000 users and the revenue from selling one-time goodies is very low (roughly 200 eur per month, definitely too low for a primary income). Also, selling additional JP dictionaries doesn't sound right to me since I'm not the author of those dictionaries...

Yet you may be right - perhaps I should reconsider the freemium model (give basic features for free, hide everything else behind a single payment - probably a recurring payment until the number of Aedict users skyrockets which would allow one-time payment to generate enough revenue).

**Comment by mvysny** [comment]
I have pushed Aedict 3.50.x update which now switched to the Aedict Ultimate subscription. Please find more information about the Aedict Ultimate here: https://groups.google.com/forum/#!topic/aedict-users/_Hw_txSmmO4
