### ISSUE TITLE
Possible incorrect inflection for くる。

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#829]
The inflection for くる seems to be incorrect for I'll Let/Make/Have Verb.  Its indicated as せる but should be させる.

See screenshot.

![screenshot_2018-04-02-10-29-57](https://user-images.githubusercontent.com/19387982/38191808-029d354e-3662-11e8-8713-8b54f09deab8.png)

Also the see more information enties say it should be させる also.

**Comment by mvysny** [comment]
I think this differs for ichidan and godan verbs: tabesaseru uses saseru, but au uses awaseru. I wonder which is correct for kuru since it's irregular. Let me try to find some info.

**Comment by mvysny** [comment]
You're right: http://maggiesensei.com/2009/10/24/%E3%81%95%E3%81%9B%E3%82%8B%E3%81%95%E3%81%9B%E3%82%89%E3%82%8C%E3%82%8B-saserusaserareru/

来させる is the right form

Also here: https://www.jref.com/articles/causative-forms.116/

来させる

**Comment by mvysny** [comment]
Fixed in Aedict 3.49
