### ISSUE TITLE
tts voice to simply read the word 

### ISSUE THREAD

**Issue by dezorianguy** [mvysny/aedict#830]
good day sir, 

when I decide to let aedict read a word aloud, by pressing the speaker button next to the Kanji, it always opens up a box where I am presenting with 2 or more choices of what exactly I want it to read aloud. mostly I can choose the kanji and hiragana reading. which in speech doesn't make any difference... 

so, for example choosing 車 to be read aloud. instead of just saying the word it let's me choose between 車 and くるま 。 

if that could be fixed that would be awesome. :) 

best wishes, 
chris

**Comment by mvysny** [comment]
The old TTS engines were pretty weak and would say nothing if I passed in just "車". Hence I had to make the user to choose to pass either 車 or くるま, based on the level of the TTS he had installed.
However, Google's TTS got pretty awesome and now is able to read both 車 and くるま. So in this specific case where the word entry consists of just one kanji and just one reading, I should not display the choice popup but should simply always pass in "車"

**Comment by mvysny** [comment]
Fixed in 3.49
