### ISSUE TITLE
Roman font got large unexpectedly

### ISSUE THREAD

**Issue by kcroker** [mvysny/aedict#832]
I have aedict v3.48 and donate on Patreon.

For some reason, the font for the kanji and roman characters became larger.  This not only looks unsightly, but less content fits on the screen.  How do I restore the original settings?   I'm sorry I do not have a screenshot of the original configuration, only the newer one.  I have a Moto x4, with everything up to date.

Thanks!
-k
![screenshot_20180417-141922](https://user-images.githubusercontent.com/10903188/38905208-df69cd7c-424a-11e8-9979-6bb7fe3b3a5f.png)

### Thank you for making the time to report a bug and make Aedict better!

Thank you for your interest in Aedict. Prior submitting bugs, please make sure that you have newest Aedict from Google Play, Blackberry store or Amazon App store.

A screenshot is often worth a thousand words, so please make sure to include one ;)

Income from Google Play and other stores is rather small, and is made even smaller by the 30% fee charged by Google and 20% VAT charged in most countries. Please consider supporting the project on Patreon: 

https://www.patreon.com/bePatron?u=2914375

**Comment by mvysny** [comment]
Thanks for letting me know, and thanks for your support! I actually do not remember increasing the font size for the recently viewed (or list items in general). I have checked the sources, and it seems that the text size of 22 sp is used at least from 5.march 2017. The sense translation is using 16 sp.

If this is an issue, I can add a setting which decreases the kanji+reading size to, say, 20 sp (or even 18 sp even though I wonder if the kanjis will still be readable at this size), while keeping the sense size to 16sp still. What do you think?

**Comment by mvysny** [comment]
Closing as inactive; please reopen if need be.
