### ISSUE TITLE
Volitional automatic deinflection does not activate for つぶそう

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#839]
Hi,

I noticed that when I look up a Verb (Volitional form 潰そう (Dictionary form 潰す)) in hiragana つぶそう search input, Automatic verb deinflection does not activate. However other forms such as plain negative work correctly つぶさない works as expected.

![screenshot_2018-07-31-14-20-15](https://user-images.githubusercontent.com/19387982/43462592-68fa4294-94ce-11e8-8f9f-312549cb5f2e.png)

**Comment by mvysny** [comment]
Thanks! Fixed in Aedict 3.50.8
