### ISSUE TITLE
Popup not appearing on Huawei P10pro, EMUI 8.0

### ISSUE THREAD

**Issue by norbusan** [mvysny/aedict#840]
Despite having allowed Aedict Reader to "show Dropzone" in Phone Manager -> Dropzone management, I don't get any popups when selecting text.

**Comment by mvysny** [comment]
Thanks, and sorry for the app malfunction. Can you please verify the following:
1. Does Google Translator work on your phone correctly?
2. In Aedict Reader, do you have both "Watch Clipboard" and "Always available" checked?
3. Does the Popup show at least in the Reader's built-in browser, when you select some text?

**Comment by norbusan** [comment]
Indeed, "Always available" was not selected (I don't remember having activated it on my previous phone, but that might be my weak memory). 
Sorry for the noise, closing the issue.

**Comment by mvysny** [comment]
No worries. "Always active" taps into the clipboard which is a privacy concern, that's why there is such a switch.
