### ISSUE TITLE
Aedict kanjipad extension broken? 

### ISSUE THREAD

**Issue by blastrock** [mvysny/aedict#841]
It seems the last update broke the kanjipad extension. I'm not sure how to check, but kanji recognition seems worse, and the +-2 strokes checkbutton has disappeared. Please tell me if I can provide more information.

On a side note, the side menu is not accessible anymore from the kanji search activity.

**Comment by mvysny** [comment]
Hi, I know this will be highly unpopular move, but the Kanjipad Extension is now part of Aedict itself and is activated when the Aedict Ultimate subscription is activated. Please read more here: https://groups.google.com/forum/#!topic/aedict-users/_Hw_txSmmO4

**Comment by blastrock** [comment]
Oh I see, thanks for the answer :(
