### ISSUE TITLE
Maybe this is not a bug, and I just need instructions. I bought a new phone and want to transfer my Aedict notepad from my old phone to my new phone. How do I do that? If it helps, I am a former Patreon supporter (had to cancel because I lost my American job).

### ISSUE THREAD

**Issue by bjschmidt61** [mvysny/aedict#842]
### Thank you for making the time to report a bug and make Aedict better!

Thank you for your interest in Aedict. Prior submitting bugs, please make sure that you have newest Aedict from Google Play, Blackberry store or Amazon App store.

A screenshot is often worth a thousand words, so please make sure to include one ;)

Income from Google Play and other stores is rather small, and is made even smaller by the 30% fee charged by Google and 20% VAT charged in most countries. Please consider supporting the project on Patreon: 

https://www.patreon.com/bePatron?u=2914375

**Comment by mvysny** [comment]
Unfortunately this is not currently possible. However, I'm working on a new synchronization solution, so you will be able to sync all your devices' notepads, recently viewed, everything.

**Comment by mvysny** [comment]
Just to let you know, I'm still working on the sync support, and actually I'm getting closer :) You will be able to use Aedict Online for syncing or (if you are worried about privacy) you can even setup your own sync server. More details here: https://gitlab.com/mvysny/umn/tree/master/umn-proxy-server - the docs are sketchy but I will post more documentation on this as the work will near towards finish.

**Comment by mvysny** [comment]
The Sync support is now implemented. Note that the synchronization only works with Aedict Ultimate subscription.

1. Go to https://aedict-online.eu and create an account there.
2. Upgrade Aedict on your phone and purchase the Aedict Ultimate subscription
3. Go to `Settings / Expert Settings / Storage Type` and select `UMN`. Your data should be copied to the UMN database on your device.
4. Go to `Settings / User Data / Aedict Online Settings` and fill in your AO username and password, then check "Synchronize with Aedict Online"
5. After that's done, please wait a bit to have your data synchronized to your phone.
