### ISSUE TITLE
How do I migrate my Aedict Ultimate from my old phone to my new phone?  my old phone was a Galaxy note 5; new phone is a Galaxy Note 9.  

### ISSUE THREAD

**Issue by astrometab** [mvysny/aedict#845]
### Thank you for making the time to report a bug and make Aedict better!

Thank you for your interest in Aedict. Prior submitting bugs, please make sure that you have newest Aedict from Google Play.

A screenshot is often worth a thousand words, so please make sure to include one ;)

Please provide:
1. Your phone brand and maker
2. The exact Android version.
3. A screenshot if possible; even better, a youtube video demonstrating the issue.
4. A full description of the issue you're experiencing. For example: I used to read manga with the MangaReader Android app, while having the Aedict Reader popup floating. I could click the Reader window, select word search and type in the word to look up. Now the virtual keyboard doesn't pop up. You suck :-D
: I moved from

**Comment by mvysny** [comment]
The Aedict Ultimate subscription is tied to your Google Play account, and is automatically activated on all phones with that account active. So all you need to do is to add your Google account to your new Galaxy Note 9 phone - the Ultimate subscription should be activated automatically. You can verify whether the Aedict Ultimate is active, either via Google Play / Subscriptions, or in Aedict / Settings / Aedict Ultimate.

**Comment by mvysny** [comment]
Closing, please reopen if the Aedict Ultimate has not been activated on your phone automatically.

**Comment by astrometab** [comment]
Thank you!

I changed Google play accounts when I moved to new phone.  If I add old Google-play account back, will it sync my notepad entries from the old phone?

BTW: This is worth more to me than the subscription fee:  How can I donate a bit more?

Ken

**Comment by mvysny** [comment]
Hi Ken, unfortunately the data will not be synced automatically. However, I'm working on a sync system that will allow you to sync your data across all of your devices. The sync will not be connected to your Google Play account - it will either sync to aedict-online.eu or to your own server (for increased privacy). I'll post a blog when there's more info.

Regarding a donation: that is very kind of you, thank you very much! For one-time donation you can send money to my Paypal account at martin@vysny.me; if you are thinking repeated donations perhaps I can add additional subscription just for that purpose. Just let me know what kind of donation would seem fair, e.g. 1 eur per month.
