### ISSUE TITLE
My notepad notes have mysteriously disappeared

### ISSUE THREAD

**Issue by Errol246** [mvysny/aedict#847]
Hello,

For the last year or more I have religiously been using the notepad function to add words that I discover here and there in books, games and TV-shows. The feature was incredibly useful, because I could always go back to them and mass export a lot of words pertaining to each work into Anki and learn them all, making reading the book/playing the game/watching the TV-show or movie a lot easier.

Yet, recently all of my notepad notes have mysteriously disappeared and I have not manually gone in and deleted them. They first disappeared from the Android app but still existed in cyberspace, cause I was able to find them in Aedict online. I just never did anything about it back then cause I didn't have time. Now when I went to Aedict to see if they were still there I discovered to my horror that they are all completely gone, vanished. That's more than a year's worth of vocab just gone in an instant, except for the words I learned in Anki, of course. I am devastated.

My Aedict username is TakeTori. Is there anything that can be done to retrieve my lost notes, or is the creator of the app able to check in the database under my username to see if they still exist somewhere? I am logged in on the app and on Online, and I have tried reinstalling the app and changing my password and everything, but to no avail. Any help would be hugely appreciated.

![untitled](https://user-images.githubusercontent.com/16990252/46096689-1f6e3d00-c1c0-11e8-9c79-a3cd7561e0bc.png)

![42532133_480019779164222_3520956542209753088_n](https://user-images.githubusercontent.com/16990252/46096550-c900fe80-c1bf-11e8-9353-3861b6d57a81.jpg)

**Comment by mvysny** [comment]
I'll try to bring your data into Aedict Online tomorrow. It will not be synced into your devices yet, but you will at least be able to see your data in the web.

**Comment by Errol246** [comment]
Thank you very much. I will wait patiently.

**Comment by mvysny** [comment]
Hi @Errol246 can you please try logging into Aedict Online and verify that your data is there?

**Comment by Errol246** [comment]
@mvysny All my notepads are back on Aedict online but are still missing from the app. I'm relieved to see that they haven't disappeared for good. I assume my notepads will reappear once you update the database on the app?

**Comment by mvysny** [comment]
Aedict 3.50.6 has now been released. All you need to do is:
1. Upgrade :)
2. Go to `Settings / Expert Settings / Storage Type` and select `UMN`
3. (Optional) Go to `Settings / Expert Settings / Nuke User Data` and select that. That way, you will make sure there is no data cruft on your phone and all of your data will be exactly as it is on Aedict Online
4. Go to `Settings / User Data / Aedict Online Settings` and fill in your AO username and password, then check "Synchronize with Aedict Online"
5. After that's done, please wait a bit to have your data synchronized to your phone.

**Comment by Errol246** [comment]
Thanks so much!
