### ISSUE TITLE
Reader: save an analysis for later without having to wait for it to reanalyze when working with large texts.

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#852]
Analyzing large texts take lots of time and CPU. Maybe we could save an analysis for later without having to wait for it to reanalyze when working with large texts.

I'm thinking of adding a "Save" button into the Reader activity, which would save the text. I wonder if we need some kind of naming, to identify the saved texts, or a save date/time + preview of the text would be enough. I wonder where in the UI we could then show the list of analyzed texts. I'm thinking an Action Button in the upper-right portion of the Reader Welcome screen (the one with the browser showing JP wiki page)?

**Comment by jsilvermist** [comment]
I feel like a save date/time + preview would be fine, maybe also something like a char count or some simple data like that to just add a bit easier identification. Some kind of (optional?) naming couldn't hurt if it's easy to fit into a simple UI, but I'm not sure how necessary it would be if it would add a lot more complexity.

**Comment by mvysny** [comment]
Implemented in Reader 1.4.5.

**Comment by jsilvermist** [comment]
Awesome! Thanks!!!
