### ISSUE TITLE
Self Test results in Dark Theme mode are black

### ISSUE THREAD

**Issue by rbleuse** [mvysny/aedict#855]
The Run Self Test results are not well displayed in Dark mode theme

![screenshot_20190112-180316](https://user-images.githubusercontent.com/626863/51071463-8e4ea380-1694-11e9-8ee6-52e89a7e48eb.png)

Google Pixel 2
Android 9

**Comment by mvysny** [comment]
Thank you! Fixed in Aedict 3.50.20
