### ISSUE TITLE
Adjective inflection search

### ISSUE THREAD

**Issue by Spanja** [mvysny/aedict#857]
I don't find the results of the adjective 詰らない (つまらない) with negative form.

I can find 詰らない :
![screenshot_20190125-195448](https://user-images.githubusercontent.com/626863/51741863-62431180-20db-11e9-9548-4ab88e247603.png)

with its negative inflection :
![screenshot_20190125-195047](https://user-images.githubusercontent.com/626863/51742383-f19cf480-20dc-11e9-8671-8809334148f7.png)

I can't search its negative inflection 詰らなくない (つまらなくない).
If i'm searching with hiragana, I get 詰まる as a result :
![screenshot_20190125-201017](https://user-images.githubusercontent.com/626863/51742598-91f31900-20dd-11e9-8a47-c4c2cee0b2e2.png)

And If i'm searching with kanji, I get 詰る (なじる) :
![screenshot_20190125-195210](https://user-images.githubusercontent.com/626863/51742617-a7684300-20dd-11e9-93e7-58292f6906f5.png)

Pixel 2
Android 9
Aedict 3.50.10
French dictionary

**Comment by mvysny** [comment]
Thanks! Yes, there is a bug in deinflector that it doesn't stop at つまらない but thinks it's a verb and goes on to tsumaru or even further. I have to fix the matching engine so that it recognizes adjectives in cooperation with JMDict... tough

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.11
