### ISSUE TITLE
[QUESTION] Text link with search term to open in Aedict

### ISSUE THREAD

**Issue by ckaden** [mvysny/aedict#858]
Hey there,

I would like to ask if there's a syntax available to create text link which will open directly in Aedict with a search term (on Android smartphones, of course).

Background:
I started to use Anki again, as I noticed how great of a combo Aedict and Anki are. When changing from Anki to Aedict, it's normally to check up additionally information about the specific card vocable. The quicker the app change the better. Currently it's already possible by marking the word, hit on 'share' and choose Aedict. The problem is, it takes quite a lot of steps and especially on slower(?) smartphones, the unasked for feature called 'direct share' adds a really annoying delay (-> https://www.xda-developers.com/remove-direct-share-share-menu-root/ ).

So, a text link like 'app:aedict=[search term]' (totally random markup) that I can built into Anki cards would be really appreciated for a quick look up.

Changing back from Aedict to Anki is a no brainer, simply hitting square twice.

Thanks!

**Comment by mvysny** [comment]
According to https://developer.android.com/guide/topics/manifest/data-element Aedict can only respond to links such as `aedict://search%20term`, for example `aedict://はは`. I need to investigate the following:
* I guess the search string will be passed in as the 'host' parameter perhaps
* How are the whitespaces handled? I guess `%20` but this needs to be examined.

The search query might be passable also as the query part of the URL spec: e.g. `aedict://a?q=はは` - this form will be necessary if the `host` part can't handle `%20` or spaces.

**Comment by mvysny** [comment]
A couple of example testing links (these should work also from the browser when Aedict will pick up this functionality):
* [aedict://はは](aedict://はは)
* [aedict://はは%20は](aedict://はは%20は)
* [aedict://a?q=はは%20](aedict://a?q=はは%20)

**Comment by mvysny** [comment]
Implemented in Aedict 3.50.11

**Comment by ckaden** [comment]
I've received the update finally a few days and it works really great!

When using it with whole sentences, though, I noticed that my data set uses html tags to emphasize the vocable and sadly, this breaks the search in Aedict.

If you could make an update which filters the html tags out that would be really appreciated, thanks.

![screenshot_20190304-192016](https://user-images.githubusercontent.com/38889357/53754084-302f8700-3eb3-11e9-996a-1dd0a321b1ac.png)

![screenshot_20190304-191922](https://user-images.githubusercontent.com/38889357/53754089-332a7780-3eb3-11e9-9939-28f7e6a49080.png)

**Comment by mvysny** [comment]
Hi, thanks for the idea! Could you please open a new bug report regarding this idea, and describe in more detail where exactly should aedict attempt to remove the html formatting? Thanks!
