### ISSUE TITLE
[Exact search] search returns more results than expected

### ISSUE THREAD

**Issue by Spanja** [mvysny/aedict#864]
When I search 吸う (すう, to smoke), I get some extra results :

![screenshot_20190221-072335](https://user-images.githubusercontent.com/626863/53137853-abe22780-35c7-11e9-8453-1701246ad9e3.png)

**Comment by mvysny** [comment]
Yes, that's the current limitation of the search technology I'm using. Yet let me see what I can do. I was thinking about post-filtering the results, but that could be dangerous, e.g. it could filter out 見た目 when searching for 見ため. I need to be careful.

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.11
