### ISSUE TITLE
[BUG] HTML tags break sentence analysis

### ISSUE THREAD

**Issue by ckaden** [mvysny/aedict#867]
When sending a text string with HTML tags to Aedict (in this case, via an aedict:// link), it seems like the first closing tag </ breaks the continuation of the sentence analysis.

Solution: strip the text string of all tags ( like `<?></?>` ) in Aedict that might break the sentence analysis before letting the sentence being handled by the sentence analysis.

Addition: Anki uses square brackets [ ] to add readings to Kanji. Maybe these should be stripped too as this isn't necessary and might clutter up the result page with additional hiragana meanings.

Example: data field 'expression' send to Aedict from Anki (Android App) via aedict:// link, where it breaks with the closing </b> tag.

![screenshot_20190304-191922](https://user-images.githubusercontent.com/38889357/53754089-332a7780-3eb3-11e9-9939-28f7e6a49080.png)

![screenshot_20190304-192016](https://user-images.githubusercontent.com/38889357/53754084-302f8700-3eb3-11e9-996a-1dd0a321b1ac.png)

**Comment by mvysny** [comment]
Thanks! Could you please post an example of such `aedict://` link?

**Comment by ckaden** [comment]
I'm using the anki template tags, so the links looks like that:

`aedict://{{Expression}}`

The actual link send to Aedict in this example should should be as follow:

`aedict://<b>会計</b>を済ませて店を出たんだ。`

**Comment by mvysny** [comment]
Let me try also http://aedict?q=<b>会計</b>を済ませて店を出たんだ。

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.13. However, since the `<>` characters could be also used for formatting of text, e.g. `<<yamero>>` which needs to be searched properly, I'll hide this behind a setting. You will need to activate the removal of HTML elements, by going into `Settings / GUI Tuning / Search / Remove HTML Tags` and make sure it's checked.

**Comment by ckaden** [comment]
Nice, thank you! Looking forward to receiving the update.

I don't know how it looks like from a developer perspective, but with regex you can match structures like `<*>*</*>` (structure with opening and closing tag) and remove only the tags while not matching things like `<<*>>` (lone structure). HTML structures like `<*>*</*>` make absolutely zero sense for sentence analysis and thus can be removed completely. The option you've built in now makes sense for square brackets though.

But maybe it's simply not worth the hassle and depends on the user scenario. Thanks again for your work!

**Comment by mvysny** [comment]
> with regex you can match structures like <*>*</*> (structure with opening and closing tag) and remove only the tags

True, but that wouldn't remove HTML4 with unclosed tags like `foo<p>bar`, or partially copied html like `<b>something`. Therefore I chose to remove anything that looks like `<*>` or `</*>` or `<*/>` with regexp matching. That kind of matching will however turn `<<foo>>` into `<>` (by removing inner `<foo>`).

**Comment by ckaden** [comment]
Maybe we're overthinking it a bit. When I look back at the problem, the sentence analysis seems to break with the closing tag, so I suspect the slash / to be the culprit. The opening tags or tags without slash seem to be ignored. Maybe it's enough to just filter out the slash? There will be some clutter because of the tag content but that shouldn't be a huge problem.

**Comment by mvysny** [comment]
With HTML stripping turned off Aedict should work as before, and should not truncate anything. Therefore I'm judging that the original link is incorrect or truncated in the first place. Maybe try escaping characters with `%`, e.g. `<` -> `%3C`. See https://www.w3schools.com/tags/ref_urlencode.asp for more details on what kind of characters may appear in the link (hint: pretty much only a-z, so no kanjis, no </> etc).

**Comment by ckaden** [comment]
Ah sorry, you're certainly right, it already gets truncated before arriving at the sentence analysis. I just tested it with copying a sentence and directly pasting it into Aedict with html tags, no problems. My bad, didn't think of that possibility. Doesn't make it easier to resolve, sadly.
