### ISSUE TITLE
Can't Sync notepad on Aedict 3.50.12

### ISSUE THREAD

**Issue by Tinz1974** [mvysny/aedict#868]
Hi Martin
As I informed since I updated to 3.50.12 on my 2 phones android (Huawei Y9 2019 android 8.0and Huawei Mate 20X android 9.0), I can't sync my notepad.
But the recently viewed is same. 
I'm a subscribed member.
Any help.

**Comment by mvysny** [comment]
Thank you for letting me know, and I am very sorry for the trouble caused. From what you write it looks like the sync partially works - it syncs the "recently viewed" but not the "notepad". Could you please verify this?

**Comment by Tinz1974** [comment]
Yes, it partiality sync as you said. 
I made tag on Y9 2019 and it appeared on Mate 20X.
The "recently viewed" with tag is same on both phone.
Only notepad is still not.

**Comment by mvysny** [comment]
Looks like a temporary glitch in the synchronization. Could you try to create a new notepad category and add a couple of entries there, whether that will sync or not please?

**Comment by Tinz1974** [comment]
The new up date 3.50.13 solved syncing problem.
Thank you so much for quick response.

**Comment by mvysny** [comment]
That's great to hear, thanks for letting me know! Closing as fixed.
