### ISSUE TITLE
Study notes for notepad entry

### ISSUE THREAD

**Issue by peterjkane** [mvysny/aedict#881]
Can study notes be added for entries in the notepads?
Maybe this is there already.
Eg adding my own sample sentence, or external references?

**Comment by mvysny** [comment]
Sure - you can attach a tag to any entry. The tag can contain any text you wish. Just long-touch any entry and choose "tag entry"

**Comment by peterjkane** [comment]
Thanks. I'll start to use that. Excellent app, one of my favourites. Thanks for the effort. I'm a subscriber.

**Comment by mvysny** [comment]
Thank you very much for your support and for your praise :)
