### ISSUE TITLE
Strip spaces from selections

### ISSUE THREAD

**Issue by Fandekasp** [mvysny/aedict#884]
Can you strip all spaces from selections before the search? When selecting a word like 面会, instead of searching for that jukugo, it will only search for 面 and 会 at the moment

![Screenshot_20190817-111444](https://user-images.githubusercontent.com/260983/63205518-628b1480-c0e0-11e9-95b8-4aa38e78aad5.png)

What I would be most grateful about is seeing the word frequency rating from the Aedict reader popup :heart:

**Comment by mvysny** [comment]
Testing text: 面 会

**Comment by mvysny** [comment]
Thanks! Fixed in 1.4.8.

> seeing the word frequency rating from the Aedict reader popup

Could you open a new feature request with more details on what you have in mind please?
