### ISSUE TITLE
[question] How it's the tag "common" set?

### ISSUE THREAD

**Issue by Fandekasp** [mvysny/aedict#885]
Some jukugo like 時機 do not appear to be common, yet have the tag common associated.
Can you explain the algorithm behind the tag?

![Screenshot_20190819-074319](https://user-images.githubusercontent.com/260983/63231363-7c019d00-c255-11e9-92f9-ae8eb9b713f6.png)

**Comment by mvysny** [comment]
The "Common" flag doesn't take Kamermans nor Matsushita into consideration, instead it relies on the definition of "common" from Jim Breen's JMDict:

> The entries with news1, ichi1, spec1, spec2 and gai1 values are marked with a "(P)" (common).
