### ISSUE TITLE
I can't hear the pronunciation sounds files.

### ISSUE THREAD

**Issue by astrometab** [mvysny/aedict#894]
### Thank you for making the time to report a bug and make Aedict better!

Thank you for your interest in Aedict. Prior submitting bugs, please make sure that you have newest Aedict from Google Play.

A screenshot is often worth a thousand words, so please make sure to include one ;)

Please provide:
1. Your phone brand and maker
2. The exact Android version.
3. A screenshot if possible; even better, a youtube video demonstrating the issue.
4. A full description of the issue you're experiencing. For example: I used to read manga with the MangaReader Android app, while having the Aedict Reader popup floating. I could click the Reader window, select word search and type in the word to look up. Now the virtual keyboard doesn't pop up. You suck :-D

**Comment by mvysny** [comment]
Could you please share in more detail what exactly isn't working?

**Comment by astrometab** [comment]
When I click the icon to listen to the pronunciation of a word, I see the message "speaking" but I can't hear anything. I raised all volume levels to max. The speech to text isn't working. I can't find any settings to adjust.

**Comment by astrometab** [comment]
I am using a Galaxy Note 9, latest Android version.

**Comment by mvysny** [comment]
The Text-to-speech (TTS) Android API is horribly broken, and it won't let us know even if there is an error.

Please find more in the Aedict FAQ, just search for TTS: http://www.aedict.eu/faq.html

You should make sure that you have a TTS engine configured in your phone. On my phone it's in the Phone Settings / System / Languages & Input / Advanced / Text-to-speech output. Please try to play an example TTS output, make sure that you have "Google Text-to-speech Engine" selected, and please try various combination of settings until the phone is able to synthesize speech. Also make sure that your phone is not muted, and you have support for Japanese language in your phone.

**Comment by astrometab** [comment]
I still can't get audio to work in Aedict. However, I have a different app for Japanese learning and nihingo audio is working so the problem may require a modification to Aedict.

**Comment by astrometab** [comment]
Still not working

**Comment by mvysny** [comment]
It could be that the different Japanese app is not using TTS but rather has access to pre-recorded audio files of the lessons or sentences. Could you please find your text-to-speech settings in Android settings and try making the phone say something in Japanese?

**Comment by astrometab** [comment]
Thanks for your reminder Martin: I had tried "everything" and given up.

I just loaded the app without changing any android settings.  Some
"dictionary" files automatically updated. I then tested the text-to-speech
and it is working now.

Hope that is useful for you, I don't know why but now, after at least 6-8
weeks, it is working again.

Best wishes,

Ken

=======================================

*Kenneth J. Storch, MD, PhD, IFMCP, FACP, FACN*

Advanced Metabolic & Functional Medicine Center
Storch Nutritional Medicine Associates, P.A.
147 Columbia Turnpike, Suite 308
Florham Park, NJ 07932
www.amfmcenter.com <http://www.storchnutrition.com/>
973-765-9355
=======================================

**Comment by mvysny** [comment]
Huh, that is weird. The Aedict dictionary files certainly do not store any audio files. Perhaps the phone was rebooted which fixed the TTS, or a permission changed, or there was some other "invisible" change that triggered the fix...

Regardless, I'm happy that the TTS works for you :+1:

Closing this as fixed.
