### ISSUE TITLE
匂 not found with Kanji search when written.

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#898]
I am using the latest version of AEDict from Google Play on an Android Tablet version 8.

I noticed that if I search for 匂 in AEDICT using Kanji search feature using hand writing, AEDICT will not display the Kanji in the choices, even though the stroke count and stroke order appear to be correct.   If I search using radicals the Kanji is located fine.

I should note that if I write the Kanji with correct stroke order and count using Google's Handwriting Keyboard the Kanji is also listed correctly.

![Screenshot_20191113-130518-01](https://user-images.githubusercontent.com/19387982/68766865-95797180-0617-11ea-858f-9963bd85f44c.jpeg)

**Comment by terrywallwork** [comment]
Also I am not sure if this is helpful or not but I did a Quick test using the JiShop app for the Kanji and it was also located fine using hand writing in its app.

![Screenshot_20191113-132224](https://user-images.githubusercontent.com/19387982/68767662-f35a8900-0618-11ea-8a82-ef65457b9ef7.png)

**Comment by mvysny** [comment]
Interesting, thank you for letting me know. The stroke order diagram for 匂 is available in Aedict, which means that the kanji should be recognized with the kanjipad. On my phone it works properly, please find the screenshot attached.

![Screenshot_20191113-154444](https://user-images.githubusercontent.com/254091/68769257-aaaccb00-062c-11ea-952f-c65930a1ab26.png)

Let me try in the tablet as well.

**Comment by mvysny** [comment]
The free Aedict uses a free kanjipad which isn't as accurate as the one used in Aedict Ultimate.

**Comment by terrywallwork** [comment]
Don't know if it matters but as far as I know it is the non-free version of AEDict I was using I have the paid version of Kanjpad also.

**Comment by mvysny** [comment]
In such case the paid Kanjipad should be used. Please let me investigate.

**Comment by terrywallwork** [comment]
Also I could be misremembering but wasn't there an option in AEDict that I had to set to use External KanjiPad extension?  I can't find the option now.  Though KanjiPad Extension is showed as installed.  Am I using the correct version?

![Screenshot_20191113-152810](https://user-images.githubusercontent.com/19387982/68777941-57d21400-062a-11ea-8ab1-abb4c3123173.png)

**Comment by mvysny** [comment]
Hi, yup, you're using the correct version. There has been a change in Aedict 3 with regarding to Aedict Ultimate, and probably the Kanjipad detection code got broken. There was a possibility to use the External KanjiPad, but it has been found that the External kanjipad is far superior to the free one, and Aedict should use the better one if you have KanjiPad Extension installed or Aedict Ultimate purchased. Sounds like a bug in Aedict, please let me investigate.

**Comment by mvysny** [comment]
Yeah, Aedict wouldn't accidentally use KanjiPad Ext when you have it installed. Fixed in Aedict 3.50.16.
