### ISSUE TITLE
Irregulor Verb/Inflection indication. - Feature Request.

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#899]
I have a feature request with regard to Irregular Verbs/Adjectives/Etc.

It would be useful if irregular Verbs/Adjective were indicated as such in the Inflection list, and maybe also on the word screen for the Irrgular Verb/Adjective, maybe with their own tag.

For example 行く inflects irregularly in te-form.  So a visual indication for the Inflection entry that is none standard would be helpful.  Either something like a change or colour or an asterisk etc.

I am guessing that there is no automatic way of recognising words that are irregular from the Dictionary files you use, but I know you keep track of some irrgular verbs.  So it would still be useful for the ones you know about.

I know there are lists of most Irregular Japanese verbs, so may be worth investigation.  I know J Breen has one but I can't say how complete it is.

**Comment by mvysny** [comment]
Hi, thank you for letting me know! Actually there are the following tags which mark irregular inflection:

* "godan iku/yuku": Godan verb - Iku/Yuku special class: there are quite a lot of those: https://www.japandict.com/lists/v5k-s
* Godan verb with `ru' ending (irregular verb)
* Godan verb with `u' ending (special class)
* Godan verb - Uru old class verb (old form of Eru)
* Godan verb - -aru special class
* Kuru verb - special class
* suru verb - special class

And possibly more. So looking out for those tags will give you the information about irregular inflection.

That being said, I can of course mark such words with a special "Irregular" tag. What do you think?

**Comment by terrywallwork** [comment]
Oops, sorry you are right.I never realized that they indicated irregular inflections.So I guess my request is not need.Though I wonder if maybe other people got confused like me.　Maybe worth adding a specfic irregular tag, or making it more obvious that the tags that do exist are irregular in meaning.

**Comment by mvysny** [comment]
No problem. You're right - having an explicit "Irregular" tag would make things much more clear. I'll implement this.

**Comment by mvysny** [comment]
The new implementation explicitly adds a new badge "Irregular" if the verb is in any of the abovementioned class, please see screenshot for details.

![Screenshot_20191214-142111](https://user-images.githubusercontent.com/254091/70848640-6441ca80-1e7d-11ea-8d01-f71e593f8a26.png)

Closing as fixed, please feel free to comment if the badge is applied incorrectly.

Fixed in Aedict 3.50.17
