### ISSUE TITLE
Possible Typo in External Dictionaries Notification

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#901]
I am not certain but I think the notification display for the external dictionaries selection screen is incorrect.

When I select an external dictionary entry so that it has a tick mark shown, the notification shown at the bottom of the screen says the dictionary will not be shown.

However if I deselect an entry so that it does not have a tick mark shown, the notification says the dictictionary will be shown?

Sorry if this is intended behaviour and I am misunderstanding.

See screenshot for the screen I am refering to.

![Screenshot_20191213-101658](https://user-images.githubusercontent.com/19387982/70793153-9e826d80-1d92-11ea-99f3-24294294cfde.png)

**Comment by mvysny** [comment]
Ouch, thank you for pointing this out :-D The notification is incorrect - when the dictionary is checked then it will be shown in the list of external dictionaries. Let me fix this.

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.17
