### ISSUE TITLE
Possible Kanji Stroke Count vs Sod Count Mismatch?

### ISSUE THREAD

**Issue by terrywallwork** [mvysny/aedict#909]
HI,

I have and Android 8 tablet.  Running the latest paid version of AEDict from the Google Play Store.

I noticed what seems to be a mismatch between the Eat Food (Radical 184) Stroke Count 9 and it's SOD picture count of 8.  See attached screenshot.

As far as I can tell it is supposted to be 8 strokes as shown by the SOD.

This is the radical:
飠 []: eat, food, radical number 184

![Screenshot_20200211-080927](https://user-images.githubusercontent.com/19387982/74220135-ac774080-4ca6-11ea-8ee3-93c1f0104243.png)

**Comment by mvysny** [comment]
This is a good question. The kanjidic2.xml.gz (downloadable at http://www.edrdg.org/wiki/index.php/KANJIDIC_Project ) says <stroke_count>9</stroke_count>. However, please notice that 食 and 飠 look a bit different when zoomed in. I wonder if 食 the kanji should be drawn exactly as 飠 the radical - if yes, then the SOD data at https://kanjivg.tagaini.net/ needs to be fixed. Do you perhaps have an authority of Japanese language whom we can ask, or should I ask Jim Breen directly?

**Comment by terrywallwork** [comment]
I would ask J Breen, if he doesnt know, chances are he knows someone who does?

**Comment by terrywallwork** [comment]
On the question of 食 it is definitely 9 strokes according to jishop.
![Screenshot_20200212-105149](https://user-images.githubusercontent.com/19387982/74328471-e4a18080-4d85-11ea-9126-42049323a7d3.png)

**Comment by terrywallwork** [comment]
I did a radical search in jishop for 飠and it is not listed but 食 is.

**Comment by terrywallwork** [comment]
Did a search in Chase Colburns kanji study with his kanji history\explainer addon.  Looks like your right.
![Screenshot_20200212-110244](https://user-images.githubusercontent.com/19387982/74329301-72ca3680-4d87-11ea-8299-d84df0ddc4b9.png)

**Comment by terrywallwork** [comment]
success!
https://www.youtube.com/watch?v=r2XK1KABdBU

Japanese pod video.  Explains both types of kanji and shows stroke orders 

for 飠 is 8 strokes

**Comment by mvysny** [comment]
Excellent catch! It thus seems that the Kanjidic2 needs to be corrected: the 飠 needs to have 8 strokes instead of 9. Let me re-check and notify Jim Breen.

**Comment by mvysny** [comment]
Yup, Kanjidic2 says 飠 has 9 strokes. I've sent an email to Jim, let's wait for his decision.

**Comment by mvysny** [comment]
Jim replied quickly:

> Yes,  飠 is 8 strokes, I have corrected the kanjidic master
file so that correction should turn up soon.

> The data for those JIS X 0213 kanji came initially from the
UniHan file, so that's probably the source of the error. The
count is correct in the current UniHan data. See:
https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E9%A3%A0

The data in Aedict will be corrected upon next update of the kanjidic data, which should happen 1st of next month.

Thanks for reporting this issue, and have a nice day :)
