### ISSUE TITLE
Pre-Fill Omnisearch from clipboard not working

### ISSUE THREAD

**Issue by jakyo-dev** [mvysny/aedict#915]
Currently following setting doesn't seem to work:
GUI Tuning -> Search -> Pre-fill Omnisearch -> [Clipboard] Pre-fill with clipboard or previous search

When switching to Aedict, the search field is always empty. No previous search and no clipboard content is taken over. Tested with copy to clipboard content from Chrome Browser, Google Lens and more.

Phone: OnePlus 6T
Android version: 10

**Comment by mvysny** [comment]
Unfortunately Android 10 forbids all apps access to the clipboard, for security reasons. So this feature will no longer work starting from Android 10. I should probably display a warning in Aedict, or disable the configuration option altogether, or similar.

**Comment by jakyo-dev** [comment]
Oh, that's seriously a bummer. Please go with the warning, who knows if Google will add this functionality back again.

**Comment by mvysny** [comment]
Sounds good! I'll display a notification toast when Aedict code tries to read the clipboard on Android 10+.

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.18
