### ISSUE TITLE
Donations/Funding

### ISSUE THREAD

**Issue by topherbuckley** [mvysny/aedict#916]
I apologize if a github issue is the wrong place to put this, but I wasn't finding any other form of contact. 

I don't know if I've had my head under a rock for the past few years or what, but I was completely unaware of your patreon until now (which unfortunately appears to be closed now). I am always quick to purchase whatever add-ons you publish, and just signed up for Aedict Ultimate (also just realized it existed) without the need to really use any of its features. I've been learning Japanese for 6 or 7 years and use your app almost daily. I would like to donate further in some way above the low price for Ultimate. Is there a reason you closed your patreon or is there some other way I can support your efforts?

**Comment by mvysny** [comment]
Thank you so much for using Aedict for so long, I'm really happy that Aedict provided value for you for such a long time :) And thank you so much for your kind support through the purchases, it wouldn't be possible to develop Aedict further without your support.

The problem with Patreon was that I was unable to come up with rewards that were interesting enough for higher tiers. I also realized at some point that it was unfair or the dear Patreon supporters to fund the Aedict development single-handedly, and it was also not a sustainable model. I think that the new subscription model is more fair towards everyone.

Please read more thoughts on this topic here: https://mvysny.github.io/aedict-blog/Aedict-Ultimate/

If you would like to donate towards Aedict development, please feel free to send any amount you deem fair towards my PayPal account martin@vysny.me.

Thank you so much again for your kind support :)

**Comment by topherbuckley** [comment]
Okidoki. Yeah, I read the reasoning, and understood the change to the subscription model, but I still thought having an open Patreon might help raise further funds, making sure to explicitly write your reasoning on the Patreon page and keeping all Patreon contributions as donations only (no reward tiers) to avoid anyone unknowingly paying in both places. I like paying small monthly payments to things I support like that, but regardless, I'm happy to know you have a PayPal account. I know its not much in the scheme of things, but I just sent over the average price of a Denshi-jisho on Amazon. Thanks again for all your efforts!

**Comment by mvysny** [comment]
Thank you so much, that is very generous of you 🙏 I will put your donation to a good use, this will pay for at least a year and a half of hosting of aedict online and the web page. Thank you again, and best of luck with your Japanese studies :)
