### ISSUE TITLE
[Inflection] Incorrect potential form

### ISSUE THREAD

**Issue by rbleuse** [mvysny/aedict#918]
Hi Martin,
the potential form of some ichidan verbs are incorrect.

example 止める :
aedict : 止めれる
it should be 止められる (source : http://www.japaneseverbconjugator.com/VerbDetails.asp?txtVerb=TOMERU or https://bondlingo.tv/conjugation/result/tomeru)

Same for 覚える, 教える, ...

Android 10, Aedict 3.50.17

**Comment by rbleuse** [comment]
This has been fixed with https://gitlab.com/mvysny/jputils/-/merge_requests/3

**Comment by mvysny** [comment]
Perfect, in such case the fix is present in Aedict 3.50.22.
