### ISSUE TITLE
Merge Notepad category option

### ISSUE THREAD

**Issue by Julianbrook1** [mvysny/aedict#921]
I was wondering if there's a way to merge different Notepad categories, in order to streamline category organization? A "Merge with category" option would certainly be helpful (ie in addition to "move after" after option -> "merge with"). Thanks.

**Comment by mvysny** [comment]
Hi, If I understand correctly, the "merge with" would in effect do the same thing as if you selected all entries from a single category, moved them into another category, then delete this (now empty) category?

**Comment by Julianbrook1** [comment]
Oh, I just noticed the "move to category" option after highlighting
selections. I initially tried a straightforward copy and paste, but
couldn't find a paste option, so I was confused. My bad! Still, having the
merge option available in the normal notepad category drop-down menus as I
mentioned would make it more accessible and obvious.

Thanks for the reply,

Julian

**Comment by mvysny** [comment]
No problem :) Android clipboard is limited in size; therefore copying entries with lots of internal structure and data (tags, translations for different languages etc) would quickly overflow the internal clipboard capacity - that's why Aedict doesn't generally support copy+paste of entries.

Still, "merge with category" would make sense. Thanks!

**Comment by mvysny** [comment]
Implemented in Aedict 3.50.18

**Comment by Julianbrook1** [comment]
Awesome! Thanks so much for considering my request. It's always refreshing
to connect with responsive developpers.

Also, thank you for providing Aedict, which has been an absolutely
indispensable tool for my Japanese learning. Enjoy the rest your summer
there.

Cheers,

Julian

**Comment by mvysny** [comment]
Thank you so much, I'm happy that Aedict was helpful to you :+1: Thank you, and enjoy the rest of the summer as well :)
