### ISSUE TITLE
Verb inflection search

### ISSUE THREAD

**Issue by rbleuse** [mvysny/aedict#922]
Hi Martin, I was searching for 見つかった (見つかる, to be found), but Aedict can't find that entry :

![Screenshot_20200718-131253](https://user-images.githubusercontent.com/626863/87851391-865e6800-c8f8-11ea-9f15-da16177df26e.png)

Aedict 3.50.17, latest french dictionaries

**Comment by topherbuckley** [comment]
Interesting. I tested a few more verbs looking for a pattern, but didn't seem to find any. Is there any way we can programmatically test this? I was thinking to filter all v5r verbs, take their Informal Past inflection, and search each, and add the verb to some List object if the search results do not include the original verb. 

(v5r)
見つかった	-> Not identified
助かった	-> Not identified
始まった	-> Correctly identified
閉まった	-> Correctly identified
送った		-> Correctly identified
入った		-> Correctly identified

(v5k)
聞いた		-> Correctly identified

(v1)
助けた		-> Correctly identified
見つけた	-> Correctly identified
入れた		-> Correctly identified
聞こえた	-> Correctly identified
食べた (correct) and 食べった (incorrect)-> Correctly identified

**Comment by mvysny** [comment]
Hi,good catch! On the first sight it looks like the deinflector engine doesn't catch/deinflect the -karu verbs. Let me investigate :)

**Comment by mvysny** [comment]
Yup, there was a bug in the deinflector code. Fixed in Aedict 3.50.18.
