### ISSUE TITLE
Masu form with kanjis not found

### ISSUE THREAD

**Issue by rbleuse** [mvysny/aedict#923]
Hi Martin,

looking for the verb できます in hiragana is ok whereas 出来ます is not found.
BTW 出来る is OK

<img src="https://user-images.githubusercontent.com/626863/89119694-ad986600-d4b0-11ea-9fcb-d9c5065c9cf9.png" width=300><img src="https://user-images.githubusercontent.com/626863/89119695-aec99300-d4b0-11ea-87b0-bbf61d7484e1.png" width=300>
<img src="https://user-images.githubusercontent.com/626863/89119696-affac000-d4b0-11ea-875f-3187416a7d7f.png" width=300>

**Comment by mvysny** [comment]
Yup, it's a limitation in the deinflector engine: it currently cannot handle when there's [kanji] + ます. Let me try to check whether I can do something with this.

**Comment by mvysny** [comment]
Fixed :) The fix will be present in Aedict 3.50.18.

**Comment by rbleuse** [comment]
Hi Martin,

I don't know if it's a regression from this fix, but it's not working with 着ます (I can't find it from kana nor kanji) :

<img src="https://user-images.githubusercontent.com/626863/92638984-7a30ce80-f2db-11ea-801c-0415d70c639b.png" width="300" /><img src="https://user-images.githubusercontent.com/626863/92638954-6c7b4900-f2db-11ea-8fb1-96dae42489cf.png" width="300" />

It's working fine with 着る

**Comment by rbleuse** [comment]
Seems that 出来ます doesn't work anymore in 3.50.21 :sweat_smile:

**Comment by mvysny** [comment]
Ouch :-) . Thanks, reopening.

**Comment by rbleuse** [comment]
My bad, I flagged all ~来る verbs with vk flag, but forgot that ~出来る is v1

**Comment by mvysny** [comment]
No worries, thank you for the PR. I'll test the fix locally today

**Comment by mvysny** [comment]
Awesome fix, Aedict now properly deinflects 出来ます to 出来る. Will be fixed in Aedict 3.50.22.

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.22
