### ISSUE TITLE
Incorrect display for がぎぐげご

### ISSUE THREAD

**Issue by mwsduelle** [mvysny/aedict#924]
OnePlus 5, Android 9.0

![Screenshot_20200813-091528](https://user-images.githubusercontent.com/29561413/90159976-ff10e280-dd45-11ea-96a6-93ef15278e05.jpg)

Sometimes there is a handakuten after the dakuten in the dictionary tab. This doesn't happen in the search listing or any other screen. It seems to only happen when there are pitch accent markings for the entry. Ex: 家具(かぐ° ) but not 下愚(かぐ).

**Comment by mvysny** [comment]
Hi, that is actually a marker for a nasal sound. You can toggle the marker invisible in settings / gui / dictionary entry screen / show pitch accent and set it to "pitch" or "none"

**Comment by mwsduelle** [comment]
Ah, okay. That setting doesn't say how it will indicate the nasal sound, hence the confusion.

**Comment by mvysny** [comment]
You're right - it's easy to confuse nasal marker with handakuten. I should either change the marker or mention it in the settings.

**Comment by mvysny** [comment]
Also see https://github.com/mvysny/aedict/issues/644

**Comment by mvysny** [comment]
I can't seem to find the article which mentions ° as the nasal marker. However https://en.wikipedia.org/wiki/Nasal_consonant the Voiceless nasal markers all seem to be using °, therefore for the lack of better options, let's stick with ° for now.

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.18.

**Comment by mwsduelle** [comment]
Nasalization of a sound is represented by a tilde over the character in IPA (ex: ã). The nasalized /g/ sound in Japanese is represented with /ŋ/, though, since it's a normal nasal consonant.

**Comment by mvysny** [comment]
@mwsduelle would you therefore prefer ~ over °, as in `かぐ~` over `かぐ°`?  Alternatively I could also use `U+0303 ◌̃ COMBINING TILDE` `ぐ◌̃` but Android is notoriously bad at rendering weird Unicode characters; not even my browser renders this correctly:

ぐ̃ 

However, according to https://en.wikipedia.org/wiki/Nasal_consonant tilde is used for voiced nasals while ° is used for voiceless nasals - I wonder which one Japanese language uses? @mwsduelle could you elaborate on this please?

**Comment by mwsduelle** [comment]
Since the sound is /ŋ/, it is a voiced nasal. The tilde could work or maybe a small ŋ as a superscript.

**Comment by mvysny** [comment]
Sounds good! I'll try a superscript tilde first; or just a regular tilde if that doesn't work.

**Comment by mvysny** [comment]
I failed to find superscript tilde, I'll just use a regular tilde :+1:

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.18
