### ISSUE TITLE
Examples and text analysis issue in 3.50.18

### ISSUE THREAD

**Issue by Nabokov86** [mvysny/aedict#926]
Examples are displayed with some errors, I think. Screenshots:
![IMG_20200830_185733_510](https://user-images.githubusercontent.com/26260168/91664392-b1db9180-eaf7-11ea-965d-1e3ee374a347.jpg)
![IMG_20200830_185731_546](https://user-images.githubusercontent.com/26260168/91664396-bdc75380-eaf7-11ea-88ae-175080df36bf.jpg)

Also in text analysis something broke, too. screenshot:
![IMG_20200830_185727_016](https://user-images.githubusercontent.com/26260168/91664532-89a06280-eaf8-11ea-9981-8562b56b9a44.jpg)

In 3.50.17 everything works as it should.

Additional info:
1. Tested on various devices, and It doesn't seem to be a device-specific problem, but for exemle nexus 5.
2. Error occurs at least on android 6 and 7.

**Comment by Nabokov86** [comment]
Forgot to say, fresh install with default settings.

Also sorry for the enormous screenshots.

**Comment by mvysny** [comment]
Thank you for letting me know! Everything works good on my Android 10 phone, but I'll try the same thing with the Emulator and/or Android 6+7 devices.

The thing is that I've switched to the new FuriganaView component which fixed #704 ; however apparently the component contain some kind of issues manifesting on Android 6+7 devices.

**Comment by mvysny** [comment]
Reproduced on Android 5.1. I'll debug the issue.

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.19.
