### ISSUE TITLE
Pull-to-refresh Dictionary Manager

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#927]
A feature suggestion:

Currently, if I download additional dictionaries, I have to back out of the Dictionary Manager and go into it again if I want the newly downloaded dictionaries to appear at the top of the list with their green color indicators. It might be neat, and feel intuitive, if a "pull down" gesture would refresh the dictionary list, similarly to apps such as Gmail or Chrome, or websites like mobile.twitter.com.

**Comment by mvysny** [comment]
Thanks! Yeah, it shouldn't be that hard: https://medium.com/@houdayer.corentin/how-to-use-swipe-to-refresh-swiperefreshlayout-99abd674c907

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.19

**Comment by topherbuckley** [comment]
Your speed to fix things is always impressive! I saw the issue report and the fix in the same day of going through my notifications :D.

**Comment by mvysny** [comment]
Thank you, luckily this issue was easy to implement since Android provided exactly this functionality :)
