### ISSUE TITLE
Masu form with kanjis not found

### ISSUE THREAD

**Issue by rbleuse** [mvysny/aedict#929]
Hi Martin,

I don't know if it's a regression from this fix, but it's not working with 着ます (I can't find it from kana nor kanji) :

<img src="https://user-images.githubusercontent.com/626863/92638984-7a30ce80-f2db-11ea-801c-0415d70c639b.png" width="300" /><img src="https://user-images.githubusercontent.com/626863/92638954-6c7b4900-f2db-11ea-8fb1-96dae42489cf.png" width="300" />

It's working fine with 着る

_Originally posted by @rbleuse in https://github.com/mvysny/aedict/issues/923#issuecomment-689741871_

**Comment by mvysny** [comment]
Hi Remi, I think it's a limitation of the deinflection engine - the engine needs to have a hiragana character before `masu` to be able to deinflect it. Yet maybe I can create an exception rule, in the way similar to kuru.

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.20.

**Comment by rbleuse** [comment]
Hi @mvysny it doesn't seem to be fixed in 3.50.20 :
<img src="https://user-images.githubusercontent.com/626863/97432658-98e73500-191c-11eb-8ae0-13e078491d2b.png" width="300" />

着ます is not in results

**Comment by mvysny** [comment]
I probably only fixed the 着ます->着ru deinflection; however kimasu probably still gets deinflected to kuru. Let me take a look.

**Comment by mvysny** [comment]
Fixed in jputils 1.51

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.21.

**Comment by rbleuse** [comment]
I didn't notice before but in my last screenshot, all くる entries except 来る when looking for kimasu shouldn't be displayed (繰る is kurimasu for example).
This problem seems to be with all forms (konai, kureba, kita, ...)

I might get a fix, when looking for kimasu, deinflection results should always be 来る (with kanji) instead of くる in addition to きる.

But it seems to be tricky because looking for 来る will also display 来る (きたる) entry.
Do you have an idea @mvysny ?

**Comment by mvysny** [comment]
@rbleuse you're right. Could you please open a new bug report regarding this? I think that jputils will, upon deinflection, store an information that a certain rule (e.g. kimasu->kuru) is only applicable for Ichidan verbs (marked as "vi"); Aedict should then take this into account and only search for Ichidan verbs in such case. Probably Aedict just ignores this information.
