### ISSUE TITLE
Can't find custom fonts in Android 10

### ISSUE THREAD

**Issue by mwsduelle** [mvysny/aedict#930]
Oneplus 5, Android 10. I'm assuming this has something to do with SAF. I used to be able to open any folder when looking for fonts. The main issue now is that when I'm trying to locate fonts, there is no address telling me where I am in the filesystem. So I don't know what folder to put them in now. All I have is the "go up a level" icon. When going up 2 levels I have "emulated" and "self".

![Screenshot_20201008-152751095](https://user-images.githubusercontent.com/29561413/95519980-24ebe980-097b-11eb-9c24-e6712c75d3b6.jpg)

![Screenshot_20201008-152756308](https://user-images.githubusercontent.com/29561413/95519995-2ddcbb00-097b-11eb-9bd0-8e28ceff2d58.jpg)

**Comment by mvysny** [comment]
You're right - the font picker dialog is very counter-intuitive. I need to display the current path as a bare minimum; also I managed to go upwards by pressing `..` and now all I can see is a blank window - probably Android security prevents me from browsing the root folder or something. In such case there should always be a way to fall back and start from the root of the SD card (or whatever is browsable).

Unfortunately this kind of dialog may not be as helpful anymore - Android 10 severely limits the way you can access the SD Card.

**Comment by mwsduelle** [comment]
I was able to load the fonts by putting them in the aedict folder in /storage/emulated/0/Android, copying the path to the file, and pasting it into the text box. So it's still possible with a workaround.

**Comment by mvysny** [comment]
Thank you for letting me know.

Starting with Android 10 it's discouraged to browse the SD Card - in fact Google made it almost impossible to access the SD Card by apps: https://stackoverflow.com/questions/59465866/how-to-read-an-existing-file-from-devices-shared-storageroot-directory-in-and . It's on purpose.

Therefore I need to replace those file browsing dialogs with ACTION_OPEN_DOCUMENT and/or ACTION_OPEN_DOCUMENT_TREE; probably I should also disallow the user to pick the folder where to download the dictionaries on Android 10+ and always use the internal app folder as provided by Android.

I need to test whether font picker will work with ACTION_OPEN_DOCUMENT; if it does I will probably need to copy the font to Aedict internal folder and use it from there.

**Comment by mvysny** [comment]
Aedict 3.50.20 will use `ACTION_OPEN_DOCUMENT` on Android 10+ from now on.
