### ISSUE TITLE
Example sentence not well parsed

### ISSUE THREAD

**Issue by rbleuse** [mvysny/aedict#937]
Hi Martin,

I didn't check the tatoeba file, maybe it's a problem in the sentence structure, but it seems that sentence is not well parsed
<img src="https://user-images.githubusercontent.com/626863/98043756-0bc54400-1e26-11eb-8811-dcbe02f82c5b.png" width="300" />

**Comment by rbleuse** [comment]
From tatoeba file : `115177	288493	彼(かれ)[01] は|1 二人{２人} の 話(はなし) が 長い{長く} 成る[01]{なり} そう[01] だ と 思う{思った}`

**Comment by rbleuse** [comment]
In fact there are many sentences with that problem :

<img src="https://user-images.githubusercontent.com/626863/98086078-87eb7600-1e7e-11eb-93d8-c63275896a7a.png" width="300" />

My tatoeba is up to date to November 2nd

**Comment by mvysny** [comment]
Thank you for letting me know! However, this is actually a bug in the FuriganaView rather than the Tatoeba sentence parser - the bug is similar to #944

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.21
