### ISSUE TITLE
Back button on main screen

### ISSUE THREAD

**Issue by tobia** [mvysny/aedict#943]
It would be nice if the back button on the main screen cleared the current search and went back to the list of recent searches, instead of closing the app. Currently it closes the app.

Thank you for the great app!

Aedict 3.50.20 on OnePlus 6, Android 10

**Comment by mvysny** [comment]
Thank you for letting me know :) I've added a new configuration option for this: `Settings / GUI Tuning / Search TextBox / Clear Omnisearch on Back`.

Fixed in Aedict 3.50.21
