### ISSUE TITLE
Inflection search with ~れば form

### ISSUE THREAD

**Issue by rbleuse** [mvysny/aedict#952]
Maybe linked to #947

Hi Martin,

I was searching the entry of an ichidan verb : 出かける with the form 出かければ

The search displays incorrectly `Base 1 + nakereba : if I do not do something`, and the entry is not found whereas this inflection is in the inflections tab
<img src="https://user-images.githubusercontent.com/626863/111716750-0975fa80-889a-11eb-851b-2273b6e8fbde.jpg" width="300" />

It's working well with another ichidan verb :
<img src="https://user-images.githubusercontent.com/626863/111716787-1bf03400-889a-11eb-95c1-226daca0a377.jpg" width="300" />

**Comment by mvysny** [comment]
Excellent work fixing the deinflector @rbleuse at https://gitlab.com/mvysny/jputils/-/merge_requests/1 - thank you so much. I've released jputils 2.0 to Maven Central and v-bumped it in Aedict, which should solve this issue.

Fixed in Aedict 3.50.21.
