### ISSUE TITLE
Verb inflection search display incorrect entry results

### ISSUE THREAD

**Issue by rbleuse** [mvysny/aedict#953]
Related to #929 & #862

When a search use deinflection engine, a certain rule should be only applicable to certain type of verbs

Examples :
| kimasu search | kirimasu search | kurimasu search | shimasu search |
| --- | --- | --- | --- |
| :x: 繰る (kurimasu)<br />:x: 呉る (no inflection)<br /> | :x: 着る (kimasu) | :x: 来る (kimasu)<br />:x: 呉る (no inflection) | :x: 擦る (surimasu)<br /> :x: 剃る (sorimasu/surimasu)<br /> :x: 刷る (surimasu)<br /> :x: 掏る (surimasu) |
| <img src="https://user-images.githubusercontent.com/626863/97432658-98e73500-191c-11eb-8ae0-13e078491d2b.png" width="300" /> | <img src="https://user-images.githubusercontent.com/626863/114846764-f3ffdc00-9e17-11eb-99ad-fb5b4629902e.jpg" width="300" /> | <img src="https://user-images.githubusercontent.com/626863/114846704-e6e2ed00-9e17-11eb-8a14-e52f4aa58b20.jpg" width="300" /> | <img src="https://user-images.githubusercontent.com/626863/115208039-23278d80-a137-11eb-9ff9-8649b68dcc7c.jpg" width="300" /> |

**Comment by rbleuse** [comment]
This can be closed as it's fixed in 3.50.21

**Comment by mvysny** [comment]
Thank you for letting me know! Fixed in Aedict 3.50.21
