### ISSUE TITLE
Aedict online is down

### ISSUE THREAD

**Issue by Taketori16** [mvysny/aedict#963]
This has nothing to do with the Android version of Aedict. I know this isn't the right place for this, but I have no idea where else to report the issue.

Aedict online has been down for a few days now. I use it very very frequently. Just letting you know!

**Comment by mvysny** [comment]
> This has nothing to do with the Android version of Aedict. I know this isn't the right place for this, but I have no idea where else to report the issue.

Not a problem. When Aedict Online is down, please feel free to reach me in any way ASAP. This is the easiest way, and the one which is guaranteed to reach me. Please continue doing so also in the future - if Aedict-Online happens to be ... offline :-D, simply open a ticket exactly like this one.

> Aedict online has been down for a few days now. I use it very very frequently. Just letting you know!

Thank you so much, I'm honored you find Aedict useful :+1: 

Aedict Online should now be online, please let me know if everything works :+1:
