### ISSUE TITLE
Kanji not showing up in SKIP code search

### ISSUE THREAD

**Issue by Messyblue** [mvysny/aedict#969]
1. Tested on Samsung Galaxy S20+ and Galaxy Tab S7+
2. Android 12
3. 
![2022-07-31 23 04 58](https://user-images.githubusercontent.com/103365869/182083533-ddb0738f-0d28-4c6a-b37f-a2b6c7c740e1.png)
4. The character 揆 doesn't show up under the results of SKIP code search for 1-3-9, even though that's the correct code as confirmed on the character entry and on other sites. I tried a few other adjacent codes to no avail. I have the latest versions of the default dictionary set.

**Comment by mvysny** [comment]
Hi, thank you for letting me know. I just verified that indeed the Kanjidic lists the `揆` character with the SKIP code of 1-3-9, so the data file is correct as well. That leads me to believe that it's a bug in the Aedict search functionality. I will investigate and write a test to verify what's going on.

**Comment by Messyblue** [comment]
The character 衒 seems to be affected by the same issue, it doesn't show up in the results of SKIP code 1-3-8.

**Comment by mvysny** [comment]
Thank you, fixed in Aedict 3.50.23
