### ISSUE TITLE
Billing error for Ultimate

### ISSUE THREAD

**Issue by greggilbert** [mvysny/aedict#970]
1. Samsung Galaxy S10
2. Android 12
3. ![Screenshot_20220826-151146_Aedict](https://user-images.githubusercontent.com/169482/186976261-bad3698c-a576-4166-a36b-51c0ceeecd0c.jpg)
4. My monthly subscription to AEDict Ultimate was supposed to occur today, but it said the payment wouldn't go through. I tried two different cards but that didn't affect anything.
  Finally I contacted my credit card company and they said they didn't even see the request come through that they could decline, so it's something on the Google Play store side. I removed my subscription and then tried to readd it, and got this error: `Billing error #3 Billing Unavailable: Billing API version is not supported for the type requested: null`

**Comment by emhendersn** [comment]
I see the exact same error with my moto one 5g uw running android 11 with build number RPN31.Q1-51-30-14.
I'm in California.

**Comment by mvysny** [comment]
Thank you so much for letting me know, and I'm sorry for the issue. Let me take a look.

**Comment by mvysny** [comment]
I found out that the billing library is getting old. I will upgrade it and then release a new version of Aedict soon.

**Comment by mvysny** [comment]
Fixed, the fix will land in 3.50.23.

**Comment by mvysny** [comment]
Reopening: there seems to be a misconfiguration of my Google Play Payments Profile. I've asked Google for help to connect my user to the correct Payments profile.

**Comment by mvysny** [comment]
Google support is a disaster. One has to navigate a labyrinth of canned articles to reach a human support. I've opened two tickets, let's pray for a fast fix.

**Comment by mvysny** [comment]
This is the reply I got from Google:

> After checking, we see that the error [OR-CAC-13] you see in the Developer Console Payments Settings page is caused by the deletion of the payment profile. Please kindly note that you can only link a Play Console and payments profile once. After they're linked, they can't be unlinked or changed. With that being said, with payment profile deleted, you will need to reach out to Google Payments Center Help to see if they are able to restore your payment profile:

> If Payment team confirms the payment profile cannot be restored, the best and the only way to fix this issue will be for you to create a new Play Console account and transfer your apps to a new developer account:

What The Fuck GOOGLE?????? I move to a different country and I have to create a new developer account and migrate all apps there, because you fuckers can't update my payments profile to a different country?!?!? Would you also like me to fucking dance naked in the streets while I'm doing all of this bureaucratic crap?

Google is a disaster. This just shows that they have so much complexity underneath, we'll just have to wait and see for Google to fall over under its own weight.

**Comment by mvysny** [comment]
The saga continues. I was able to register my old Google account as an app developer, only to see in Google Play Console that the Account Is Closed and Can not be reactivated. I'm waiting for a refund for the Developer Registration Fee and I'll have to create a FOURTH user named Martin Vysny4, register that one, pay the fee, transfer all apps to him and ONLY THEN I will be able to receive payments.

**Comment by mvysny** [comment]
I've asked to transfer the apps to the new account martin.vysny3@gmail.com. I pray that this won't affect the subscription IDs and such. Damn you Google.

**Comment by mvysny** [comment]
Google is still processing the application transfer to the new account. 🤦🤦‍♀️🤦‍♂️

**Comment by mvysny** [comment]
The app transfer has been completed; everything has been set up properly on Google's side and the payments should now go through. The new Aedict release is still "pending review from Google" ( :facepalm: ) but the subscription payments should now go through. @greggilbert could you please test it out and let me know?

**Comment by greggilbert** [comment]
Confirmed as working. Still on v3.50.22, for what it's worth.

**Comment by mvysny** [comment]
Awesome, thank you so much for confirming so quickly. I'm so happy that the Google toolchain finally works :)

Thanks again for letting me know. Closing as fixed, but please feel free to reopen if anything stops working.
