### ISSUE TITLE
App won't let me past the dictionary update screen

### ISSUE THREAD

**Issue by colaprograms** [mvysny/aedict#979]
Aedict starts up to the "Aedict has been upgraded" screen and asks me to download dictionaries, but when I click the button, it does not download any new dictionaries and the screen does not go away. I tried deleting all dictionaries and re-downloading them, but this did not help. Changing the directory also didn't help. The app is currently unusable because of this.

The phone is an LG Velvet (LM-G900UM), Android version is 12 (G900UM30b).

I have attached two screenshots. Thanks for your time. @ @
![Screenshot_20230820-202055](https://github.com/mvysny/aedict/assets/48771028/36db9c28-4ca5-42bb-b3e1-28212dcb9df7)
![Screenshot_20230820-202101](https://github.com/mvysny/aedict/assets/48771028/3cd4b793-b9b3-42da-9817-5c4ae58ac840)

**Comment by mvysny** [comment]
Hi  I'm sorry to hear about your issues. Which Android version do you have please? Which aedict version? Could you go into the "expert settings" and post the result of the dictionary health check?

**Comment by maemigh** [comment]
Same issue. Sony Xperia 5-II on Android 12. I was able to make it to the download screen only once (and it downloaded), but then returned me to the screen that says I have no dictionaries.

This screen is generally non-responsive and heats up the phone (if I tap as fast as I can, sometimes I can get the expert settings to show, or the download button to work). I have also tried deleting all storage/cache and restarting phone, but no luck.

**Comment by mvysny** [comment]
Damn, this looks like an endless loop between WelcomeActivity and MainActivity. Fixing now.

**Comment by mvysny** [comment]
Trusting Android documentation, burned myself again.

**Comment by mvysny** [comment]
Should be fixed in Aedict 3.50.29 which will be available in Google Play soon. Closing as (hopefully) fixed :crossed_fingers:  , please reopen if the bug persists in 3.50.29 as well
