### ISSUE TITLE
Update SOD Stroke Order Diagrams Vector from 2019 version?

### ISSUE THREAD

**Issue by mikemorr** [mvysny/aedict#985]
I wonder if the SOD Stroke Order Diagrams Vector dictionary in Aedict could be updated to a more recent version. The one I have installed is dated 4/17/19 and it doesn't include recent updates to the https://github.com/KanjiVG/kanjivg repository.

**Comment by mvysny** [comment]
Great catch! The releases are published at https://github.com/KanjiVG/kanjivg/releases (namely the `kanjivg-*.xml.gz` is important). For a long time there was no update on the page ([2016/04/26](https://github.com/KanjiVG/kanjivg/releases/tag/r20160426) was the last one), but there's https://github.com/KanjiVG/kanjivg/releases/tag/r20230110 now. Let me run the indexer on it.

**Comment by mvysny** [comment]
Done - the new KanjiVG SOD data is available for download from Aedict. Thanks!

**Comment by mikemorr** [comment]
Thanks! Are the kanji Parts and Junctures calculated from this data? I updated, but I'm not seeing parts/junctures updates such as https://github.com/KanjiVG/kanjivg/issues/425

**Comment by mvysny** [comment]
Excellent catch! Parts and Junctures are actually hard-coded, so I need to update those as well. I'll also need to release new Aedict once that's done, in order for those to take effect.

**Comment by mvysny** [comment]
Fixed: I've uploaded newest kanjidic which should now correctly search based on the new set of parts and junctures. A new Aedict will be released later on, which should correctly display the new parts and junctures. Fixed in Aedict 3.51.4.
