### ISSUE TITLE
Kanji search crash

### ISSUE THREAD

**Issue by Dinges666** [mvysny/aedict#988]
When I use the kanji search function, select a kanji and then search, either a crash will occur or I will be returned to the word search, without the kanji being searched for.

Android version 13 is being used and it persists after removing and reinstalling the app and redownload of the dictionaries.

I used a random one in the screenshot but it happens with every one.
![Screenshot_20240720-091401](https://github.com/user-attachments/assets/dd91701d-282d-4181-880d-768300be9397)

**Comment by mvysny** [comment]
Hi, thank you for letting me know. Let me take a look.

**Comment by mvysny** [comment]
Reproduced; the Kotlin 2.0 closures aren't Serializable anymore, so Android can't Parcel them, and that's what's causing this problem. Fixing now.

**Comment by mvysny** [comment]
Fixed in Aedict 3.51.5
