### ISSUE TITLE
July 17 update breaks kanji search

### ISSUE THREAD

**Issue by donkoch** [mvysny/aedict#989]
Please provide:
1. Your phone brand and maker: Pixel 7
2. The exact Android version: 14
3. A full description of the issue you're experiencing. 

Select Kanji Search from menu.
Put kanji together using parts.
Hit the search icon -> it goes back to the main screen.
Select Kanji Search from menu, again.
Put kanji together.
Hit search icon -> Get "Aedict keeps stopping" message.

**Comment by mvysny** [comment]
Hi, sorry about that. Sounds like a duplicate of #988 - could you please upgrade to Aedict 3.51.5 and try again?

**Comment by mvysny** [comment]
Yup, it's a duplicate of #988, should be fixed in Aedict 3.51.5
