### ISSUE TITLE
July 17th update prevents launch of app

### ISSUE THREAD

**Issue by clintm99** [mvysny/aedict#991]
App fails to launch after 7/17 update.  No error.
Someone reported this in the play store comments / reviews. 

SM-F711U
Galaxy Z Flip3 5g
Android 14
5.4.254-qgki-28575149-abF711USQS8IXFC
Build UP1A.231005.007.F711USQS8IXFC

**Comment by mvysny** [comment]
Thanks! Closing as duplicate of #990 ; Aedict 3.51.6 will fix this issue; it's currently on Google Play, pending Google's review.

**Comment by AltoRetrato** [comment]
Glad to know a fix is on the way!
This update affected me more than the CrowdStrike one!
